### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  id: CantStartSingleInstanceException
  children:
  - Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor
  - Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.String)
  - Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: CantStartSingleInstanceException
  nameWithType: CantStartSingleInstanceException
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  type: Class
  summary: "単一インスタンス アプリケーション、後続のインスタンスが最初のアプリケーション インスタンスに接続できない場合は、この例外がスローされます。"
  remarks: "単一インスタンス アプリケーションは、コンピューターを一度に実行する通常のアプリケーションから、アプリケーションの&1; つだけのインスタンスは異なります。 後続のアプリケーション インスタンスが起動したら、そのコマンドライン引数を渡す最初のインスタンスのアプリケーションにお問い合わせくださいしようとします。 最初のインスタンスに接続できない場合、CantStartSingleInstanceException が後続のアプリケーション インスタンスで発生します。 Visual Basic アプリケーション モデルでは、例外で任意のコンテキスト情報は提供されません。       詳細については、次を参照してください。 [Visual Basic アプリケーション モデルの概要](~/add/includes/ajax-current-ext-md.md)です。"
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]

      public class CantStartSingleInstanceException : Exception
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  langs:
  - csharp
  name: CantStartSingleInstanceException()
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException()
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException()
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "新しいインスタンスを初期化、 <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException&quot;> </xref>クラスです。"
  remarks: "単一インスタンス アプリケーションは、コンピューターを一度に実行する通常のアプリケーションから、アプリケーションの&1; つだけのインスタンスは異なります。 後続のアプリケーション インスタンスが起動したら、そのコマンドライン引数を渡す最初のインスタンスのアプリケーションにお問い合わせくださいしようとします。 最初のインスタンスに接続できない場合、<xref:Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException>は後続のアプリケーション インスタンスで発生します</xref:Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException>。 詳細については、次を参照してください。 [Visual Basic アプリケーション モデルの概要](~/add/includes/ajax-current-ext-md.md)です。       次の表は、 <xref:Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException>。</xref:Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException>のインスタンスの初期プロパティ値を示しています。      |||  |-|-|  |プロパティ |値 |  |<xref:System.Exception.InnerException%2A>|Null 参照 (`Nothing` Visual Basic で). |  |<xref:System.Exception.Message%2A>|ローカライズされたエラー メッセージ文字列 |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> 。"
  syntax:
    content: public CantStartSingleInstanceException ();
    parameters: []
  overload: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  langs:
  - csharp
  name: CantStartSingleInstanceException(String)
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException(String)
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException(String)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "新しいインスタンスを初期化、 <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException&quot;> </xref>指定したエラー メッセージを使用します。"
  remarks: "内容、`message`パラメーターをユーザーが理解できるものではします。 このコンス トラクターの呼び出し元は、この文字列が現在のシステムのカルチャに合わせてローカライズ済みであることを確認するために必要です。       <xref:Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException><xref:System.Exception>。</xref:System.Exception>から継承します。</xref:Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException> このコンス トラクターのプロパティの設定、<xref:System.Exception>オブジェクトの次の表に示すようにします</xref:System.Exception>。      |||  |-|-|  |プロパティ |値 |  |<xref:System.Exception.InnerException%2A>|Null 参照 (`Nothing` Visual Basic で) |  |<xref:System.Exception.Message%2A>|`message`文字列です |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> 。"
  syntax:
    content: public CantStartSingleInstanceException (string message);
    parameters:
    - id: message
      type: System.String
      description: "エラーを説明するメッセージ。"
  overload: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  langs:
  - csharp
  name: CantStartSingleInstanceException(SerializationInfo,StreamingContext)
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException(SerializationInfo,StreamingContext)
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "新しいインスタンスを初期化、 <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException&quot;> </xref>シリアル化されたデータを持つクラス。"
  remarks: "このコンス トラクターは、ストリームで送信された例外オブジェクトを再構成する逆シリアル化中に呼び出されます。"
  syntax:
    content: protected CantStartSingleInstanceException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "<xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref>スローされた例外に関する、シリアル化されたオブジェクト データを保持するオブジェクト。"
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "<xref:System.Runtime.Serialization.StreamingContext>元または転送先に関するコンテキスト情報を含むオブジェクトです</xref:System.Runtime.Serialization.StreamingContext>。"
  overload: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  langs:
  - csharp
  name: CantStartSingleInstanceException(String,Exception)
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException(String,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException(String,Exception)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "新しいインスタンスを初期化、 <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException&quot;> </xref>指定したエラー メッセージおよびこの例外の原因となった内部例外への参照を持つクラス。"
  remarks: "内容、`message`パラメーターをユーザーが理解できるものではします。 このコンス トラクターの呼び出し元は、この文字列が現在のシステムのカルチャに合わせてローカライズ済みであることを確認するために必要です。       前の例外への参照を含める必要があります前の例外の直接の結果としてスローされる例外、<xref:System.Exception.InnerException%2A>プロパティ</xref:System.Exception.InnerException%2A>。 <xref:System.Exception.InnerException%2A>プロパティが同じ場合は、コンス トラクター、または null 参照に渡される値を返します、<xref:System.Exception.InnerException%2A>プロパティがコンス トラクターには、内部例外値を指定していません</xref:System.Exception.InnerException%2A></xref:System.Exception.InnerException%2A>。       次の表は、 <xref:System.ApplicationException>。</xref:System.ApplicationException>のインスタンスの初期プロパティ値を示しています。      |||  |-|-|  |プロパティ |値 |  |<xref:System.Exception.InnerException%2A>|`inner`参照 |。  |<xref:System.Exception.Message%2A>|`message`文字列です |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> 。"
  syntax:
    content: public CantStartSingleInstanceException (string message, Exception inner);
    parameters:
    - id: message
      type: System.String
      description: "A<xref:System.String>エラーを説明するオブジェクト</xref:System.String>。"
    - id: inner
      type: System.Exception
      description: "<xref:System.Exception>現在の例外の原因となったオブジェクトです</xref:System.Exception>。 場合、<xref:System.Exception.InnerException*>パラメーターが null 参照ではありません (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref> Visual Basic で) で現在の例外が発生、 <xref uid=&quot;langword_csharp_Catch&quot; name=&quot;Catch&quot; href=&quot;&quot;> </xref>ブロックは、内部例外を処理する</xref:System.Exception.InnerException*>。"
  overload: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  isExternal: false
  name: CantStartSingleInstanceException()
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException()
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException()
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.String)
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  isExternal: false
  name: CantStartSingleInstanceException(String)
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException(String)
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  isExternal: false
  name: CantStartSingleInstanceException(SerializationInfo,StreamingContext)
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException(SerializationInfo,StreamingContext)
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.String,System.Exception)
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  isExternal: false
  name: CantStartSingleInstanceException(String,Exception)
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException(String,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException(String,Exception)
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor*
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  isExternal: false
  name: CantStartSingleInstanceException
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException
