### YamlMime:ManagedReference
items:
- uid: System.Configuration.ElementInformation
  id: ElementInformation
  children:
  - System.Configuration.ElementInformation.Errors
  - System.Configuration.ElementInformation.IsCollection
  - System.Configuration.ElementInformation.IsLocked
  - System.Configuration.ElementInformation.IsPresent
  - System.Configuration.ElementInformation.LineNumber
  - System.Configuration.ElementInformation.Properties
  - System.Configuration.ElementInformation.Source
  - System.Configuration.ElementInformation.Type
  - System.Configuration.ElementInformation.Validator
  langs:
  - csharp
  name: ElementInformation
  nameWithType: ElementInformation
  fullName: System.Configuration.ElementInformation
  type: Class
  summary: "構成内の各要素に関するメタ情報が含まれています。 このクラスは継承できません。"
  remarks: "ElementInformation オブジェクトには、構成内の各要素に関するメタ情報が含まれています。 このオブジェクトは、検証して、個々 の要素のプロパティを変更するときに使用できます。"
  example:
  - "The following example shows how to get the ElementInformation associated with a <xref:System.Configuration.ConfigurationElement> object.  \n  \n [!code-cs[System.Configuration.ConfigurationElement#80](~/add/codesnippet/csharp/t-system.configuration.e_1.cs)]\n [!code-vb[System.Configuration.ConfigurationElement#80](~/add/codesnippet/visualbasic/t-system.configuration.e_1.vb)]  \n  \n The following excerpt shows the configuration used by the previous code example.  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\"?>  \n<configuration>  \n  <configSections>  \n    <section name=\"MyUrls\" type=\"Samples.AspNet.UrlsSection,  \n      ConfigurationElement, Version=1.0.0.0, Culture=neutral,  \n      PublicKeyToken=null\" allowDefinition=\"Everywhere\"  \n      allowExeDefinition=\"MachineToApplication\"  \n      restartOnExternalChanges=\"true\" />  \n  </configSections>  \n  <MyUrls name=\"MyFavorites\">  \n    <simple name=\"Contoso\" url=\"http://www.contoso.com\" port=\"8080\" />  \n    <urls>  \n      <clear />  \n      <add name=\"Microsoft\" url=\"http://www.microsoft.com\" port=\"0\" />  \n    </urls>  \n  </MyUrls>  \n</configuration>  \n```"
  syntax:
    content: public sealed class ElementInformation
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ElementInformation.Errors
  id: Errors
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: Errors
  nameWithType: ElementInformation.Errors
  fullName: System.Configuration.ElementInformation.Errors
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "関連付けられている要素とサブ要素のエラーを取得します。"
  remarks: ''
  example:
  - "The following example shows how to use the Errors collection.  \n  \n [!code-cs[System.Configuration.ConfigurationElement#89](~/add/codesnippet/csharp/p-system.configuration.e_5_1.cs)]\n [!code-vb[System.Configuration.ConfigurationElement#89](~/add/codesnippet/visualbasic/p-system.configuration.e_5_1.vb)]"
  syntax:
    content: public System.Collections.ICollection Errors { get; }
    return:
      type: System.Collections.ICollection
      description: "関連付けられている要素とサブ要素のエラーを含むコレクション"
  overload: System.Configuration.ElementInformation.Errors*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ElementInformation.IsCollection
  id: IsCollection
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: IsCollection
  nameWithType: ElementInformation.IsCollection
  fullName: System.Configuration.ElementInformation.IsCollection
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "示す値を取得するかどうか、関連付けられている<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>オブジェクトが、 <xref href=&quot;System.Configuration.ConfigurationElementCollection&quot;> </xref>コレクション。"
  remarks: ''
  example:
  - "The following example shows how to use the IsCollection property.  \n  \n [!code-cs[System.Configuration.ConfigurationElement#81](~/add/codesnippet/csharp/p-system.configuration.e_8_1.cs)]\n [!code-vb[System.Configuration.ConfigurationElement#81](~/add/codesnippet/visualbasic/p-system.configuration.e_8_1.vb)]"
  syntax:
    content: public bool IsCollection { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>場合、関連付けられている<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>オブジェクトが、 <xref href=&quot;System.Configuration.ConfigurationElementCollection&quot;> </xref>コレクションです。 それ以外の場合、 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>です。"
  overload: System.Configuration.ElementInformation.IsCollection*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ElementInformation.IsLocked
  id: IsLocked
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: IsLocked
  nameWithType: ElementInformation.IsLocked
  fullName: System.Configuration.ElementInformation.IsLocked
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "示す値を取得するかどうか、関連付けられている<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>オブジェクトは変更できません。"
  remarks: "IsLocked プロパティから返される`true`で関連する要素がロックされている場合、 <xref:System.Configuration.SectionInformation.AllowOverride%2A>、 <xref:System.Configuration.SectionInformation.AllowDefinition%2A>、または<xref:System.Configuration.ConfigurationElement.LockAllAttributesExcept%2A>プロパティ</xref:System.Configuration.ConfigurationElement.LockAllAttributesExcept%2A></xref:System.Configuration.SectionInformation.AllowDefinition%2A></xref:System.Configuration.SectionInformation.AllowOverride%2A>。"
  example:
  - "The following example shows how to use the IsLocked property.  \n  \n [!code-cs[System.Configuration.ConfigurationElement#82](~/add/codesnippet/csharp/p-system.configuration.e_2_1.cs)]\n [!code-vb[System.Configuration.ConfigurationElement#82](~/add/codesnippet/visualbasic/p-system.configuration.e_2_1.vb)]"
  syntax:
    content: public bool IsLocked { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>場合、関連付けられている<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>オブジェクトが変更された、それ以外にすることはできません<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>です。"
  overload: System.Configuration.ElementInformation.IsLocked*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ElementInformation.IsPresent
  id: IsPresent
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: IsPresent
  nameWithType: ElementInformation.IsPresent
  fullName: System.Configuration.ElementInformation.IsPresent
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "示す値を取得するかどうか、関連付けられている<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>オブジェクトは、構成ファイル。"
  remarks: ''
  example:
  - "The following example shows how to use the IsPresent property.  \n  \n [!code-cs[System.Configuration.ConfigurationElement#83](~/add/codesnippet/csharp/p-system.configuration.e_0_1.cs)]\n [!code-vb[System.Configuration.ConfigurationElement#83](~/add/codesnippet/visualbasic/p-system.configuration.e_0_1.vb)]"
  syntax:
    content: public bool IsPresent { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>場合、関連付けられている<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>オブジェクトが、構成ファイルにあるそれ以外の場合、 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>です。"
  overload: System.Configuration.ElementInformation.IsPresent*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ElementInformation.LineNumber
  id: LineNumber
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: LineNumber
  nameWithType: ElementInformation.LineNumber
  fullName: System.Configuration.ElementInformation.LineNumber
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "構成ファイル内の行番号を取得場所、関連付けられている<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>オブジェクトを定義します。"
  remarks: ''
  example:
  - "The following example shows how to use the LineNumber property.  \n  \n [!code-cs[System.Configuration.ConfigurationElement#84](~/add/codesnippet/csharp/p-system.configuration.e_7_1.cs)]\n [!code-vb[System.Configuration.ConfigurationElement#84](~/add/codesnippet/visualbasic/p-system.configuration.e_7_1.vb)]"
  syntax:
    content: public int LineNumber { get; }
    return:
      type: System.Int32
      description: "ファイル、構成内の行番号、関連付けられている<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>オブジェクトを定義します。"
  overload: System.Configuration.ElementInformation.LineNumber*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ElementInformation.Properties
  id: Properties
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: Properties
  nameWithType: ElementInformation.Properties
  fullName: System.Configuration.ElementInformation.Properties
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "取得、 <xref href=&quot;System.Configuration.PropertyInformationCollection&quot;> </xref> 、関連するプロパティのコレクション<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>オブジェクト。"
  remarks: "プロパティ、<xref:System.Configuration.ConfigurationElement>オブジェクトは、属性とサブ要素の構成ファイルには、その構成要素に関連付けられている</xref:System.Configuration.ConfigurationElement>。"
  example:
  - "The following example shows how to get the Properties collection.  \n  \n [!code-cs[System.Configuration.ConfigurationElement#85](~/add/codesnippet/csharp/p-system.configuration.e_4_1.cs)]\n [!code-vb[System.Configuration.ConfigurationElement#85](~/add/codesnippet/visualbasic/p-system.configuration.e_4_1.vb)]"
  syntax:
    content: public System.Configuration.PropertyInformationCollection Properties { get; }
    return:
      type: System.Configuration.PropertyInformationCollection
      description: "A <xref href=&quot;System.Configuration.PropertyInformationCollection&quot;> </xref> 、関連するプロパティのコレクション<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>オブジェクト。"
  overload: System.Configuration.ElementInformation.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ElementInformation.Source
  id: Source
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: Source
  nameWithType: ElementInformation.Source
  fullName: System.Configuration.ElementInformation.Source
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "ソース ファイルの取得場所、関連付けられている<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>発生オブジェクト。"
  remarks: "A<xref:System.Configuration.ConfigurationElement>オブジェクトを作成して、既定の状態でこのプロパティは後者を返します`null`</xref:System.Configuration.ConfigurationElement>。"
  example:
  - "The following example shows how to use the Source property.  \n  \n [!code-cs[System.Configuration.ConfigurationElement#86](~/add/codesnippet/csharp/p-system.configuration.e_1_1.cs)]\n [!code-vb[System.Configuration.ConfigurationElement#86](~/add/codesnippet/visualbasic/p-system.configuration.e_1_1.vb)]"
  syntax:
    content: public string Source { get; }
    return:
      type: System.String
      description: "ソース ファイルの場所、関連付けられている<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>発生オブジェクト。"
  overload: System.Configuration.ElementInformation.Source*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ElementInformation.Type
  id: Type
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: Type
  nameWithType: ElementInformation.Type
  fullName: System.Configuration.ElementInformation.Type
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "関連付けられている型を取得<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>オブジェクト。"
  remarks: ''
  example:
  - "The following example shows how to use the Type property.  \n  \n [!code-cs[System.Configuration.ConfigurationElement#87](~/add/codesnippet/csharp/p-system.configuration.e_3_1.cs)]\n [!code-vb[System.Configuration.ConfigurationElement#87](~/add/codesnippet/visualbasic/p-system.configuration.e_3_1.vb)]"
  syntax:
    content: public Type Type { get; }
    return:
      type: System.Type
      description: "関連付けられている型<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>オブジェクト。"
  overload: System.Configuration.ElementInformation.Type*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ElementInformation.Validator
  id: Validator
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: Validator
  nameWithType: ElementInformation.Validator
  fullName: System.Configuration.ElementInformation.Validator
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "関連付けられている検証に使用されるオブジェクトを取得<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>オブジェクト。"
  remarks: "検証コントロール オブジェクトが必要でないと、このプロパティが返す可能性があります`null`です。"
  example:
  - "The following example shows how to use the Validator property.  \n  \n [!code-cs[System.Configuration.ConfigurationElement#88](~/add/codesnippet/csharp/p-system.configuration.e_6_1.cs)]\n [!code-vb[System.Configuration.ConfigurationElement#88](~/add/codesnippet/visualbasic/p-system.configuration.e_6_1.vb)]"
  syntax:
    content: public System.Configuration.ConfigurationValidatorBase Validator { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "関連付けられている検証に使用するオブジェクト<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>オブジェクト。"
  overload: System.Configuration.ElementInformation.Validator*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ElementInformation.Errors
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: Errors
  nameWithType: ElementInformation.Errors
  fullName: System.Configuration.ElementInformation.Errors
- uid: System.Collections.ICollection
  parent: System.Collections
  isExternal: true
  name: ICollection
  nameWithType: ICollection
  fullName: System.Collections.ICollection
- uid: System.Configuration.ElementInformation.IsCollection
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: IsCollection
  nameWithType: ElementInformation.IsCollection
  fullName: System.Configuration.ElementInformation.IsCollection
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.ElementInformation.IsLocked
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: IsLocked
  nameWithType: ElementInformation.IsLocked
  fullName: System.Configuration.ElementInformation.IsLocked
- uid: System.Configuration.ElementInformation.IsPresent
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: IsPresent
  nameWithType: ElementInformation.IsPresent
  fullName: System.Configuration.ElementInformation.IsPresent
- uid: System.Configuration.ElementInformation.LineNumber
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: LineNumber
  nameWithType: ElementInformation.LineNumber
  fullName: System.Configuration.ElementInformation.LineNumber
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.ElementInformation.Properties
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: Properties
  nameWithType: ElementInformation.Properties
  fullName: System.Configuration.ElementInformation.Properties
- uid: System.Configuration.PropertyInformationCollection
  parent: System.Configuration
  isExternal: false
  name: PropertyInformationCollection
  nameWithType: PropertyInformationCollection
  fullName: System.Configuration.PropertyInformationCollection
- uid: System.Configuration.ElementInformation.Source
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: Source
  nameWithType: ElementInformation.Source
  fullName: System.Configuration.ElementInformation.Source
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ElementInformation.Type
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: Type
  nameWithType: ElementInformation.Type
  fullName: System.Configuration.ElementInformation.Type
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.ElementInformation.Validator
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: Validator
  nameWithType: ElementInformation.Validator
  fullName: System.Configuration.ElementInformation.Validator
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.ElementInformation.Errors*
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: Errors
  nameWithType: ElementInformation.Errors
- uid: System.Configuration.ElementInformation.IsCollection*
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: IsCollection
  nameWithType: ElementInformation.IsCollection
- uid: System.Configuration.ElementInformation.IsLocked*
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: IsLocked
  nameWithType: ElementInformation.IsLocked
- uid: System.Configuration.ElementInformation.IsPresent*
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: IsPresent
  nameWithType: ElementInformation.IsPresent
- uid: System.Configuration.ElementInformation.LineNumber*
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: LineNumber
  nameWithType: ElementInformation.LineNumber
- uid: System.Configuration.ElementInformation.Properties*
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: Properties
  nameWithType: ElementInformation.Properties
- uid: System.Configuration.ElementInformation.Source*
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: Source
  nameWithType: ElementInformation.Source
- uid: System.Configuration.ElementInformation.Type*
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: Type
  nameWithType: ElementInformation.Type
- uid: System.Configuration.ElementInformation.Validator*
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: Validator
  nameWithType: ElementInformation.Validator
