### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  id: TcpConnectionPoolSettingsElement
  children:
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.#ctor
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties
  langs:
  - csharp
  name: TcpConnectionPoolSettingsElement
  nameWithType: TcpConnectionPoolSettingsElement
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  type: Class
  summary: "TCP トランスポートの追加の接続プール設定を指定する構成要素を表します。 このクラスは継承できません。"
  syntax:
    content: 'public sealed class TcpConnectionPoolSettingsElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: TcpConnectionPoolSettingsElement()
  nameWithType: TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement()
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement&quot;> </xref>クラスです。"
  syntax:
    content: public TcpConnectionPoolSettingsElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName
  id: GroupName
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: GroupName
  nameWithType: TcpConnectionPoolSettingsElement.GroupName
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得または送信チャネルに使用される接続プールの名前を定義する文字列を設定します。"
  remarks: "ストリーミング モードは、接続が共有されません、接続プールが無効になっていることを意味します。 既定値は、&quot;default&quot;文字列です。 個別のグループに、特定のクライアント接続を分離するには、この値を変更することができます。"
  syntax:
    content: public string GroupName { get; set; }
    return:
      type: System.String
      description: "送信チャネルに使用される接続プールの名前。"
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
  id: IdleTimeout
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: TcpConnectionPoolSettingsElement.IdleTimeout
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得または設定期間、接続は切断されるまでアイドル状態であることができます。"
  syntax:
    content: public TimeSpan IdleTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "正<xref:System.TimeSpan>接続は切断されるまでアイドル状態であることができます、最大時間を指定します</xref:System.TimeSpan>。 既定値は、00時 02分: 00 です。"
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout
  id: LeaseTimeout
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: LeaseTimeout
  nameWithType: TcpConnectionPoolSettingsElement.LeaseTimeout
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得またはアクティブな接続が閉じられるまでの時間間隔を設定します。"
  remarks: "アクティブに転送中ではなく、接続キャッシュに返された後、接続は閉じられます。 TCP トランスポートによって使用される接続キャッシュが上限はキャッシュ<xref:System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint%2A>。</xref:System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint%2A>で設定されている各エンドポイントの必要に応じて新しい接続を作成します。"
  syntax:
    content: public TimeSpan LeaseTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "A<xref:System.TimeSpan>構造との TCP 接続が閉じられるまでの期間を指定します</xref:System.TimeSpan>。"
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  id: MaxOutboundConnectionsPerEndpoint
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得またはサービスによって開始されるリモート エンドポイントへの接続の最大数を設定します。"
  remarks: "制限を超えた接続は、制限の下の領域が使用可能になるまでキューに格納します。 このプロパティは、接続入れたままにキューに置かれた例外をスローする前に期間を制限します。       このプロパティは、特定のサービス エンドポイントをクライアントから同時にアクティブな接続の数を制限します。 複数のアクティブなクライアント接続でこの値を超えると、サービスがクライアントに応答しないように見える可能性があります。 この場合、この値は、特定のエンドポイントへの予想される同時クライアント接続の最大数を超えるを調整する必要があります。       この設定は、 <xref:System.ServiceModel.Channels.MaxPooledConnections%2A> <xref:System.ServiceModel.Channels.TcpChannelListener>。</xref:System.ServiceModel.Channels.TcpChannelListener></xref:System.ServiceModel.Channels.MaxPooledConnections%2A>設定に使用される場合、値をサービス側で設定することもできます。"
  syntax:
    content: public int MaxOutboundConnectionsPerEndpoint { get; set; }
    return:
      type: System.Int32
      description: "サービスによって開始されるリモート エンドポイントへの接続の最大数。 既定値は 10 です。"
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: Properties
  nameWithType: TcpConnectionPoolSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "追加します。"
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.#ctor
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: TcpConnectionPoolSettingsElement()
  nameWithType: TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement()
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement()
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: GroupName
  nameWithType: TcpConnectionPoolSettingsElement.GroupName
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: IdleTimeout
  nameWithType: TcpConnectionPoolSettingsElement.IdleTimeout
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: LeaseTimeout
  nameWithType: TcpConnectionPoolSettingsElement.LeaseTimeout
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: Properties
  nameWithType: TcpConnectionPoolSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.#ctor*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: TcpConnectionPoolSettingsElement
  nameWithType: TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: GroupName
  nameWithType: TcpConnectionPoolSettingsElement.GroupName
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: IdleTimeout
  nameWithType: TcpConnectionPoolSettingsElement.IdleTimeout
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: LeaseTimeout
  nameWithType: TcpConnectionPoolSettingsElement.LeaseTimeout
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: Properties
  nameWithType: TcpConnectionPoolSettingsElement.Properties
