### YamlMime:ManagedReference
items:
- uid: System.Configuration.NameValueFileSectionHandler
  id: NameValueFileSectionHandler
  children:
  - System.Configuration.NameValueFileSectionHandler.#ctor
  - System.Configuration.NameValueFileSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: NameValueFileSectionHandler
  nameWithType: NameValueFileSectionHandler
  fullName: System.Configuration.NameValueFileSectionHandler
  type: Class
  summary: "構成ファイルへのアクセスを提供します。 この型では、構成の .NET Framework インフラストラクチャをサポートしているし、コードから直接使用するものではありません。"
  remarks: "`file`の属性、`<appSettings>`セクションでは、カスタムのアプリケーション構成設定を含む外部ファイルへの相対パスを指定します。 ファイルで詳細情報が果たす、`<appSettings>`構成ファイル内のセクションです。 NameValueFileSectionHandler クラスを使用してファイルにアクセスします。 ファイルのルート要素は、セクションを参照することと一致する必要があります。"
  syntax:
    content: 'public class NameValueFileSectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.NameValueFileSectionHandler.#ctor
  id: '#ctor'
  parent: System.Configuration.NameValueFileSectionHandler
  langs:
  - csharp
  name: NameValueFileSectionHandler()
  nameWithType: NameValueFileSectionHandler.NameValueFileSectionHandler()
  fullName: System.Configuration.NameValueFileSectionHandler.NameValueFileSectionHandler()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Configuration.NameValueFileSectionHandler&quot;> </xref>クラスです。"
  syntax:
    content: public NameValueFileSectionHandler ();
    parameters: []
  overload: System.Configuration.NameValueFileSectionHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.NameValueFileSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.NameValueFileSectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: NameValueFileSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.NameValueFileSectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "新しい構成ハンドラーを作成し、指定したパラメーターに基づくセクション ハンドラー コレクションに追加します。"
  remarks: "`parent`オブジェクト パラメーターは、対応する親構成セクションの構成設定として機能します。 `configContext`オブジェクト パラメーターは構成セクション ハンドラーが構成値を計算する対象の仮想パス。 通常このパラメーターは予約されており`null`です。 `section`パラメーターは、<xref:System.Xml.XmlNode>を処理するための構成情報を格納します</xref:System.Xml.XmlNode>。 `section`パラメーターは、構成セクションの XML コンテンツに直接アクセスを提供します。"
  syntax:
    content: public object Create (object parent, object configContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "親オブジェクトです。"
    - id: configContext
      type: System.Object
      description: "構成のコンテキスト オブジェクト。"
    - id: section
      type: System.Xml.XmlNode
      description: "セクションの XML ノードです。"
    return:
      type: System.Object
      description: "構成オブジェクト。"
  overload: System.Configuration.NameValueFileSectionHandler.Create*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "The file specified in the <xref uid=\"langword_csharp_file\" name=\"file\" href=\"\"></xref> attribute of <code>section</code> exists but cannot be loaded.  \n  \n \\- or -  \n  \n The <xref uid=\"langword_csharp_name\" name=\"name\" href=\"\"></xref> attribute of <code>section</code> does not match the root element of the file specified in the <xref uid=\"langword_csharp_file\" name=\"file\" href=\"\"></xref> attribute."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.Configuration.NameValueFileSectionHandler.#ctor
  parent: System.Configuration.NameValueFileSectionHandler
  isExternal: false
  name: NameValueFileSectionHandler()
  nameWithType: NameValueFileSectionHandler.NameValueFileSectionHandler()
  fullName: System.Configuration.NameValueFileSectionHandler.NameValueFileSectionHandler()
- uid: System.Configuration.NameValueFileSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.NameValueFileSectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: NameValueFileSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.NameValueFileSectionHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.NameValueFileSectionHandler.#ctor*
  parent: System.Configuration.NameValueFileSectionHandler
  isExternal: false
  name: NameValueFileSectionHandler
  nameWithType: NameValueFileSectionHandler.NameValueFileSectionHandler
- uid: System.Configuration.NameValueFileSectionHandler.Create*
  parent: System.Configuration.NameValueFileSectionHandler
  isExternal: false
  name: Create
  nameWithType: NameValueFileSectionHandler.Create
