### YamlMime:ManagedReference
items:
- uid: System.Drawing.Printing.QueryPageSettingsEventArgs
  id: QueryPageSettingsEventArgs
  children:
  - System.Drawing.Printing.QueryPageSettingsEventArgs.#ctor(System.Drawing.Printing.PageSettings)
  - System.Drawing.Printing.QueryPageSettingsEventArgs.PageSettings
  langs:
  - csharp
  name: QueryPageSettingsEventArgs
  nameWithType: QueryPageSettingsEventArgs
  fullName: System.Drawing.Printing.QueryPageSettingsEventArgs
  type: Class
  summary: "データを提供、 <xref href=&quot;System.Drawing.Printing.PrintDocument.QueryPageSettings&quot;> </xref>イベント。"
  remarks: "別のページの設定を使用してドキュメントの各ページを印刷することができます。 設定ページの個々 のプロパティを変更することによって、<xref:System.Drawing.Printing.QueryPageSettingsEventArgs.PageSettings%2A>プロパティまたは<xref:System.Drawing.Printing.PageSettings></xref:System.Drawing.Printing.PageSettings>プロパティを設定して</xref:System.Drawing.Printing.QueryPageSettingsEventArgs.PageSettings%2A>。 印刷ジョブを設定して取り消すこともできます、<xref:System.ComponentModel.CancelEventArgs.Cancel%2A>プロパティを`true`</xref:System.ComponentModel.CancelEventArgs.Cancel%2A>。"
  example:
  - "The following code example prints a document with the first page in color, if the printer supports it. The example assumes that a <xref:System.Drawing.Printing.PrintDocument> variable named `printDoc` has been created, and the <xref:System.Drawing.Printing.PrintDocument.PrintPage> and <xref:System.Drawing.Printing.PrintDocument.QueryPageSettings> events are handled.  \n  \n Use the <xref:System.Drawing> and <xref:System.Drawing.Printing> namespaces for this example.  \n  \n [!code-cs[PaperSource and PaperSize Example with Resolution#6](~/add/codesnippet/csharp/t-system.drawing.printin_1_1.cs)]\n [!code-cpp[PaperSource and PaperSize Example with Resolution#6](~/add/codesnippet/cpp/t-system.drawing.printin_1_1.cpp)]\n [!code-vb[PaperSource and PaperSize Example with Resolution#6](~/add/codesnippet/visualbasic/t-system.drawing.printin_1_1.vb)]"
  syntax:
    content: 'public class QueryPageSettingsEventArgs : System.Drawing.Printing.PrintEventArgs'
  inheritance:
  - System.ComponentModel.CancelEventArgs
  - System.Drawing.Printing.PrintEventArgs
  implements: []
  inheritedMembers:
  - System.Drawing.Printing.PrintEventArgs.PrintAction
  platform:
  - net462
- uid: System.Drawing.Printing.QueryPageSettingsEventArgs.#ctor(System.Drawing.Printing.PageSettings)
  id: '#ctor(System.Drawing.Printing.PageSettings)'
  parent: System.Drawing.Printing.QueryPageSettingsEventArgs
  langs:
  - csharp
  name: QueryPageSettingsEventArgs(PageSettings)
  nameWithType: QueryPageSettingsEventArgs.QueryPageSettingsEventArgs(PageSettings)
  fullName: System.Drawing.Printing.QueryPageSettingsEventArgs.QueryPageSettingsEventArgs(PageSettings)
  type: Constructor
  assemblies:
  - System.Drawing
  namespace: System.Drawing.Printing
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Drawing.Printing.QueryPageSettingsEventArgs&quot;> </xref>クラスです。"
  syntax:
    content: public QueryPageSettingsEventArgs (System.Drawing.Printing.PageSettings pageSettings);
    parameters:
    - id: pageSettings
      type: System.Drawing.Printing.PageSettings
      description: "印刷するページのページ設定します。"
  overload: System.Drawing.Printing.QueryPageSettingsEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Drawing.Printing.QueryPageSettingsEventArgs.PageSettings
  id: PageSettings
  parent: System.Drawing.Printing.QueryPageSettingsEventArgs
  langs:
  - csharp
  name: PageSettings
  nameWithType: QueryPageSettingsEventArgs.PageSettings
  fullName: System.Drawing.Printing.QueryPageSettingsEventArgs.PageSettings
  type: Property
  assemblies:
  - System.Drawing
  namespace: System.Drawing.Printing
  summary: "取得または印刷するページのページの設定を設定します。"
  remarks: "別のページの設定を使用してドキュメントの各ページを印刷することができます。 PageSettings プロパティの個々 のプロパティを変更することによって、または<xref:System.Drawing.Printing.PageSettings>。</xref:System.Drawing.Printing.PageSettings>プロパティを設定して、ページの設定を設定します。 印刷ジョブを設定して取り消すこともできます、<xref:System.ComponentModel.CancelEventArgs.Cancel%2A>プロパティを`true`</xref:System.ComponentModel.CancelEventArgs.Cancel%2A>。"
  example:
  - "The following code example prints a document with the first page in color, if the printer supports it. The example assumes that a <xref:System.Drawing.Printing.PrintDocument> variable named `printDoc` has been created, and the <xref:System.Drawing.Printing.PrintDocument.PrintPage> and <xref:System.Drawing.Printing.PrintDocument.QueryPageSettings> events are handled.  \n  \n Use the <xref:System.Drawing> and <xref:System.Drawing.Printing> namespaces for this example.  \n  \n [!code-cs[PaperSource and PaperSize Example with Resolution#6](~/add/codesnippet/csharp/p-system.drawing.printin_18_1.cs)]\n [!code-cpp[PaperSource and PaperSize Example with Resolution#6](~/add/codesnippet/cpp/p-system.drawing.printin_18_1.cpp)]\n [!code-vb[PaperSource and PaperSize Example with Resolution#6](~/add/codesnippet/visualbasic/p-system.drawing.printin_18_1.vb)]"
  syntax:
    content: public System.Drawing.Printing.PageSettings PageSettings { get; set; }
    return:
      type: System.Drawing.Printing.PageSettings
      description: "印刷するページのページ設定します。"
  overload: System.Drawing.Printing.QueryPageSettingsEventArgs.PageSettings*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Drawing.Printing.PrintEventArgs
  isExternal: false
  name: System.Drawing.Printing.PrintEventArgs
- uid: System.Drawing.Printing.QueryPageSettingsEventArgs.#ctor(System.Drawing.Printing.PageSettings)
  parent: System.Drawing.Printing.QueryPageSettingsEventArgs
  isExternal: false
  name: QueryPageSettingsEventArgs(PageSettings)
  nameWithType: QueryPageSettingsEventArgs.QueryPageSettingsEventArgs(PageSettings)
  fullName: System.Drawing.Printing.QueryPageSettingsEventArgs.QueryPageSettingsEventArgs(PageSettings)
- uid: System.Drawing.Printing.PageSettings
  parent: System.Drawing.Printing
  isExternal: false
  name: PageSettings
  nameWithType: PageSettings
  fullName: System.Drawing.Printing.PageSettings
- uid: System.Drawing.Printing.QueryPageSettingsEventArgs.PageSettings
  parent: System.Drawing.Printing.QueryPageSettingsEventArgs
  isExternal: false
  name: PageSettings
  nameWithType: QueryPageSettingsEventArgs.PageSettings
  fullName: System.Drawing.Printing.QueryPageSettingsEventArgs.PageSettings
- uid: System.Drawing.Printing.QueryPageSettingsEventArgs.#ctor*
  parent: System.Drawing.Printing.QueryPageSettingsEventArgs
  isExternal: false
  name: QueryPageSettingsEventArgs
  nameWithType: QueryPageSettingsEventArgs.QueryPageSettingsEventArgs
- uid: System.Drawing.Printing.QueryPageSettingsEventArgs.PageSettings*
  parent: System.Drawing.Printing.QueryPageSettingsEventArgs
  isExternal: false
  name: PageSettings
  nameWithType: QueryPageSettingsEventArgs.PageSettings
