### YamlMime:ManagedReference
items:
- uid: System.Security.Permissions.EnvironmentPermissionAttribute
  id: EnvironmentPermissionAttribute
  children:
  - System.Security.Permissions.EnvironmentPermissionAttribute.#ctor(System.Security.Permissions.SecurityAction)
  - System.Security.Permissions.EnvironmentPermissionAttribute.All
  - System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission
  - System.Security.Permissions.EnvironmentPermissionAttribute.Read
  - System.Security.Permissions.EnvironmentPermissionAttribute.Write
  langs:
  - csharp
  name: EnvironmentPermissionAttribute
  nameWithType: EnvironmentPermissionAttribute
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute
  type: Class
  summary: "により、セキュリティ アクションを<xref href=&quot;System.Security.Permissions.EnvironmentPermission&quot;></xref>宣言セキュリティを使用してコードに適用します。 このクラスは継承できません。"
  remarks: "許可されている宣言のスコープによって異なります、<xref:System.Security.Permissions.SecurityAction>ために使用される</xref:System.Security.Permissions.SecurityAction>。       セキュリティ属性によって宣言されたセキュリティ情報は、属性の対象のメタデータに格納され、実行時に、システムによってアクセスされます。 セキュリティ属性は、宣言型セキュリティにのみ使用されます。 命令型のセキュリティのアクセス許可の対応するクラスを使用します。       環境変数の名前は区別されません。 <xref:System.IO.Path.PathSeparator>。</xref:System.IO.Path.PathSeparator>を使用して名前で区切って複数の環境変数の名前を指定します。"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Assembly | System.AttributeTargets.Class | System.AttributeTargets.Struct | System.AttributeTargets.Constructor | System.AttributeTargets.Method, AllowMultiple=true, Inherited=false)]

      [System.Runtime.InteropServices.ComVisible(true)]

      public sealed class EnvironmentPermissionAttribute : System.Security.Permissions.CodeAccessSecurityAttribute
  inheritance:
  - System.Attribute
  - System.Security.Permissions.SecurityAttribute
  - System.Security.Permissions.CodeAccessSecurityAttribute
  implements: []
  inheritedMembers:
  - System.Security.Permissions.SecurityAttribute.Action
  - System.Security.Permissions.SecurityAttribute.Unrestricted
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.#ctor(System.Security.Permissions.SecurityAction)
  id: '#ctor(System.Security.Permissions.SecurityAction)'
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  langs:
  - csharp
  name: EnvironmentPermissionAttribute(SecurityAction)
  nameWithType: EnvironmentPermissionAttribute.EnvironmentPermissionAttribute(SecurityAction)
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.EnvironmentPermissionAttribute(SecurityAction)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Security.Permissions.EnvironmentPermissionAttribute&quot;> </xref> 、指定したクラス<xref href=&quot;System.Security.Permissions.SecurityAction&quot;></xref>です。"
  syntax:
    content: public EnvironmentPermissionAttribute (System.Security.Permissions.SecurityAction action);
    parameters:
    - id: action
      type: System.Security.Permissions.SecurityAction
      description: "1 つ、 <xref href=&quot;System.Security.Permissions.SecurityAction&quot;> </xref>値。"
  overload: System.Security.Permissions.EnvironmentPermissionAttribute.#ctor*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "<code> action </code>パラメーターがの有効な値ではありません<xref href=&quot;System.Security.Permissions.SecurityAction&quot;></xref>です。"
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.All
  id: All
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  langs:
  - csharp
  name: All
  nameWithType: EnvironmentPermissionAttribute.All
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.All
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "フル、文字列値で指定された環境変数へのアクセスを設定します。"
  remarks: "環境変数の名前は区別されません。 <xref:System.IO.Path.PathSeparator>。</xref:System.IO.Path.PathSeparator>を使用して名前で区切って複数の環境変数の名前を指定します。"
  syntax:
    content: public string All { get; set; }
    return:
      type: System.String
      description: "フル アクセスの環境変数の一覧。"
  overload: System.Security.Permissions.EnvironmentPermissionAttribute.All*
  exceptions:
  - type: System.NotSupportedException
    commentId: T:System.NotSupportedException
    description: "このプロパティの get メソッドがサポートされていません。"
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission
  id: CreatePermission
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  langs:
  - csharp
  name: CreatePermission()
  nameWithType: EnvironmentPermissionAttribute.CreatePermission()
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission()
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "作成して、新しい返します<xref href=&quot;System.Security.Permissions.EnvironmentPermission&quot;></xref>です。"
  remarks: "このメソッドは、アプリケーション コードからではなく、セキュリティ システムによってのみ呼び出す必要があります。       コンパイル時に、属性は、セキュリティの宣言をメタデータのシリアル化された形式に変換されます。 メタデータの宣言セキュリティ データは、この属性に対応する権限をこのメソッドが返すから作成されます。"
  syntax:
    content: public override System.Security.IPermission CreatePermission ();
    parameters: []
    return:
      type: System.Security.IPermission
      description: "<xref href=&quot;System.Security.Permissions.EnvironmentPermission&quot;> </xref>この属性に対応します。"
  overload: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission*
  exceptions: []
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Read
  id: Read
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  langs:
  - csharp
  name: Read
  nameWithType: EnvironmentPermissionAttribute.Read
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.Read
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "取得または文字列値が指定された環境変数の読み取りアクセス許可を設定します。"
  remarks: "環境変数の名前は区別されません。 <xref:System.IO.Path.PathSeparator>。</xref:System.IO.Path.PathSeparator>を使用して名前で区切って複数の環境変数の名前を指定します。"
  syntax:
    content: public string Read { get; set; }
    return:
      type: System.String
      description: "読み取りアクセス用の環境変数の一覧。"
  overload: System.Security.Permissions.EnvironmentPermissionAttribute.Read*
  exceptions: []
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Write
  id: Write
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  langs:
  - csharp
  name: Write
  nameWithType: EnvironmentPermissionAttribute.Write
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.Write
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "取得または文字列値で指定された環境変数への書き込みアクセスを設定します。"
  remarks: "環境変数の名前は区別されません。 <xref:System.IO.Path.PathSeparator>。</xref:System.IO.Path.PathSeparator>を使用して名前で区切って複数の環境変数の名前を指定します。"
  syntax:
    content: public string Write { get; set; }
    return:
      type: System.String
      description: "書き込みアクセス用の環境変数の一覧。"
  overload: System.Security.Permissions.EnvironmentPermissionAttribute.Write*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Security.Permissions.CodeAccessSecurityAttribute
  isExternal: false
  name: System.Security.Permissions.CodeAccessSecurityAttribute
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.NotSupportedException
  isExternal: true
  name: System.NotSupportedException
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.#ctor(System.Security.Permissions.SecurityAction)
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: EnvironmentPermissionAttribute(SecurityAction)
  nameWithType: EnvironmentPermissionAttribute.EnvironmentPermissionAttribute(SecurityAction)
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.EnvironmentPermissionAttribute(SecurityAction)
- uid: System.Security.Permissions.SecurityAction
  parent: System.Security.Permissions
  isExternal: false
  name: SecurityAction
  nameWithType: SecurityAction
  fullName: System.Security.Permissions.SecurityAction
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.All
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: All
  nameWithType: EnvironmentPermissionAttribute.All
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.All
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: CreatePermission()
  nameWithType: EnvironmentPermissionAttribute.CreatePermission()
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission()
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Read
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: Read
  nameWithType: EnvironmentPermissionAttribute.Read
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.Read
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Write
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: Write
  nameWithType: EnvironmentPermissionAttribute.Write
  fullName: System.Security.Permissions.EnvironmentPermissionAttribute.Write
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.#ctor*
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: EnvironmentPermissionAttribute
  nameWithType: EnvironmentPermissionAttribute.EnvironmentPermissionAttribute
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.All*
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: All
  nameWithType: EnvironmentPermissionAttribute.All
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.CreatePermission*
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: CreatePermission
  nameWithType: EnvironmentPermissionAttribute.CreatePermission
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Read*
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: Read
  nameWithType: EnvironmentPermissionAttribute.Read
- uid: System.Security.Permissions.EnvironmentPermissionAttribute.Write*
  parent: System.Security.Permissions.EnvironmentPermissionAttribute
  isExternal: false
  name: Write
  nameWithType: EnvironmentPermissionAttribute.Write
