### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DeploymentDownloadException
  id: DeploymentDownloadException
  children:
  - System.Deployment.Application.DeploymentDownloadException.#ctor
  - System.Deployment.Application.DeploymentDownloadException.#ctor(System.String)
  - System.Deployment.Application.DeploymentDownloadException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.DeploymentDownloadException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: DeploymentDownloadException
  nameWithType: DeploymentDownloadException
  fullName: System.Deployment.Application.DeploymentDownloadException
  type: Class
  summary: "いずれかのダウンロード中にエラーがあったことを示します、[!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)]マニフェストまたは配置のファイルをクライアント コンピューターにします。"
  remarks: "多くの問題が発生したとき、ユーザーがダウンロードしようとした場合、DeploymentDownloadException を示すことができます、[!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)]アプリケーションの更新プログラム:-クライアントのコンピューターのネットワーク接続がダウンしています。      -Web サーバー、FTP サーバー、または更新プログラムをホストしているファイル共有は使用できません。      -1 つ以上の内のファイル、[!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)]展開が見つかりませんでした。       例外に関する詳細なエラー情報を取得するを参照してください、[!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)]エラー ログ。 詳細については、次を参照してください。 [ClickOnce 配置のトラブルシューティング](~/add/includes/ajax-current-ext-md.md)です。"
  example:
  - "The following code example installs an application update synchronously, and reports to the user if there was a problem downloading either the manifests or the deployment's files.  \n  \n [!code-cs[ClickOnceAPI#5](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#5)]\n [!code-cpp[ClickOnceAPI#5](~/add/codesnippet/cpp/t-system.deployment.appl_2_1.cpp)]\n [!code-vb[ClickOnceAPI#5](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#5)]"
  syntax:
    content: 'public class DeploymentDownloadException : System.Deployment.Application.DeploymentException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  implements: []
  inheritedMembers:
  - System.Deployment.Application.DeploymentException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.DeploymentDownloadException
  langs:
  - csharp
  name: DeploymentDownloadException()
  nameWithType: DeploymentDownloadException.DeploymentDownloadException()
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Deployment.Application.DeploymentDownloadException&quot;> </xref>クラスです。"
  syntax:
    content: public DeploymentDownloadException ();
    parameters: []
  overload: System.Deployment.Application.DeploymentDownloadException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.DeploymentDownloadException
  langs:
  - csharp
  name: DeploymentDownloadException(String)
  nameWithType: DeploymentDownloadException.DeploymentDownloadException(String)
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Deployment.Application.DeploymentDownloadException&quot;> </xref>例外を説明するメッセージを使用します。"
  syntax:
    content: public DeploymentDownloadException (string message);
    parameters:
    - id: message
      type: System.String
      description: "例外を説明するメッセージ。 このコンス トラクターの呼び出し元は、この文字列が現在のシステムのカルチャに合わせてローカライズ済みであることを確認するために必要です。"
  overload: System.Deployment.Application.DeploymentDownloadException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.DeploymentDownloadException
  langs:
  - csharp
  name: DeploymentDownloadException(SerializationInfo,StreamingContext)
  nameWithType: DeploymentDownloadException.DeploymentDownloadException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Deployment.Application.DeploymentDownloadException&quot;> </xref>クラスです。"
  syntax:
    content: protected DeploymentDownloadException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "シリアル化されたオブジェクト データを保持するオブジェクト。"
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: "ソースまたは転送先に関する文脈情報。"
  overload: System.Deployment.Application.DeploymentDownloadException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.DeploymentDownloadException
  langs:
  - csharp
  name: DeploymentDownloadException(String,Exception)
  nameWithType: DeploymentDownloadException.DeploymentDownloadException(String,Exception)
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Deployment.Application.DeploymentDownloadException&quot;> </xref>クラスです。"
  syntax:
    content: public DeploymentDownloadException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "例外を説明するメッセージ。 このコンス トラクターの呼び出し元は、この文字列が現在のシステムのカルチャに合わせてローカライズ済みであることを確認するために必要です。"
    - id: innerException
      type: System.Exception
      description: "現在の例外の原因となった例外。 場合、`innerException`パラメーターではありません<xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>で現在の例外が発生、 <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref>ブロックは、内部例外を処理します。"
  overload: System.Deployment.Application.DeploymentDownloadException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Deployment.Application.DeploymentException
  isExternal: false
  name: System.Deployment.Application.DeploymentException
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor
  parent: System.Deployment.Application.DeploymentDownloadException
  isExternal: false
  name: DeploymentDownloadException()
  nameWithType: DeploymentDownloadException.DeploymentDownloadException()
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException()
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor(System.String)
  parent: System.Deployment.Application.DeploymentDownloadException
  isExternal: false
  name: DeploymentDownloadException(String)
  nameWithType: DeploymentDownloadException.DeploymentDownloadException(String)
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DeploymentDownloadException
  isExternal: false
  name: DeploymentDownloadException(SerializationInfo,StreamingContext)
  nameWithType: DeploymentDownloadException.DeploymentDownloadException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.DeploymentDownloadException
  isExternal: false
  name: DeploymentDownloadException(String,Exception)
  nameWithType: DeploymentDownloadException.DeploymentDownloadException(String,Exception)
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor*
  parent: System.Deployment.Application.DeploymentDownloadException
  isExternal: false
  name: DeploymentDownloadException
  nameWithType: DeploymentDownloadException.DeploymentDownloadException
