### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsGroupNameAttribute
  id: SettingsGroupNameAttribute
  children:
  - System.Configuration.SettingsGroupNameAttribute.#ctor(System.String)
  - System.Configuration.SettingsGroupNameAttribute.GroupName
  langs:
  - csharp
  name: SettingsGroupNameAttribute
  nameWithType: SettingsGroupNameAttribute
  fullName: System.Configuration.SettingsGroupNameAttribute
  type: Class
  summary: "アプリケーション設定のプロパティ グループの名前を指定します。 このクラスは継承できません。"
  remarks: "アプリケーション設定クラスから派生した<xref:System.Configuration.ApplicationSettingsBase>、同じアプリケーション設定のプロパティ グループに属している&1; つまたは複数のプロパティを定義します</xref:System.Configuration.ApplicationSettingsBase>。 既定では、グループには設定クラスの名前が割り当てられます。 ただし、SettingsGroupNameAttribute を使用して、プロパティ グループの名前を明示的に指定することができます。 この名前では、多数のサポートが必要なプログラミングのデザイン時ツールと管理ツールの実行時に、プロパティの整理に役に立つできにすることができます。 関連付けられた設定プロバイダーは、データ ストアの設定を編成するのにこの名前を使用も可能性があります。       SettingsGroupNameAttribute は、クラス レベルでのみ適用できます。"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class)]

      public sealed class SettingsGroupNameAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsGroupNameAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsGroupNameAttribute
  langs:
  - csharp
  name: SettingsGroupNameAttribute(String)
  nameWithType: SettingsGroupNameAttribute.SettingsGroupNameAttribute(String)
  fullName: System.Configuration.SettingsGroupNameAttribute.SettingsGroupNameAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Configuration.SettingsGroupNameAttribute&quot;> </xref>クラスです。"
  remarks: "理論上の最大長、`groupName`パラメーターがの上限によって制限されます、 <xref:System.Int32>、実用的な制限数、使いやすさとクォータの制限の設定プロバイダーによって決まりますが大幅に小さくなる</xref:System.Int32>。      > [!NOTE] > 設定グループ名は一意である必要はありません。"
  syntax:
    content: public SettingsGroupNameAttribute (string groupName);
    parameters:
    - id: groupName
      type: System.String
      description: "A<xref:System.String>アプリケーション設定のプロパティ グループの名前を含むします</xref:System.String>。"
  overload: System.Configuration.SettingsGroupNameAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsGroupNameAttribute.GroupName
  id: GroupName
  parent: System.Configuration.SettingsGroupNameAttribute
  langs:
  - csharp
  name: GroupName
  nameWithType: SettingsGroupNameAttribute.GroupName
  fullName: System.Configuration.SettingsGroupNameAttribute.GroupName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "アプリケーション設定のプロパティ グループの名前を取得します。"
  remarks: "GroupName プロパティ値が設定、<xref:System.Configuration.SettingsGroupNameAttribute.%23ctor%2A>コンス トラクター</xref:System.Configuration.SettingsGroupNameAttribute.%23ctor%2A> 。"
  syntax:
    content: public string GroupName { get; }
    return:
      type: System.String
      description: "A<xref:System.String>アプリケーション設定のプロパティ グループの名前を含むします</xref:System.String>。"
  overload: System.Configuration.SettingsGroupNameAttribute.GroupName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsGroupNameAttribute.#ctor(System.String)
  parent: System.Configuration.SettingsGroupNameAttribute
  isExternal: false
  name: SettingsGroupNameAttribute(String)
  nameWithType: SettingsGroupNameAttribute.SettingsGroupNameAttribute(String)
  fullName: System.Configuration.SettingsGroupNameAttribute.SettingsGroupNameAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsGroupNameAttribute.GroupName
  parent: System.Configuration.SettingsGroupNameAttribute
  isExternal: false
  name: GroupName
  nameWithType: SettingsGroupNameAttribute.GroupName
  fullName: System.Configuration.SettingsGroupNameAttribute.GroupName
- uid: System.Configuration.SettingsGroupNameAttribute.#ctor*
  parent: System.Configuration.SettingsGroupNameAttribute
  isExternal: false
  name: SettingsGroupNameAttribute
  nameWithType: SettingsGroupNameAttribute.SettingsGroupNameAttribute
- uid: System.Configuration.SettingsGroupNameAttribute.GroupName*
  parent: System.Configuration.SettingsGroupNameAttribute
  isExternal: false
  name: GroupName
  nameWithType: SettingsGroupNameAttribute.GroupName
