### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  id: X509ScopedServiceCertificateElement
  children:
  - System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.#ctor
  - System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.Copy(System.ServiceModel.Configuration.X509ScopedServiceCertificateElement)
  - System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.FindValue
  - System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.Properties
  - System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.StoreLocation
  - System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.StoreName
  - System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.TargetUri
  - System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.X509FindType
  langs:
  - csharp
  name: X509ScopedServiceCertificateElement
  nameWithType: X509ScopedServiceCertificateElement
  fullName: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  type: Class
  summary: "サービス証明書を指定する構成要素を表します。 このクラスは継承できません。"
  syntax:
    content: 'public sealed class X509ScopedServiceCertificateElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  langs:
  - csharp
  name: X509ScopedServiceCertificateElement()
  nameWithType: X509ScopedServiceCertificateElement.X509ScopedServiceCertificateElement()
  fullName: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.X509ScopedServiceCertificateElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.ServiceModel.Configuration.X509ScopedServiceCertificateElement&quot;> </xref>クラスです。"
  syntax:
    content: public X509ScopedServiceCertificateElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.Copy(System.ServiceModel.Configuration.X509ScopedServiceCertificateElement)
  id: Copy(System.ServiceModel.Configuration.X509ScopedServiceCertificateElement)
  parent: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  langs:
  - csharp
  name: Copy(X509ScopedServiceCertificateElement)
  nameWithType: X509ScopedServiceCertificateElement.Copy(X509ScopedServiceCertificateElement)
  fullName: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.Copy(X509ScopedServiceCertificateElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "この構成要素に指定された構成要素の内容をコピーします。"
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.X509ScopedServiceCertificateElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
      description: "コピーされる構成要素。"
  overload: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.Copy*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>from</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "構成ファイルは、読み取り専用です。"
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.FindValue
  id: FindValue
  parent: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  langs:
  - csharp
  name: FindValue
  nameWithType: X509ScopedServiceCertificateElement.FindValue
  fullName: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.FindValue
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得または X.509 証明書ストアで検索する値を指定する文字列を設定します。"
  remarks: "このプロパティに含まれる型は、指定した要件を満たしている必要があります<xref:System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.X509FindType%2A>値</xref:System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.X509FindType%2A>。 既定では、空の文字列です。"
  syntax:
    content: public string FindValue { get; set; }
    return:
      type: System.String
      description: "X.509 証明書ストアで検索する値。"
  overload: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.FindValue*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  langs:
  - csharp
  name: Properties
  nameWithType: X509ScopedServiceCertificateElement.Properties
  fullName: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "追加します。"
  overload: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.StoreLocation
  id: StoreLocation
  parent: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  langs:
  - csharp
  name: StoreLocation
  nameWithType: X509ScopedServiceCertificateElement.StoreLocation
  fullName: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.StoreLocation
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得またはサーバーの証明書の検証に使用できる、クライアント証明書ストアの位置を指定する値を設定します。"
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreLocation StoreLocation { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreLocation
      description: "A <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreLocation&quot;></xref>. 既定値は<xref href=&quot;System.Security.Cryptography.X509Certificates.StoreLocation&quot;></xref>です。"
  overload: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.StoreLocation*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.StoreName
  id: StoreName
  parent: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  langs:
  - csharp
  name: StoreName
  nameWithType: X509ScopedServiceCertificateElement.StoreName
  fullName: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.StoreName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得または設定を開くには、X.509 証明書ストアの名前。"
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreName StoreName { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreName
      description: "A <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreName&quot;> </xref>を開くには、X.509 証明書ストアの名前を格納しています。"
  overload: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.StoreName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.TargetUri
  id: TargetUri
  parent: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  langs:
  - csharp
  name: TargetUri
  nameWithType: X509ScopedServiceCertificateElement.TargetUri
  fullName: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.TargetUri
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得またはこの証明書の URI を設定します。"
  syntax:
    content: public Uri TargetUri { get; set; }
    return:
      type: System.Uri
      description: "URI。"
  overload: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.TargetUri*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.X509FindType
  id: X509FindType
  parent: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  langs:
  - csharp
  name: X509FindType
  nameWithType: X509ScopedServiceCertificateElement.X509FindType
  fullName: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.X509FindType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得またはを実行する X.509 検索の種類を設定します。"
  remarks: "含まれる型<xref:System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.FindValue%2A>このプロパティの要件を満たす必要があります</xref:System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.FindValue%2A>。"
  syntax:
    content: public System.Security.Cryptography.X509Certificates.X509FindType X509FindType { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.X509FindType
      description: "A <xref href=&quot;System.Security.Cryptography.X509Certificates.X509FindType&quot;> </xref>を実行する X.509 検索の種類を指定します。"
  overload: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.X509FindType*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.#ctor
  parent: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  isExternal: false
  name: X509ScopedServiceCertificateElement()
  nameWithType: X509ScopedServiceCertificateElement.X509ScopedServiceCertificateElement()
  fullName: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.X509ScopedServiceCertificateElement()
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.Copy(System.ServiceModel.Configuration.X509ScopedServiceCertificateElement)
  parent: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  isExternal: false
  name: Copy(X509ScopedServiceCertificateElement)
  nameWithType: X509ScopedServiceCertificateElement.Copy(X509ScopedServiceCertificateElement)
  fullName: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.Copy(X509ScopedServiceCertificateElement)
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: X509ScopedServiceCertificateElement
  nameWithType: X509ScopedServiceCertificateElement
  fullName: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.FindValue
  parent: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  isExternal: false
  name: FindValue
  nameWithType: X509ScopedServiceCertificateElement.FindValue
  fullName: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.FindValue
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.Properties
  parent: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  isExternal: false
  name: Properties
  nameWithType: X509ScopedServiceCertificateElement.Properties
  fullName: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.StoreLocation
  parent: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  isExternal: false
  name: StoreLocation
  nameWithType: X509ScopedServiceCertificateElement.StoreLocation
  fullName: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.StoreLocation
- uid: System.Security.Cryptography.X509Certificates.StoreLocation
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreLocation
  nameWithType: StoreLocation
  fullName: System.Security.Cryptography.X509Certificates.StoreLocation
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.StoreName
  parent: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  isExternal: false
  name: StoreName
  nameWithType: X509ScopedServiceCertificateElement.StoreName
  fullName: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.StoreName
- uid: System.Security.Cryptography.X509Certificates.StoreName
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreName
  nameWithType: StoreName
  fullName: System.Security.Cryptography.X509Certificates.StoreName
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.TargetUri
  parent: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  isExternal: false
  name: TargetUri
  nameWithType: X509ScopedServiceCertificateElement.TargetUri
  fullName: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.TargetUri
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.X509FindType
  parent: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  isExternal: false
  name: X509FindType
  nameWithType: X509ScopedServiceCertificateElement.X509FindType
  fullName: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.X509FindType
- uid: System.Security.Cryptography.X509Certificates.X509FindType
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: X509FindType
  nameWithType: X509FindType
  fullName: System.Security.Cryptography.X509Certificates.X509FindType
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.#ctor*
  parent: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  isExternal: false
  name: X509ScopedServiceCertificateElement
  nameWithType: X509ScopedServiceCertificateElement.X509ScopedServiceCertificateElement
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.Copy*
  parent: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  isExternal: false
  name: Copy
  nameWithType: X509ScopedServiceCertificateElement.Copy
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.FindValue*
  parent: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  isExternal: false
  name: FindValue
  nameWithType: X509ScopedServiceCertificateElement.FindValue
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.Properties*
  parent: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  isExternal: false
  name: Properties
  nameWithType: X509ScopedServiceCertificateElement.Properties
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.StoreLocation*
  parent: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  isExternal: false
  name: StoreLocation
  nameWithType: X509ScopedServiceCertificateElement.StoreLocation
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.StoreName*
  parent: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  isExternal: false
  name: StoreName
  nameWithType: X509ScopedServiceCertificateElement.StoreName
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.TargetUri*
  parent: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  isExternal: false
  name: TargetUri
  nameWithType: X509ScopedServiceCertificateElement.TargetUri
- uid: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement.X509FindType*
  parent: System.ServiceModel.Configuration.X509ScopedServiceCertificateElement
  isExternal: false
  name: X509FindType
  nameWithType: X509ScopedServiceCertificateElement.X509FindType
