### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  id: ICustomIdentityConfiguration
  children:
  - System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(System.Xml.XmlNodeList)
  langs:
  - csharp
  name: ICustomIdentityConfiguration
  nameWithType: ICustomIdentityConfiguration
  fullName: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  type: Interface
  summary: "カスタム構成をロードするクラスを有効にするメソッドを定義します。"
  remarks: "ICustomIdentityConfiguration インターフェイスを実装するクラスは、XML からカスタム構成を読み込むことができます。       Windows Identity Foundation (WIF) クラスのいくつかは、構成ファイルからの派生クラスのカスタム構成を定義するための機能を提供する ICustomIdentityConfiguration インターフェイスを実装します。 WIF クラスの多くは、それらが表すオブジェクトの既定の構成を提供するには、このメソッドの基本実装を提供します。"
  syntax:
    content: public interface ICustomIdentityConfiguration
  implements: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(System.Xml.XmlNodeList)
  id: LoadCustomConfiguration(System.Xml.XmlNodeList)
  parent: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  langs:
  - csharp
  name: LoadCustomConfiguration(XmlNodeList)
  nameWithType: ICustomIdentityConfiguration.LoadCustomConfiguration(XmlNodeList)
  fullName: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(XmlNodeList)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "XML からカスタム構成を読み込みます。 構成要素のカスタム処理を指定するには、このメソッドをオーバーライドします。"
  remarks: "LoadCustomConfiguration メソッドは、構成のインフラストラクチャによって呼び出されます。 このメソッドが呼び出されたときに、`nodelist`パラメーターには、構成ファイルからオブジェクトのクラスを構成する親要素の最上位レベルの子要素が含まれています。 派生したクラスなど、<xref:System.IdentityModel.Tokens.IssuerNameRegistry>の子要素を持つ、 [ \\&lt; issuerNameRegistry\\&gt;](../Topic/%3CissuerNameRegistry%3E.md)要素が渡された、`nodelist`パラメーター</xref:System.IdentityModel.Tokens.IssuerNameRegistry> 。 `nodelist`は完全で構成<xref:System.Xml.XmlElement>オブジェクト</xref:System.Xml.XmlElement>。 これらの各属性と、スキーマに応じて、構成が構成されているクラスに対して定義されている子要素があります。"
  syntax:
    content: public void LoadCustomConfiguration (System.Xml.XmlNodeList nodeList);
    parameters:
    - id: nodeList
      type: System.Xml.XmlNodeList
      description: "カスタム構成を含む XML ノードです。 型のリスト内の各ノードは、 <xref href=&quot;System.Xml.XmlElement&quot;></xref>です。"
  overload: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration*
  exceptions: []
  platform:
  - net462
references:
- uid: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(System.Xml.XmlNodeList)
  parent: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  isExternal: false
  name: LoadCustomConfiguration(XmlNodeList)
  nameWithType: ICustomIdentityConfiguration.LoadCustomConfiguration(XmlNodeList)
  fullName: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(XmlNodeList)
- uid: System.Xml.XmlNodeList
  parent: System.Xml
  isExternal: false
  name: XmlNodeList
  nameWithType: XmlNodeList
  fullName: System.Xml.XmlNodeList
- uid: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration*
  parent: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  isExternal: false
  name: LoadCustomConfiguration
  nameWithType: ICustomIdentityConfiguration.LoadCustomConfiguration
