### YamlMime:ManagedReference
items:
- uid: System.Configuration.ContextInformation
  id: ContextInformation
  children:
  - System.Configuration.ContextInformation.GetSection(System.String)
  - System.Configuration.ContextInformation.HostingContext
  - System.Configuration.ContextInformation.IsMachineLevel
  langs:
  - csharp
  name: ContextInformation
  nameWithType: ContextInformation
  fullName: System.Configuration.ContextInformation
  type: Class
  summary: "関連付けられているコンテキスト情報をカプセル化、 <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref>オブジェクト。 このクラスは継承できません。"
  remarks: "ContextInformation オブジェクトでは、構成の要素に関連する環境の詳細を提供します。 たとえば、使用することができます、<xref:System.Configuration.ContextInformation.IsMachineLevel%2A>プロパティを決定するかどうか、 <xref:System.Configuration.ConfigurationElement>Machine.config で設定されたか、どの階層を指定できます、<xref:System.Configuration.ConfigurationElement>を使用してに属している、<xref:System.Configuration.ContextInformation.HostingContext%2A>プロパティ</xref:System.Configuration.ContextInformation.HostingContext%2A></xref:System.Configuration.ConfigurationElement></xref:System.Configuration.ConfigurationElement></xref:System.Configuration.ContextInformation.IsMachineLevel%2A>。"
  example:
  - "The following code example demonstrates how to use the ContextInformation type.  \n  \n [!code-vb[System.Configuration.ContextInformation#1](~/add/codesnippet/visualbasic/t-system.configuration.c_0_1.vb)]\n [!code-cs[System.Configuration.ContextInformation#1](~/add/codesnippet/csharp/t-system.configuration.c_0_1.cs)]"
  syntax:
    content: public sealed class ContextInformation
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ContextInformation.GetSection(System.String)
  id: GetSection(System.String)
  parent: System.Configuration.ContextInformation
  langs:
  - csharp
  name: GetSection(String)
  nameWithType: ContextInformation.GetSection(String)
  fullName: System.Configuration.ContextInformation.GetSection(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "指定したセクション名に基づいて構成セクションの情報を含むオブジェクトを提供します。"
  remarks: "構成内のセクションを指定する場合は、構成セクションの名前は大文字小文字を区別する注意してください。"
  syntax:
    content: public object GetSection (string sectionName);
    parameters:
    - id: sectionName
      type: System.String
      description: "構成セクションの名前。"
    return:
      type: System.Object
      description: "構成内で指定されたセクションを格納するオブジェクト。"
  overload: System.Configuration.ContextInformation.GetSection*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ContextInformation.HostingContext
  id: HostingContext
  parent: System.Configuration.ContextInformation
  langs:
  - csharp
  name: HostingContext
  nameWithType: ContextInformation.HostingContext
  fullName: System.Configuration.ContextInformation.HostingContext
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "構成プロパティが評価されている環境のコンテキストを取得します。"
  remarks: "考えられる HostingContext 値は<xref:System.Web.Configuration.WebContext>、 <xref:System.Configuration.ExeContext>、または`null`</xref:System.Configuration.ExeContext></xref:System.Web.Configuration.WebContext>。"
  example:
  - "The following code example demonstrates how to use the HostingContext property.  \n  \n [!code-vb[System.Configuration.ContextInformation#3](~/add/codesnippet/visualbasic/p-system.configuration.c_46_1.vb)]\n [!code-cs[System.Configuration.ContextInformation#3](~/add/codesnippet/csharp/p-system.configuration.c_46_1.cs)]"
  syntax:
    content: public object HostingContext { get; }
    return:
      type: System.Object
      description: "構成プロパティが評価されている環境を指定するオブジェクト。"
  overload: System.Configuration.ContextInformation.HostingContext*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ContextInformation.IsMachineLevel
  id: IsMachineLevel
  parent: System.Configuration.ContextInformation
  langs:
  - csharp
  name: IsMachineLevel
  nameWithType: ContextInformation.IsMachineLevel
  fullName: System.Configuration.ContextInformation.IsMachineLevel
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "構成プロパティが、コンピューターの構成レベルで評価されるかどうかを指定する値を取得します。"
  remarks: "IsMachineLevel の返された値が`false`を使用して、<xref:System.Configuration.ContextInformation.HostingContext%2A>構成階層内のレベルを決定するプロパティ</xref:System.Configuration.ContextInformation.HostingContext%2A>。"
  example:
  - "The following code example demonstrates how to use the <xref:System.Configuration.ContextInformation.HostingContext%2A> property.  \n  \n [!code-vb[System.Configuration.ContextInformation#2](~/add/codesnippet/visualbasic/p-system.configuration.c_7_1.vb)]\n [!code-cs[System.Configuration.ContextInformation#2](~/add/codesnippet/csharp/p-system.configuration.c_7_1.cs)]"
  syntax:
    content: public bool IsMachineLevel { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>コンピューターの構成レベルで構成プロパティが評価されている場合それ以外の場合、 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>です。"
  overload: System.Configuration.ContextInformation.IsMachineLevel*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ContextInformation.GetSection(System.String)
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: GetSection(String)
  nameWithType: ContextInformation.GetSection(String)
  fullName: System.Configuration.ContextInformation.GetSection(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ContextInformation.HostingContext
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: HostingContext
  nameWithType: ContextInformation.HostingContext
  fullName: System.Configuration.ContextInformation.HostingContext
- uid: System.Configuration.ContextInformation.IsMachineLevel
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: IsMachineLevel
  nameWithType: ContextInformation.IsMachineLevel
  fullName: System.Configuration.ContextInformation.IsMachineLevel
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.ContextInformation.GetSection*
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: GetSection
  nameWithType: ContextInformation.GetSection
- uid: System.Configuration.ContextInformation.HostingContext*
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: HostingContext
  nameWithType: ContextInformation.HostingContext
- uid: System.Configuration.ContextInformation.IsMachineLevel*
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: IsMachineLevel
  nameWithType: ContextInformation.IsMachineLevel
