### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler
  id: HttpCapabilitiesSectionHandler
  children:
  - System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor
  - System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: HttpCapabilitiesSectionHandler
  nameWithType: HttpCapabilitiesSectionHandler
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler
  type: Class
  summary: "読み取り中に支援、 <xref uid=&quot;langword_csharp_&lt;browserCaps&gt;&quot; name=&quot;&lt;browserCaps&gt;&quot; href=&quot;&quot;> </xref>のセクションの構成ファイルとのインスタンスを作成する、 <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref>クライアント ブラウザーの機能の情報を含むクラスです。"
  remarks: "HttpCapabilitiesSectionHandler クラスと、対応する`<browserCaps>`は .NET Framework version 2.0 で廃止された構成セクション。 ブラウザーの機能を管理するための推奨される方法は、<xref:System.Web.Configuration.BrowserCapabilitiesFactory>クラス</xref:System.Web.Configuration.BrowserCapabilitiesFactory>で使用するため、コンパイルのブラウザー定義ファイルを使用 両方の構成方法の目標は、<xref:System.Web.HttpBrowserCapabilities><xref:System.Web.HttpRequest.Browser%2A><xref:System.Web.HttpRequest>クラス</xref:System.Web.HttpRequest>のプロパティ</xref:System.Web.HttpRequest.Browser%2A>からアクセスできるクラス</xref:System.Web.HttpBrowserCapabilities>のインスタンスを生成するには       ブラウザー定義ファイルを使用して、ブラウザーの機能を格納する恩恵を代わりにします。 ブラウザーの定義については、XML 構成ファイルから解析され、事前のクラスにコンパイルするため、パフォーマンスの向上を提供します。 ブラウザー定義ファイルは簡単に管理: の定義が階層形式であり、したがってブラウザーの機能を決定する小さいに正規表現を使用します。      -定義は、管理しやすいように、複数のファイルに編成できます。      -定義は、Machine.config レベルまたは特定のアプリケーション レベルで、任意のレベルで定義できます。 これにより、特定のブラウザーの機能をオーバーライドするために定義のセット全体をコピーする必要があります。"
  syntax:
    content: 'public class HttpCapabilitiesSectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  langs:
  - csharp
  name: HttpCapabilitiesSectionHandler()
  nameWithType: HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Web.Configuration.HttpCapabilitiesSectionHandler&quot;> </xref>クラスです。"
  syntax:
    content: public HttpCapabilitiesSectionHandler ();
    parameters: []
  overload: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "インスタンスを作成、 <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref>クライアント ブラウザーの機能の情報を含むクラスです。"
  remarks: "このクラスの派生、ブラウザーの定義のデータを`<browserCaps>`構成セクション。 .NET Framework version 2.0 では、このセクションでは推奨されていません。"
  syntax:
    content: public object Create (object parent, object configurationContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "親構成ノードです。"
    - id: configurationContext
      type: System.Object
      description: "現在の構成ファイルの構成のコンテキスト。"
    - id: section
      type: System.Xml.XmlNode
      description: "情報を含む構成ファイルのセクションです。"
    return:
      type: System.Object
      description: "インスタンス<xref href=&quot;System.Web.HttpBrowserCapabilities&quot;></xref>クライアント ブラウザーの機能の情報を格納します。"
  overload: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: HttpCapabilitiesSectionHandler()
  nameWithType: HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor*
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: HttpCapabilitiesSectionHandler
  nameWithType: HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create*
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: Create
  nameWithType: HttpCapabilitiesSectionHandler.Create
