### YamlMime:ManagedReference
items:
- uid: System.Security.Permissions.EnvironmentPermissionAccess
  id: EnvironmentPermissionAccess
  children:
  - System.Security.Permissions.EnvironmentPermissionAccess.AllAccess
  - System.Security.Permissions.EnvironmentPermissionAccess.NoAccess
  - System.Security.Permissions.EnvironmentPermissionAccess.Read
  - System.Security.Permissions.EnvironmentPermissionAccess.Write
  langs:
  - csharp
  name: EnvironmentPermissionAccess
  nameWithType: EnvironmentPermissionAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess
  type: Enum
  summary: "環境変数へのアクセスを指定します。"
  remarks: "<xref:System.Security.Permissions.EnvironmentPermission>。</xref:System.Security.Permissions.EnvironmentPermission>でこの列挙を使用します。      > [!NOTE] > が NoAccess AllAccess に、表示 EnvironmentPermissionAccess、無効のパラメーターとして使用する<xref:System.Security.Permissions.EnvironmentPermission.GetPathList%2A>説明しているのでない環境変数へのアクセスの種類またはすべての環境変数へのアクセスの種類、それぞれ、および<xref:System.Security.Permissions.EnvironmentPermission.GetPathList%2A>は&1; つの環境変数アクセスの種類が必要です</xref:System.Security.Permissions.EnvironmentPermission.GetPathList%2A></xref:System.Security.Permissions.EnvironmentPermission.GetPathList%2A>。"
  syntax:
    content: >-
      [System.Flags]

      [System.Runtime.InteropServices.ComVisible(true)]

      public enum EnvironmentPermissionAccess
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAccess.AllAccess
  id: AllAccess
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  langs:
  - csharp
  name: AllAccess
  nameWithType: EnvironmentPermissionAccess.AllAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.AllAccess
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "環境変数へのアクセスを読み書きします。 AllAccess が EnvironmentPermissionAccess の複数の値を表し、原因、<xref:System.ArgumentException>として使用する場合、 <code> flag </code>のパラメーター、<xref:System.Security.Permissions.EnvironmentPermission.GetPathList*>メソッドで、1 つの値が必要です</xref:System.Security.Permissions.EnvironmentPermission.GetPathList*></xref:System.ArgumentException>。"
  syntax:
    content: AllAccess
    return:
      type: System.Security.Permissions.EnvironmentPermissionAccess
      description: "追加します。"
  exceptions: []
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAccess.NoAccess
  id: NoAccess
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  langs:
  - csharp
  name: NoAccess
  nameWithType: EnvironmentPermissionAccess.NoAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.NoAccess
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "環境変数にアクセスできません。 NoAccess EnvironmentPermissionAccess の有効な値を表すありませんし、<xref:System.ArgumentException>のパラメーターとして使用すると<xref:System.Security.Permissions.EnvironmentPermission.GetPathList*>、1 つの値を受け取る</xref:System.Security.Permissions.EnvironmentPermission.GetPathList*></xref:System.ArgumentException>。"
  syntax:
    content: NoAccess
    return:
      type: System.Security.Permissions.EnvironmentPermissionAccess
      description: "追加します。"
  exceptions: []
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAccess.Read
  id: Read
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  langs:
  - csharp
  name: Read
  nameWithType: EnvironmentPermissionAccess.Read
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.Read
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "環境変数への読み取りアクセスのみを指定します。 変更、削除、および環境変数の作成は、このアクセス レベルには含まれません。"
  syntax:
    content: Read
    return:
      type: System.Security.Permissions.EnvironmentPermissionAccess
      description: "追加します。"
  exceptions: []
  platform:
  - net462
- uid: System.Security.Permissions.EnvironmentPermissionAccess.Write
  id: Write
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  langs:
  - csharp
  name: Write
  nameWithType: EnvironmentPermissionAccess.Write
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.Write
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  summary: "環境変数への書き込みアクセスのみを指定します。 書き込みアクセスには、作成し、環境変数を削除するだけでなく既存の値を変更するが含まれています。 このアクセス レベルでは、環境変数の読み取りは含まれません。"
  syntax:
    content: Write
    return:
      type: System.Security.Permissions.EnvironmentPermissionAccess
      description: "追加します。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Security.Permissions.EnvironmentPermissionAccess.AllAccess
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  isExternal: false
  name: AllAccess
  nameWithType: EnvironmentPermissionAccess.AllAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.AllAccess
- uid: System.Security.Permissions.EnvironmentPermissionAccess
  parent: System.Security.Permissions
  isExternal: false
  name: EnvironmentPermissionAccess
  nameWithType: EnvironmentPermissionAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess
- uid: System.Security.Permissions.EnvironmentPermissionAccess.NoAccess
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  isExternal: false
  name: NoAccess
  nameWithType: EnvironmentPermissionAccess.NoAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.NoAccess
- uid: System.Security.Permissions.EnvironmentPermissionAccess.Read
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  isExternal: false
  name: Read
  nameWithType: EnvironmentPermissionAccess.Read
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.Read
- uid: System.Security.Permissions.EnvironmentPermissionAccess.Write
  parent: System.Security.Permissions.EnvironmentPermissionAccess
  isExternal: false
  name: Write
  nameWithType: EnvironmentPermissionAccess.Write
  fullName: System.Security.Permissions.EnvironmentPermissionAccess.Write
