### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ComUdtElement
  id: ComUdtElement
  children:
  - System.ServiceModel.Configuration.ComUdtElement.#ctor
  - System.ServiceModel.Configuration.ComUdtElement.#ctor(System.String)
  - System.ServiceModel.Configuration.ComUdtElement.Name
  - System.ServiceModel.Configuration.ComUdtElement.Properties
  - System.ServiceModel.Configuration.ComUdtElement.TypeDefID
  - System.ServiceModel.Configuration.ComUdtElement.TypeLibID
  - System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion
  langs:
  - csharp
  name: ComUdtElement
  nameWithType: ComUdtElement
  fullName: System.ServiceModel.Configuration.ComUdtElement
  type: Class
  summary: "ユーザー定義型 (UDT)、サービス コントラクトに含まれることを表します。 このクラスは継承できません。"
  remarks: "COM + 統合ランタイムは、タイプ ライブラリを調べることによってサービスを作成します。 COM + コンポーネントに渡すメソッドが含まれている場合、 `VARIANT`、システムが実行前に渡される実際の型を判断することはできません。 したがって、しようとすると、ユーザー定義型 (UDT) 内に渡す、 `VARIANT`、シリアル化のための既知の型ではないので失敗します。       この問題を回避するために適切なサービス コントラクトで既知の型として含まれている可能性があるように、構成ファイルに、Udt を追加することができます。 このためには、UDT とそれを使用する元の COM インターフェイスは、コントラクト、一意に識別する必要があります。       次の例では、2 つの特定の Udt を追加することを示しています、 `userDefinedTypes`> この目的のため構成ファイルのセクションです。       [!code-cs[XpsCreate #XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent) ]の属性、 `userDefinedType`> 要素は次のように定義されている:- `typeName`: 判読可能な型名を提供する省略可能な属性です。 これにより、ランタイムでは使用されませんが、型を判別するためのリーダーに役立ちます。      - `typeLibID`: 型を定義する登録されているタイプ ライブラリを指定する GUID 文字列です。      - `typeLibVersion`: 型を定義するタイプ ライブラリのバージョンを指定する文字列。      - `typeDefID`: 登録されているタイプ ライブラリ内の特定の UDT 型を指定する GUID 文字列です。       サービスが初期化されたときに、COM + 統合ランタイムは、指定された型を検索し、指定されたコントラクトの既知の型のコレクションに追加。"
  example:
  - "The following example demonstrates adding two specific UDTs to the <`userDefinedTypes`> section of the configuration file for this purpose.  \n  \n [!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]"
  syntax:
    content: 'public sealed class ComUdtElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: ComUdtElement()
  nameWithType: ComUdtElement.ComUdtElement()
  fullName: System.ServiceModel.Configuration.ComUdtElement.ComUdtElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.ServiceModel.Configuration.ComUdtElement&quot;> </xref>クラスです。"
  syntax:
    content: public ComUdtElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ComUdtElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: ComUdtElement(String)
  nameWithType: ComUdtElement.ComUdtElement(String)
  fullName: System.ServiceModel.Configuration.ComUdtElement.ComUdtElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.ServiceModel.Configuration.ComUdtElement&quot;> </xref>クラス GUID 文字列を指定します。"
  syntax:
    content: public ComUdtElement (string typeDefID);
    parameters:
    - id: typeDefID
      type: System.String
      description: "登録済みタイプ ライブラリ内の特定の UDT 型を識別する GUID 文字列です。"
  overload: System.ServiceModel.Configuration.ComUdtElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.Name
  id: Name
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: Name
  nameWithType: ComUdtElement.Name
  fullName: System.ServiceModel.Configuration.ComUdtElement.Name
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得または読み取り可能な型名を設定します。"
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "読み取り可能な型名。"
  overload: System.ServiceModel.Configuration.ComUdtElement.Name*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: Properties
  nameWithType: ComUdtElement.Properties
  fullName: System.ServiceModel.Configuration.ComUdtElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "追加します。"
  overload: System.ServiceModel.Configuration.ComUdtElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeDefID
  id: TypeDefID
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: TypeDefID
  nameWithType: ComUdtElement.TypeDefID
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeDefID
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得または登録されているタイプ ライブラリ内の特定の UDT 型を識別する GUID 文字列を設定します。"
  syntax:
    content: public string TypeDefID { get; set; }
    return:
      type: System.String
      description: "登録済みタイプ ライブラリ内の特定の UDT 型。"
  overload: System.ServiceModel.Configuration.ComUdtElement.TypeDefID*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibID
  id: TypeLibID
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: TypeLibID
  nameWithType: ComUdtElement.TypeLibID
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeLibID
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得または型を定義する登録済みタイプ ライブラリを識別する GUID 文字列を設定します。"
  syntax:
    content: public string TypeLibID { get; set; }
    return:
      type: System.String
      description: "型を定義する登録済みタイプ ライブラリ。"
  overload: System.ServiceModel.Configuration.ComUdtElement.TypeLibID*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion
  id: TypeLibVersion
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: TypeLibVersion
  nameWithType: ComUdtElement.TypeLibVersion
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得または型を定義するタイプ ライブラリのバージョンを識別する文字列を設定します。"
  syntax:
    content: public string TypeLibVersion { get; set; }
    return:
      type: System.String
      description: "型を定義するタイプ ライブラリのバージョン。"
  overload: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ComUdtElement.#ctor
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: ComUdtElement()
  nameWithType: ComUdtElement.ComUdtElement()
  fullName: System.ServiceModel.Configuration.ComUdtElement.ComUdtElement()
- uid: System.ServiceModel.Configuration.ComUdtElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: ComUdtElement(String)
  nameWithType: ComUdtElement.ComUdtElement(String)
  fullName: System.ServiceModel.Configuration.ComUdtElement.ComUdtElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.ComUdtElement.Name
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: Name
  nameWithType: ComUdtElement.Name
  fullName: System.ServiceModel.Configuration.ComUdtElement.Name
- uid: System.ServiceModel.Configuration.ComUdtElement.Properties
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: Properties
  nameWithType: ComUdtElement.Properties
  fullName: System.ServiceModel.Configuration.ComUdtElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeDefID
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeDefID
  nameWithType: ComUdtElement.TypeDefID
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeDefID
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibID
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeLibID
  nameWithType: ComUdtElement.TypeLibID
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeLibID
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeLibVersion
  nameWithType: ComUdtElement.TypeLibVersion
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion
- uid: System.ServiceModel.Configuration.ComUdtElement.#ctor*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: ComUdtElement
  nameWithType: ComUdtElement.ComUdtElement
- uid: System.ServiceModel.Configuration.ComUdtElement.Name*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: Name
  nameWithType: ComUdtElement.Name
- uid: System.ServiceModel.Configuration.ComUdtElement.Properties*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: Properties
  nameWithType: ComUdtElement.Properties
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeDefID*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeDefID
  nameWithType: ComUdtElement.TypeDefID
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibID*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeLibID
  nameWithType: ComUdtElement.TypeLibID
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeLibVersion
  nameWithType: ComUdtElement.TypeLibVersion
