### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IInternalConfigRoot
  id: IInternalConfigRoot
  children:
  - System.Configuration.Internal.IInternalConfigRoot.ConfigChanged
  - System.Configuration.Internal.IInternalConfigRoot.ConfigRemoved
  - System.Configuration.Internal.IInternalConfigRoot.GetConfigRecord(System.String)
  - System.Configuration.Internal.IInternalConfigRoot.GetSection(System.String,System.String)
  - System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigPath(System.String)
  - System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigRecord(System.String)
  - System.Configuration.Internal.IInternalConfigRoot.Init(System.Configuration.Internal.IInternalConfigHost,System.Boolean)
  - System.Configuration.Internal.IInternalConfigRoot.IsDesignTime
  - System.Configuration.Internal.IInternalConfigRoot.RemoveConfig(System.String)
  langs:
  - csharp
  name: IInternalConfigRoot
  nameWithType: IInternalConfigRoot
  fullName: System.Configuration.Internal.IInternalConfigRoot
  type: Interface
  summary: "構成のルート オブジェクトをサポートするために、.NET 構造体の内部で使用されるインターフェイスを定義します。"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IInternalConfigRoot
  implements: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRoot.ConfigChanged
  id: ConfigChanged
  parent: System.Configuration.Internal.IInternalConfigRoot
  langs:
  - csharp
  name: ConfigChanged
  nameWithType: IInternalConfigRoot.ConfigChanged
  fullName: System.Configuration.Internal.IInternalConfigRoot.ConfigChanged
  type: Event
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "ConfigChanged イベントを処理するメソッドを表す、 <xref href=&quot;System.Configuration.Internal.IInternalConfigRoot&quot;> </xref>オブジェクト。"
  syntax:
    content: public event System.Configuration.Internal.InternalConfigEventHandler ConfigChanged;
    return:
      type: System.Configuration.Internal.InternalConfigEventHandler
      description: "追加します。"
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRoot.ConfigRemoved
  id: ConfigRemoved
  parent: System.Configuration.Internal.IInternalConfigRoot
  langs:
  - csharp
  name: ConfigRemoved
  nameWithType: IInternalConfigRoot.ConfigRemoved
  fullName: System.Configuration.Internal.IInternalConfigRoot.ConfigRemoved
  type: Event
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "ConfigRemoved イベントを処理するメソッドを表す、 <xref href=&quot;System.Configuration.Internal.IInternalConfigRoot&quot;> </xref>オブジェクト。"
  syntax:
    content: public event System.Configuration.Internal.InternalConfigEventHandler ConfigRemoved;
    return:
      type: System.Configuration.Internal.InternalConfigEventHandler
      description: "追加します。"
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRoot.GetConfigRecord(System.String)
  id: GetConfigRecord(System.String)
  parent: System.Configuration.Internal.IInternalConfigRoot
  langs:
  - csharp
  name: GetConfigRecord(String)
  nameWithType: IInternalConfigRoot.GetConfigRecord(String)
  fullName: System.Configuration.Internal.IInternalConfigRoot.GetConfigRecord(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "返します、 <xref href=&quot;System.Configuration.Internal.IInternalConfigRecord&quot;> </xref>構成パスで指定された構成を表すオブジェクト。"
  syntax:
    content: public System.Configuration.Internal.IInternalConfigRecord GetConfigRecord (string configPath);
    parameters:
    - id: configPath
      type: System.String
      description: "構成ファイルへのパスを表す文字列。"
    return:
      type: System.Configuration.Internal.IInternalConfigRecord
      description: "<xref href=&quot;System.Configuration.Internal.IInternalConfigRecord&quot;> </xref>で指定された構成を表すオブジェクト<code> configPath</code>です。"
  overload: System.Configuration.Internal.IInternalConfigRoot.GetConfigRecord*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRoot.GetSection(System.String,System.String)
  id: GetSection(System.String,System.String)
  parent: System.Configuration.Internal.IInternalConfigRoot
  langs:
  - csharp
  name: GetSection(String,String)
  nameWithType: IInternalConfigRoot.GetSection(String,String)
  fullName: System.Configuration.Internal.IInternalConfigRoot.GetSection(String,String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "返します、<xref:System.Object>構成ファイルのセクションのデータを表すします</xref:System.Object>。"
  syntax:
    content: public object GetSection (string section, string configPath);
    parameters:
    - id: section
      type: System.String
      description: "構成ファイルのセクションを表す文字列。"
    - id: configPath
      type: System.String
      description: "構成ファイルへのパスを表す文字列。"
    return:
      type: System.Object
      description: "<xref:System.Object>構成ファイルのセクションのデータを表すします</xref:System.Object>。"
  overload: System.Configuration.Internal.IInternalConfigRoot.GetSection*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigPath(System.String)
  id: GetUniqueConfigPath(System.String)
  parent: System.Configuration.Internal.IInternalConfigRoot
  langs:
  - csharp
  name: GetUniqueConfigPath(String)
  nameWithType: IInternalConfigRoot.GetUniqueConfigPath(String)
  fullName: System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigPath(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "構成データを持つ構成の最も近い先祖のファイル パスを表す値を返します。"
  syntax:
    content: public string GetUniqueConfigPath (string configPath);
    parameters:
    - id: configPath
      type: System.String
      description: "構成ファイルのパス。"
    return:
      type: System.String
      description: "構成データを持つ構成の最も近い先祖のファイル パスを表す文字列を返します。"
  overload: System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigPath*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigRecord(System.String)
  id: GetUniqueConfigRecord(System.String)
  parent: System.Configuration.Internal.IInternalConfigRoot
  langs:
  - csharp
  name: GetUniqueConfigRecord(String)
  nameWithType: IInternalConfigRoot.GetUniqueConfigRecord(String)
  fullName: System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigRecord(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "返します、 <xref href=&quot;System.Configuration.Internal.IInternalConfigRecord&quot;> </xref>指定された一意の構成のレコードを表すオブジェクトを構成パス。"
  syntax:
    content: public System.Configuration.Internal.IInternalConfigRecord GetUniqueConfigRecord (string configPath);
    parameters:
    - id: configPath
      type: System.String
      description: "構成ファイルのパス。"
    return:
      type: System.Configuration.Internal.IInternalConfigRecord
      description: "<xref href=&quot;System.Configuration.Internal.IInternalConfigRecord&quot;> </xref>指定の構成パスの一意の構成のレコードを表すオブジェクト。"
  overload: System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigRecord*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRoot.Init(System.Configuration.Internal.IInternalConfigHost,System.Boolean)
  id: Init(System.Configuration.Internal.IInternalConfigHost,System.Boolean)
  parent: System.Configuration.Internal.IInternalConfigRoot
  langs:
  - csharp
  name: Init(IInternalConfigHost,Boolean)
  nameWithType: IInternalConfigRoot.Init(IInternalConfigHost,Boolean)
  fullName: System.Configuration.Internal.IInternalConfigRoot.Init(IInternalConfigHost,Boolean)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "構成オブジェクトを初期化します。"
  syntax:
    content: public void Init (System.Configuration.Internal.IInternalConfigHost host, bool isDesignTime);
    parameters:
    - id: host
      type: System.Configuration.Internal.IInternalConfigHost
      description: "<xref href=&quot;System.Configuration.Internal.IInternalConfigHost&quot;> </xref>オブジェクト。"
    - id: isDesignTime
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>場合はデザイン時です。<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>ランタイムする場合。"
  overload: System.Configuration.Internal.IInternalConfigRoot.Init*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRoot.IsDesignTime
  id: IsDesignTime
  parent: System.Configuration.Internal.IInternalConfigRoot
  langs:
  - csharp
  name: IsDesignTime
  nameWithType: IInternalConfigRoot.IsDesignTime
  fullName: System.Configuration.Internal.IInternalConfigRoot.IsDesignTime
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "構成がデザイン時構成するかどうかを示す値を返します。"
  syntax:
    content: public bool IsDesignTime { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>構成が、デザイン時の構成の場合<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>場合は、構成は、デザイン時構成ではありません。"
  overload: System.Configuration.Internal.IInternalConfigRoot.IsDesignTime*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigRoot.RemoveConfig(System.String)
  id: RemoveConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigRoot
  langs:
  - csharp
  name: RemoveConfig(String)
  nameWithType: IInternalConfigRoot.RemoveConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigRoot.RemoveConfig(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "検索し、構成のレコードと指定した構成パスのすべての子を削除します。"
  syntax:
    content: public void RemoveConfig (string configPath);
    parameters:
    - id: configPath
      type: System.String
      description: "構成ファイルのパス。"
  overload: System.Configuration.Internal.IInternalConfigRoot.RemoveConfig*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.Internal.IInternalConfigRoot.ConfigChanged
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: ConfigChanged
  nameWithType: IInternalConfigRoot.ConfigChanged
  fullName: System.Configuration.Internal.IInternalConfigRoot.ConfigChanged
- uid: System.Configuration.Internal.InternalConfigEventHandler
  parent: System.Configuration.Internal
  isExternal: false
  name: InternalConfigEventHandler
  nameWithType: InternalConfigEventHandler
  fullName: System.Configuration.Internal.InternalConfigEventHandler
- uid: System.Configuration.Internal.IInternalConfigRoot.ConfigRemoved
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: ConfigRemoved
  nameWithType: IInternalConfigRoot.ConfigRemoved
  fullName: System.Configuration.Internal.IInternalConfigRoot.ConfigRemoved
- uid: System.Configuration.Internal.IInternalConfigRoot.GetConfigRecord(System.String)
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: GetConfigRecord(String)
  nameWithType: IInternalConfigRoot.GetConfigRecord(String)
  fullName: System.Configuration.Internal.IInternalConfigRoot.GetConfigRecord(String)
- uid: System.Configuration.Internal.IInternalConfigRecord
  parent: System.Configuration.Internal
  isExternal: false
  name: IInternalConfigRecord
  nameWithType: IInternalConfigRecord
  fullName: System.Configuration.Internal.IInternalConfigRecord
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IInternalConfigRoot.GetSection(System.String,System.String)
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: GetSection(String,String)
  nameWithType: IInternalConfigRoot.GetSection(String,String)
  fullName: System.Configuration.Internal.IInternalConfigRoot.GetSection(String,String)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigPath(System.String)
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: GetUniqueConfigPath(String)
  nameWithType: IInternalConfigRoot.GetUniqueConfigPath(String)
  fullName: System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigPath(String)
- uid: System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigRecord(System.String)
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: GetUniqueConfigRecord(String)
  nameWithType: IInternalConfigRoot.GetUniqueConfigRecord(String)
  fullName: System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigRecord(String)
- uid: System.Configuration.Internal.IInternalConfigRoot.Init(System.Configuration.Internal.IInternalConfigHost,System.Boolean)
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: Init(IInternalConfigHost,Boolean)
  nameWithType: IInternalConfigRoot.Init(IInternalConfigHost,Boolean)
  fullName: System.Configuration.Internal.IInternalConfigRoot.Init(IInternalConfigHost,Boolean)
- uid: System.Configuration.Internal.IInternalConfigHost
  parent: System.Configuration.Internal
  isExternal: false
  name: IInternalConfigHost
  nameWithType: IInternalConfigHost
  fullName: System.Configuration.Internal.IInternalConfigHost
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.Internal.IInternalConfigRoot.IsDesignTime
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: IsDesignTime
  nameWithType: IInternalConfigRoot.IsDesignTime
  fullName: System.Configuration.Internal.IInternalConfigRoot.IsDesignTime
- uid: System.Configuration.Internal.IInternalConfigRoot.RemoveConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: RemoveConfig(String)
  nameWithType: IInternalConfigRoot.RemoveConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigRoot.RemoveConfig(String)
- uid: System.Configuration.Internal.IInternalConfigRoot.GetConfigRecord*
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: GetConfigRecord
  nameWithType: IInternalConfigRoot.GetConfigRecord
- uid: System.Configuration.Internal.IInternalConfigRoot.GetSection*
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: GetSection
  nameWithType: IInternalConfigRoot.GetSection
- uid: System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigPath*
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: GetUniqueConfigPath
  nameWithType: IInternalConfigRoot.GetUniqueConfigPath
- uid: System.Configuration.Internal.IInternalConfigRoot.GetUniqueConfigRecord*
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: GetUniqueConfigRecord
  nameWithType: IInternalConfigRoot.GetUniqueConfigRecord
- uid: System.Configuration.Internal.IInternalConfigRoot.Init*
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: Init
  nameWithType: IInternalConfigRoot.Init
- uid: System.Configuration.Internal.IInternalConfigRoot.IsDesignTime*
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: IsDesignTime
  nameWithType: IInternalConfigRoot.IsDesignTime
- uid: System.Configuration.Internal.IInternalConfigRoot.RemoveConfig*
  parent: System.Configuration.Internal.IInternalConfigRoot
  isExternal: false
  name: RemoveConfig
  nameWithType: IInternalConfigRoot.RemoveConfig
