### YamlMime:ManagedReference
items:
- uid: System.Configuration.ApplicationScopedSettingAttribute
  id: ApplicationScopedSettingAttribute
  children:
  - System.Configuration.ApplicationScopedSettingAttribute.#ctor
  langs:
  - csharp
  name: ApplicationScopedSettingAttribute
  nameWithType: ApplicationScopedSettingAttribute
  fullName: System.Configuration.ApplicationScopedSettingAttribute
  type: Class
  summary: "アプリケーション設定プロパティがアプリケーションのすべてのユーザーに対して共通の値を持つことを指定します。 このクラスは継承できません。"
  remarks: "アプリケーション設定のプロパティは、アプリケーションまたはユーザー レベルに基づいているスコープを設定します。 カテゴリに示すものでは、アプリケーション スコープ設定のプロパティは、アプリケーションのすべてのユーザーに同じ値を提供しますが、ユーザー スコープのプロパティが、アプリケーションのユーザーごとに値を個別をします。       ApplicationScopedSettingAttribute を示し、プロパティ見なす必要がある、アプリケーション レベルの設定では、適切な記憶域の決定を適宜行う必要があります設定プロバイダー。       スコープ属性は、各設定のプロパティに必要です。 プロパティがいずれか ApplicationScopedSettingAttribute で適用されていない場合または<xref:System.Configuration.UserScopedSettingAttribute>、プロパティが設定プロバイダーで認識されません: シリアル化されていない</xref:System.Configuration.UserScopedSettingAttribute>。 ただし、同じプロパティを両方の属性を適用することはできません。 このようなしようとすると、<xref:System.Configuration.ConfigurationErrorsException>スローされます</xref:System.Configuration.ConfigurationErrorsException>。"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class ApplicationScopedSettingAttribute : System.Configuration.SettingAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.SettingAttribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ApplicationScopedSettingAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.ApplicationScopedSettingAttribute
  langs:
  - csharp
  name: ApplicationScopedSettingAttribute()
  nameWithType: ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
  fullName: System.Configuration.ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Configuration.ApplicationScopedSettingAttribute&quot;> </xref>クラスです。"
  remarks: "各アプリケーション設定のプロパティを認識し、設定プロバイダーによってシリアル化するためにスコープを&1; つの属性を持つ適用しなければなりません。"
  syntax:
    content: public ApplicationScopedSettingAttribute ();
    parameters: []
  overload: System.Configuration.ApplicationScopedSettingAttribute.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.SettingAttribute
  isExternal: false
  name: System.Configuration.SettingAttribute
- uid: System.Configuration.ApplicationScopedSettingAttribute.#ctor
  parent: System.Configuration.ApplicationScopedSettingAttribute
  isExternal: false
  name: ApplicationScopedSettingAttribute()
  nameWithType: ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
  fullName: System.Configuration.ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
- uid: System.Configuration.ApplicationScopedSettingAttribute.#ctor*
  parent: System.Configuration.ApplicationScopedSettingAttribute
  isExternal: false
  name: ApplicationScopedSettingAttribute
  nameWithType: ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute
