### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DownloadFileGroupCompletedEventArgs
  id: DownloadFileGroupCompletedEventArgs
  children:
  - System.Deployment.Application.DownloadFileGroupCompletedEventArgs.Group
  langs:
  - csharp
  name: DownloadFileGroupCompletedEventArgs
  nameWithType: DownloadFileGroupCompletedEventArgs
  fullName: System.Deployment.Application.DownloadFileGroupCompletedEventArgs
  type: Class
  summary: "最近完了したファイルのダウンロードについて説明します。"
  remarks: ''
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!code-cs[ClickOnceAPI#8](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#8)]\n [!code-cpp[ClickOnceAPI#8](~/add/codesnippet/cpp/t-system.deployment.appl_7_1.cpp)]\n [!code-vb[ClickOnceAPI#8](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#8)]"
  syntax:
    content: 'public class DownloadFileGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs'
  inheritance:
  - System.ComponentModel.AsyncCompletedEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.DownloadFileGroupCompletedEventArgs.Group
  id: Group
  parent: System.Deployment.Application.DownloadFileGroupCompletedEventArgs
  langs:
  - csharp
  name: Group
  nameWithType: DownloadFileGroupCompletedEventArgs.Group
  fullName: System.Deployment.Application.DownloadFileGroupCompletedEventArgs.Group
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "ダウンロードされるファイル グループの名前を取得します。"
  remarks: "複数の呼び出しを開始する<xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupAsync%2A>と同時に複数のファイル グループをダウンロードします</xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupAsync%2A>。 どのイベント コールバックを判断するグループを使用では、どのグループに対応します。"
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!code-cs[ClickOnceAPI#8](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#8)]\n [!code-cpp[ClickOnceAPI#8](~/add/codesnippet/cpp/p-system.deployment.appl_9_1.cpp)]\n [!code-vb[ClickOnceAPI#8](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#8)]"
  syntax:
    content: public string Group { get; }
    return:
      type: System.String
      description: "A<xref:System.String>ファイル グループの名前を表すします</xref:System.String>。"
  overload: System.Deployment.Application.DownloadFileGroupCompletedEventArgs.Group*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.AsyncCompletedEventArgs
  isExternal: false
  name: System.ComponentModel.AsyncCompletedEventArgs
- uid: System.Deployment.Application.DownloadFileGroupCompletedEventArgs.Group
  parent: System.Deployment.Application.DownloadFileGroupCompletedEventArgs
  isExternal: false
  name: Group
  nameWithType: DownloadFileGroupCompletedEventArgs.Group
  fullName: System.Deployment.Application.DownloadFileGroupCompletedEventArgs.Group
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DownloadFileGroupCompletedEventArgs.Group*
  parent: System.Deployment.Application.DownloadFileGroupCompletedEventArgs
  isExternal: false
  name: Group
  nameWithType: DownloadFileGroupCompletedEventArgs.Group
