### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.SupportedRuntimeMissingException
  id: SupportedRuntimeMissingException
  children:
  - System.Deployment.Application.SupportedRuntimeMissingException.#ctor
  - System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String)
  - System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String,System.Exception)
  - System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion
  langs:
  - csharp
  name: SupportedRuntimeMissingException
  nameWithType: SupportedRuntimeMissingException
  fullName: System.Deployment.Application.SupportedRuntimeMissingException
  type: Class
  summary: "このアプリケーションと互換性があるランタイムのバージョンが見つからない場合に、この例外がスローされます。"
  syntax:
    content: 'public class SupportedRuntimeMissingException : System.Deployment.Application.DependentPlatformMissingException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  - System.Deployment.Application.DependentPlatformMissingException
  implements: []
  inheritedMembers:
  - System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  platform:
  - net462
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: SupportedRuntimeMissingException()
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException()
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Deployment.Application.SupportedRuntimeMissingException&quot;> </xref>エラーを説明するシステム提供のメッセージを持つクラス。"
  remarks: "このコンス トラクターは、 <xref:System.Exception.Message%2A>「ランタイム不足例外」など、エラーを説明するシステム提供メッセージの新しいインスタンスのプロパティ</xref:System.Exception.Message%2A>を初期化します このメッセージでは、現在のシステム カルチャが考慮されます。       次の表は、 <xref:System.Deployment.Application.SupportedRuntimeMissingException>。</xref:System.Deployment.Application.SupportedRuntimeMissingException>のインスタンスの初期プロパティ値を示しています。      |プロパティ |値 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|`null`.|  |<xref:System.Exception.Message%2A>|ローカライズされたエラー メッセージ文字列 |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> 。"
  syntax:
    content: public SupportedRuntimeMissingException ();
    parameters: []
  overload: System.Deployment.Application.SupportedRuntimeMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: SupportedRuntimeMissingException(String)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(String)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Deployment.Application.SupportedRuntimeMissingException&quot;> </xref>エラーを説明するメッセージが指定されたクラスです。"
  remarks: "次の表は、 <xref:System.Deployment.Application.SupportedRuntimeMissingException>。</xref:System.Deployment.Application.SupportedRuntimeMissingException>のインスタンスの初期プロパティ値を示しています。      |プロパティ |値 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|`null`.|  |<xref:System.Exception.Message%2A>|指定されたエラー メッセージ文字列`message`|</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> 。"
  syntax:
    content: public SupportedRuntimeMissingException (string message);
    parameters:
    - id: message
      type: System.String
      description: "例外を説明するメッセージ。 このコンス トラクターの呼び出し元は、この文字列が現在のシステムのカルチャに合わせてローカライズ済みであることを確認するために必要です。"
  overload: System.Deployment.Application.SupportedRuntimeMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Deployment.Application.SupportedRuntimeMissingException&quot;> </xref>シリアル化されたデータを持つクラス。"
  remarks: "このコンス トラクターは、ストリームで送信された例外オブジェクトを再構成する逆シリアル化中に呼び出されます。"
  syntax:
    content: protected SupportedRuntimeMissingException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "シリアル化されたオブジェクト データを保持するオブジェクト。"
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: "ソースまたは転送先に関する文脈情報。"
  overload: System.Deployment.Application.SupportedRuntimeMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: SupportedRuntimeMissingException(String,Exception)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(String,Exception)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Deployment.Application.SupportedRuntimeMissingException&quot;> </xref>指定したエラー メッセージおよびこの例外の原因となった内部例外への参照を持つクラス。"
  remarks: "前の例外への参照を含める必要があります前の例外の直接の結果としてスローされる例外、<xref:System.Exception.InnerException%2A>プロパティ</xref:System.Exception.InnerException%2A>。 <xref:System.Exception.InnerException%2A>プロパティは、コンス トラクターに渡されたものと同じ値を返しますまたは`null`場合、<xref:System.Exception.InnerException%2A>プロパティがコンス トラクターには、内部例外値を指定していません</xref:System.Exception.InnerException%2A></xref:System.Exception.InnerException%2A>。       次の表は、 <xref:System.Deployment.Application.SupportedRuntimeMissingException>。</xref:System.Deployment.Application.SupportedRuntimeMissingException>のインスタンスの初期プロパティ値を示しています。      |プロパティ |値 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|`null`.|  |<xref:System.Exception.Message%2A>|指定されたエラー メッセージ文字列`message`|</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> 。"
  syntax:
    content: public SupportedRuntimeMissingException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "例外を説明するメッセージ。 このコンス トラクターの呼び出し元は、この文字列が現在のシステムのカルチャに合わせてローカライズ済みであることを確認するために必要です。"
    - id: innerException
      type: System.Exception
      description: "現在の例外の原因となった例外。 場合、`innerException`パラメーター <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>で現在の例外が発生、 <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref>ブロックは、内部例外を処理します。"
  overload: System.Deployment.Application.SupportedRuntimeMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: SupportedRuntimeMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData(SerializationInfo,StreamingContext)
  type: Method
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Deployment.Application.SupportedRuntimeMissingException&quot;> </xref>シリアル化されたデータを持つクラス。"
  remarks: "このコンス トラクターは、ストリームで送信された例外オブジェクトを再構成する逆シリアル化中に呼び出されます。"
  syntax:
    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "シリアル化されたオブジェクト データを保持するオブジェクト。"
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "ソースまたは転送先に関する文脈情報。"
  overload: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion
  id: SupportedRuntimeVersion
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: SupportedRuntimeVersion
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeVersion
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "このアプリケーションをインストールして実行できますランタイムのバージョンを取得します。"
  syntax:
    content: public string SupportedRuntimeVersion { get; }
    return:
      type: System.String
      description: "ランタイムのバージョン番号を表す文字列。"
  overload: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: System.Deployment.Application.DependentPlatformMissingException
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeMissingException()
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException()
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException()
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String)
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeMissingException(String)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(String)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeMissingException(String,Exception)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(String,Exception)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: SupportedRuntimeMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData(SerializationInfo,StreamingContext)
- uid: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeVersion
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeVersion
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor*
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeMissingException
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException
- uid: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData*
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: GetObjectData
  nameWithType: SupportedRuntimeMissingException.GetObjectData
- uid: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion*
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeVersion
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeVersion
