### YamlMime:ManagedReference
items:
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier
  id: IApplicationIdentifier
  children:
  - System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId
  langs:
  - csharp
  name: IApplicationIdentifier
  nameWithType: IApplicationIdentifier
  fullName: System.Runtime.Caching.Hosting.IApplicationIdentifier
  type: Interface
  summary: "キャッシュの実装は、ホスト環境との対話に使用できるアプリケーション ドメインの識別子を定義します。"
  remarks: "A [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] ASP.NET などのホスト環境は IApplicationIdentifier インターフェイスを使用して、個々 のアプリケーション ドメインを識別する文字列を定義します。 ホスト環境では、IApplicationIdentifier インターフェイスを実装します。 このインターフェイスは、使用できる、<xref:System.Runtime.Caching.ObjectCache>実装を介して、<xref:System.Runtime.Caching.ObjectCache.Host%2A>プロパティ</xref:System.Runtime.Caching.ObjectCache.Host%2A></xref:System.Runtime.Caching.ObjectCache>。       キャッシュ実装では、この参照を使用して、アプリケーション ドメインの識別子を取得します。 ASP.NET では、キャッシュの実装は、キャッシュ パフォーマンス カウンターの識別子を構築するためにアプリケーションの識別子を使用します。 これは、パフォーマンスの名前に、複数のアプリケーション ドメインを実行しているときに、アプリケーション ドメイン間で区別できるカウンターのインスタンスを提供します。"
  syntax:
    content: public interface IApplicationIdentifier
  implements: []
  platform:
  - net462
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId
  id: GetApplicationId
  parent: System.Runtime.Caching.Hosting.IApplicationIdentifier
  langs:
  - csharp
  name: GetApplicationId()
  nameWithType: IApplicationIdentifier.GetApplicationId()
  fullName: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId()
  type: Method
  assemblies:
  - System.Runtime.Caching
  namespace: System.Runtime.Caching.Hosting
  summary: "アプリケーション ドメインの識別子を取得します。"
  remarks: "GetApplicationId メソッドは通常によって実装され、[!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)]ホスト環境のアプリケーション識別子を構築するために、<xref:System.Runtime.Caching.ObjectCache>実装</xref:System.Runtime.Caching.ObjectCache>。 A<xref:System.Runtime.Caching.ObjectCache>実装では、この情報を使用して、現在実行されているアプリケーション ドメインを識別します</xref:System.Runtime.Caching.ObjectCache>。       たとえば、ASP.NET では、キャッシュ識別子を使用してアプリケーション キャッシュ パフォーマンス カウンターの識別子を構築します。 キャッシュは、ホスト環境によって実装されている GetApplicationId メソッドを呼び出して、ホスト、識別子を返します。 これは、パフォーマンスの名前に、複数のアプリケーション ドメインを実行しているときに、アプリケーション ドメイン間で区別できるカウンターのインスタンスを提供します。"
  syntax:
    content: public string GetApplicationId ();
    parameters: []
    return:
      type: System.String
      description: "現在のアプリケーション ドメインの一意の識別子。"
  overload: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId
  parent: System.Runtime.Caching.Hosting.IApplicationIdentifier
  isExternal: false
  name: GetApplicationId()
  nameWithType: IApplicationIdentifier.GetApplicationId()
  fullName: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId()
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId*
  parent: System.Runtime.Caching.Hosting.IApplicationIdentifier
  isExternal: false
  name: GetApplicationId
  nameWithType: IApplicationIdentifier.GetApplicationId
