### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsPropertyValue
  id: SettingsPropertyValue
  children:
  - System.Configuration.SettingsPropertyValue.#ctor(System.Configuration.SettingsProperty)
  - System.Configuration.SettingsPropertyValue.Deserialized
  - System.Configuration.SettingsPropertyValue.IsDirty
  - System.Configuration.SettingsPropertyValue.Name
  - System.Configuration.SettingsPropertyValue.Property
  - System.Configuration.SettingsPropertyValue.PropertyValue
  - System.Configuration.SettingsPropertyValue.SerializedValue
  - System.Configuration.SettingsPropertyValue.UsingDefaultValue
  langs:
  - csharp
  name: SettingsPropertyValue
  nameWithType: SettingsPropertyValue
  fullName: System.Configuration.SettingsPropertyValue
  type: Class
  summary: "ロードしてのインスタンスで格納できる設定のプロパティの値を含む<xref href=&quot;System.Configuration.SettingsBase&quot;></xref>です。"
  remarks: "プロファイル データの実際の一部のクラスの表現。 A<xref:System.Configuration.SettingsProperty>インスタンス SettingsPropertyValue オブジェクトのインスタンス内に格納された値を説明します</xref:System.Configuration.SettingsProperty>。"
  syntax:
    content: public class SettingsPropertyValue
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyValue.#ctor(System.Configuration.SettingsProperty)
  id: '#ctor(System.Configuration.SettingsProperty)'
  parent: System.Configuration.SettingsPropertyValue
  langs:
  - csharp
  name: SettingsPropertyValue(SettingsProperty)
  nameWithType: SettingsPropertyValue.SettingsPropertyValue(SettingsProperty)
  fullName: System.Configuration.SettingsPropertyValue.SettingsPropertyValue(SettingsProperty)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Configuration.SettingsPropertyValue&quot;> </xref>クラス、指定されたパラメーターを基にします。"
  remarks: "> [!IMPORTANT]> 信頼できないデータをこのメソッドを呼び出すと、セキュリティ上のリスクです。 このメソッドでは、信頼されたデータだけです。 詳細については、次を参照してください。[信頼されていないデータのセキュリティ リスク](http://go.microsoft.com/fwlink/?LinkId=330378)です。       <xref:System.Configuration.SettingsProperty>オブジェクトによって格納される値に関する情報を説明する、<xref:System.Configuration.SettingsPropertyValue>オブジェクト</xref:System.Configuration.SettingsPropertyValue></xref:System.Configuration.SettingsProperty>。"
  syntax:
    content: public SettingsPropertyValue (System.Configuration.SettingsProperty property);
    parameters:
    - id: property
      type: System.Configuration.SettingsProperty
      description: "指定します、 <xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref>オブジェクト。"
  overload: System.Configuration.SettingsPropertyValue.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyValue.Deserialized
  id: Deserialized
  parent: System.Configuration.SettingsPropertyValue
  langs:
  - csharp
  name: Deserialized
  nameWithType: SettingsPropertyValue.Deserialized
  fullName: System.Configuration.SettingsPropertyValue.Deserialized
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "取得または設定するかどうかの値、 <xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref>オブジェクトが逆シリアル化されました。"
  remarks: "プロパティの値の逆シリアル化は要求時にのみ実行されます。"
  syntax:
    content: public bool Deserialized { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>場合の値、 <xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref>逆シリアル化された、それ以外のオブジェクトが表示された<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>です。"
  overload: System.Configuration.SettingsPropertyValue.Deserialized*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyValue.IsDirty
  id: IsDirty
  parent: System.Configuration.SettingsPropertyValue
  langs:
  - csharp
  name: IsDirty
  nameWithType: SettingsPropertyValue.IsDirty
  fullName: System.Configuration.SettingsPropertyValue.IsDirty
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "取得または設定するかどうかの値、 <xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref>オブジェクトが変更されました。"
  remarks: "IsDirty プロパティは、このクラスが格納されている値が変更されたことを示します。 既定値は`false`します。 IsDirty プロパティに設定`true`次の条件下で: 1。  含まれる値、<xref:System.Configuration.SettingsPropertyValue>オブジェクトが変更されました</xref:System.Configuration.SettingsPropertyValue>。      2.  含まれる値、<xref:System.Configuration.SettingsPropertyValue>オブジェクトがアクセスされ、値は文字列またはプリミティブ型など`int`、 `float`、 `real`、または`DateTime`</xref:System.Configuration.SettingsPropertyValue>。 値を管理する場合、<xref:System.Configuration.SettingsPropertyValue>オブジェクトは、複雑な型 (たとえば、 <xref:System.Collections.ArrayList>)、方法はありません、<xref:System.Configuration.SettingsPropertyValue>加えられた変更を検出するオブジェクト</xref:System.Configuration.SettingsPropertyValue></xref:System.Collections.ArrayList></xref:System.Configuration.SettingsPropertyValue>。 その結果、<xref:System.Configuration.SettingsPropertyValue>オブジェクト排他が想定する複合型はダーティからアクセスした後、<xref:System.Configuration.SettingsPropertyValue.PropertyValue%2A>プロパティ</xref:System.Configuration.SettingsPropertyValue.PropertyValue%2A></xref:System.Configuration.SettingsPropertyValue>。"
  syntax:
    content: public bool IsDirty { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>場合の値、 <xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref>オブジェクトが変更されました。 それ以外の場合、 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>です。"
  overload: System.Configuration.SettingsPropertyValue.IsDirty*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyValue.Name
  id: Name
  parent: System.Configuration.SettingsPropertyValue
  langs:
  - csharp
  name: Name
  nameWithType: SettingsPropertyValue.Name
  fullName: System.Configuration.SettingsPropertyValue.Name
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "関連付けられているプロパティの名前を取得<xref href=&quot;System.Configuration.SettingsProperty&quot;></xref>オブジェクト。"
  syntax:
    content: public string Name { get; }
    return:
      type: System.String
      description: "名前、 <xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref>オブジェクト。"
  overload: System.Configuration.SettingsPropertyValue.Name*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyValue.Property
  id: Property
  parent: System.Configuration.SettingsPropertyValue
  langs:
  - csharp
  name: Property
  nameWithType: SettingsPropertyValue.Property
  fullName: System.Configuration.SettingsPropertyValue.Property
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "取得、 <xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref>オブジェクト。"
  syntax:
    content: public System.Configuration.SettingsProperty Property { get; }
    return:
      type: System.Configuration.SettingsProperty
      description: "<xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref>を記述するオブジェクト、 <xref href=&quot;System.Configuration.SettingsPropertyValue&quot;> </xref>オブジェクト。"
  overload: System.Configuration.SettingsPropertyValue.Property*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyValue.PropertyValue
  id: PropertyValue
  parent: System.Configuration.SettingsPropertyValue
  langs:
  - csharp
  name: PropertyValue
  nameWithType: SettingsPropertyValue.PropertyValue
  fullName: System.Configuration.SettingsPropertyValue.PropertyValue
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "取得または設定の値、 <xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref>オブジェクト。"
  syntax:
    content: public object PropertyValue { get; set; }
    return:
      type: System.Object
      description: "値、 <xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref>オブジェクト。 この値が設定されている場合、 <> </> *> プロパティに設定されている<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>と<> *> に設定されている<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>です。       PropertyValue プロパティから値を最初にアクセスし、値が最初に格納されている場合、 <xref href=&quot;System.Configuration.SettingsPropertyValue&quot;> </xref>オブジェクトとしてシリアル化された表現を使用して、 <> </> *> プロパティ、PropertyValue プロパティは、基になる値の逆シリアル化をトリガーします。副作用として、 <> </> *> プロパティ設定されます<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>です。       ASP.NET では、この一連のイベントが発生した場合、および逆シリアル化プロセス中にエラーが発生した場合は、ASP.NET の稼働状況の監視機能を使用して、エラーが記録されます。 既定では、つまり、逆シリアル化エラーが表示されるアプリケーション イベント ログで ASP.NET で実行する場合。 このプロセスは、ASP.NET の外部で発生し、逆シリアル化中にエラーが発生した場合は、エラーが抑制され、逆シリアル化中に、ロジックの残りの部分が発生します。 逆シリアル化のシリアル化された値が存在しない場合と、逆シリアル化を試みると、し<xref href=&quot;System.Configuration.SettingsPropertyValue&quot;></xref>オブジェクトは代わりにしようと関連付けられたに定義されているいずれかが構成された場合、既定値を返す<xref href=&quot;System.Configuration.SettingsProperty&quot;></xref>インスタンス。 この場合場合、 <> </> *> プロパティが設定されたいずれかに<xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>、または&quot;[null]&quot;の文字列、 <xref href=&quot;System.Configuration.SettingsPropertyValue&quot;> </xref>オブジェクト プロパティを初期化、PropertyValue いずれかに<xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>参照型の場合、または関連付けられている値型の既定値にします。その一方で場合、 <> </> *> プロパティ (&quot;[null 以外]&quot;)、有効なオブジェクトの参照または文字列値を保持する、 <> </> *> プロパティが返されます。     シリアル化、逆シリアル化が試行され、既定値が指定されていないときに逆シリアル化された値がない場合、空の文字列が文字列型に対して返されます。呼び出して他のすべての種類では、既定のインスタンスが返されます<> *>: 参照型に既定のコンス トラクターを使用してオブジェクト インスタンスを作成するを試行ことを意味します。  この試行が失敗した場合、し<xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>が返されます。"
  overload: System.Configuration.SettingsPropertyValue.PropertyValue*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "既定値を使用しているときに、 <> </> *> プロパティ、エラーが発生しました。変換を試行するか、 <> </> *> は有効な型のプロパティは、次の失敗、または結果の値は<xref:System.Configuration.SettingsProperty.PropertyType*>.</xref:System.Configuration.SettingsProperty.PropertyType*>によって定義された型と互換性がありません"
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyValue.SerializedValue
  id: SerializedValue
  parent: System.Configuration.SettingsPropertyValue
  langs:
  - csharp
  name: SerializedValue
  nameWithType: SettingsPropertyValue.SerializedValue
  fullName: System.Configuration.SettingsPropertyValue.SerializedValue
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "シリアル化された値の取得または設定、 <xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref>オブジェクト。"
  remarks: "場合、<xref:System.Configuration.SettingsPropertyValue>ことを検出するインスタンス、<xref:System.Configuration.SettingsPropertyValue.PropertyValue%2A>前回 SerializedValue プロパティが呼び出されたために、プロパティが変更された、おそれがある<xref:System.Configuration.SettingsPropertyValue.PropertyValue%2A>、シリアル化された形式に変換するプロパティ</xref:System.Configuration.SettingsPropertyValue.PropertyValue%2A></xref:System.Configuration.SettingsPropertyValue.PropertyValue%2A></xref:System.Configuration.SettingsPropertyValue>。 使用する特定のシリアル化機構がによって定義された、<xref:System.Configuration.SettingsProperty.SerializeAs%2A>プロパティを<xref:System.Configuration.SettingsProperty>インスタンスに関連付けられている、<xref:System.Configuration.SettingsPropertyValue>インスタンス</xref:System.Configuration.SettingsPropertyValue></xref:System.Configuration.SettingsProperty></xref:System.Configuration.SettingsProperty.SerializeAs%2A>。 現在サポートされているシリアル化オプションは、オブジェクトを文字列型コンバーターを使用して文字列に変換を使用してシリアル化を<xref:System.Xml.Serialization.XmlSerializer>、またはバイナリのシリアル化を実行します</xref:System.Xml.Serialization.XmlSerializer>。      > [!NOTE] > 基になるシリアライザーはシリアル化プロセス中に例外をスローする可能性があります。       直前の呼び出し元コードが必要な<xref:System.Security.Permissions.SecurityPermissionFlag>権限 (として利用可能な権限のいずれかの一部<xref:System.Security.Permissions.SecurityPermission>) をこのプロパティの get アクセス操作子または set アクセス操作子を呼び出す</xref:System.Security.Permissions.SecurityPermission></xref:System.Security.Permissions.SecurityPermissionFlag>。  このアクセス許可を使用した強制は、<xref:System.Security.Permissions.SecurityAction>列挙値</xref:System.Security.Permissions.SecurityAction>。"
  syntax:
    content: public object SerializedValue { get; set; }
    return:
      type: System.Object
      description: "シリアル化された値、 <xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref>オブジェクト。"
  overload: System.Configuration.SettingsPropertyValue.SerializedValue*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "プロパティのシリアル化オプションには、文字列型コンバーターの使用が示されますが、型コンバーターを使用できませんでした。"
  platform:
  - net462
- uid: System.Configuration.SettingsPropertyValue.UsingDefaultValue
  id: UsingDefaultValue
  parent: System.Configuration.SettingsPropertyValue
  langs:
  - csharp
  name: UsingDefaultValue
  nameWithType: SettingsPropertyValue.UsingDefaultValue
  fullName: System.Configuration.SettingsPropertyValue.UsingDefaultValue
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "指定するブール値を取得するかどうかの値、 <xref href=&quot;System.Configuration.SettingsPropertyValue&quot;> </xref>オブジェクトは既定値で定義されて、 <xref:System.Configuration.SettingsProperty.DefaultValue*>、関連するプロパティ値<xref href=&quot;System.Configuration.SettingsProperty&quot;></xref>オブジェクト</xref:System.Configuration.SettingsProperty.DefaultValue*>。"
  syntax:
    content: public bool UsingDefaultValue { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>場合の値、 <xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref>オブジェクトは、既定値以外の場合、 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>です。"
  overload: System.Configuration.SettingsPropertyValue.UsingDefaultValue*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Configuration.SettingsPropertyValue.#ctor(System.Configuration.SettingsProperty)
  parent: System.Configuration.SettingsPropertyValue
  isExternal: false
  name: SettingsPropertyValue(SettingsProperty)
  nameWithType: SettingsPropertyValue.SettingsPropertyValue(SettingsProperty)
  fullName: System.Configuration.SettingsPropertyValue.SettingsPropertyValue(SettingsProperty)
- uid: System.Configuration.SettingsProperty
  parent: System.Configuration
  isExternal: false
  name: SettingsProperty
  nameWithType: SettingsProperty
  fullName: System.Configuration.SettingsProperty
- uid: System.Configuration.SettingsPropertyValue.Deserialized
  parent: System.Configuration.SettingsPropertyValue
  isExternal: false
  name: Deserialized
  nameWithType: SettingsPropertyValue.Deserialized
  fullName: System.Configuration.SettingsPropertyValue.Deserialized
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.SettingsPropertyValue.IsDirty
  parent: System.Configuration.SettingsPropertyValue
  isExternal: false
  name: IsDirty
  nameWithType: SettingsPropertyValue.IsDirty
  fullName: System.Configuration.SettingsPropertyValue.IsDirty
- uid: System.Configuration.SettingsPropertyValue.Name
  parent: System.Configuration.SettingsPropertyValue
  isExternal: false
  name: Name
  nameWithType: SettingsPropertyValue.Name
  fullName: System.Configuration.SettingsPropertyValue.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsPropertyValue.Property
  parent: System.Configuration.SettingsPropertyValue
  isExternal: false
  name: Property
  nameWithType: SettingsPropertyValue.Property
  fullName: System.Configuration.SettingsPropertyValue.Property
- uid: System.Configuration.SettingsPropertyValue.PropertyValue
  parent: System.Configuration.SettingsPropertyValue
  isExternal: false
  name: PropertyValue
  nameWithType: SettingsPropertyValue.PropertyValue
  fullName: System.Configuration.SettingsPropertyValue.PropertyValue
- uid: System.Configuration.SettingsPropertyValue.SerializedValue
  parent: System.Configuration.SettingsPropertyValue
  isExternal: false
  name: SerializedValue
  nameWithType: SettingsPropertyValue.SerializedValue
  fullName: System.Configuration.SettingsPropertyValue.SerializedValue
- uid: System.Configuration.SettingsPropertyValue.UsingDefaultValue
  parent: System.Configuration.SettingsPropertyValue
  isExternal: false
  name: UsingDefaultValue
  nameWithType: SettingsPropertyValue.UsingDefaultValue
  fullName: System.Configuration.SettingsPropertyValue.UsingDefaultValue
- uid: System.Configuration.SettingsPropertyValue.#ctor*
  parent: System.Configuration.SettingsPropertyValue
  isExternal: false
  name: SettingsPropertyValue
  nameWithType: SettingsPropertyValue.SettingsPropertyValue
- uid: System.Configuration.SettingsPropertyValue.Deserialized*
  parent: System.Configuration.SettingsPropertyValue
  isExternal: false
  name: Deserialized
  nameWithType: SettingsPropertyValue.Deserialized
- uid: System.Configuration.SettingsPropertyValue.IsDirty*
  parent: System.Configuration.SettingsPropertyValue
  isExternal: false
  name: IsDirty
  nameWithType: SettingsPropertyValue.IsDirty
- uid: System.Configuration.SettingsPropertyValue.Name*
  parent: System.Configuration.SettingsPropertyValue
  isExternal: false
  name: Name
  nameWithType: SettingsPropertyValue.Name
- uid: System.Configuration.SettingsPropertyValue.Property*
  parent: System.Configuration.SettingsPropertyValue
  isExternal: false
  name: Property
  nameWithType: SettingsPropertyValue.Property
- uid: System.Configuration.SettingsPropertyValue.PropertyValue*
  parent: System.Configuration.SettingsPropertyValue
  isExternal: false
  name: PropertyValue
  nameWithType: SettingsPropertyValue.PropertyValue
- uid: System.Configuration.SettingsPropertyValue.SerializedValue*
  parent: System.Configuration.SettingsPropertyValue
  isExternal: false
  name: SerializedValue
  nameWithType: SettingsPropertyValue.SerializedValue
- uid: System.Configuration.SettingsPropertyValue.UsingDefaultValue*
  parent: System.Configuration.SettingsPropertyValue
  isExternal: false
  name: UsingDefaultValue
  nameWithType: SettingsPropertyValue.UsingDefaultValue
