### YamlMime:ManagedReference
items:
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute
  id: SettingsAllowAnonymousAttribute
  children:
  - System.Web.Profile.SettingsAllowAnonymousAttribute.#ctor(System.Boolean)
  - System.Web.Profile.SettingsAllowAnonymousAttribute.Allow
  - System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute
  langs:
  - csharp
  name: SettingsAllowAnonymousAttribute
  nameWithType: SettingsAllowAnonymousAttribute
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute
  type: Class
  summary: "プロファイル プロパティを設定または匿名ユーザーがアクセスできるかどうかを識別します。"
  remarks: "SettingsAllowAnonymousAttribute クラスを使用して、ユーザーが匿名ユーザーの場合、カスタム プロファイルの実装のプロパティにアクセスするかどうかを識別します。 匿名 id を有効にする方法については、構成要素の付属のマニュアルを参照してください。       プロファイル プロパティの SettingsAllowAnonymousAttribute が指定されていない場合、プロファイル プロパティへの匿名アクセスが許可されていません。       カスタム プロファイルの実装が継承されたクラス、<xref:System.Web.Profile.ProfileBase>クラスを abstract であり、ユーザー プロファイルの構成要素で指定されていないプロパティを定義します</xref:System.Web.Profile.ProfileBase>。 カスタムのユーザー プロファイルの種類を指定するには、アプリケーションの Web.config ファイルで、`inherits`次の例で示すように構成要素の属性です。       `<configuration>`       `<connectionStrings>`       `<add`       `name=&quot;SqlServices&quot;`       `connectionString=&quot;Data Source=localhost;Integrated Security=SSPI;Initial Catalog=aspnetdb;&quot; />`       `</connectionStrings>`       `<system.web>`       `<authentication mode=&quot;Forms&quot; >`       `<forms`       `loginUrl=&quot;login.aspx&quot;`       `name=&quot;.ASPXFORMSAUTH&quot; />`       `</authentication>`       `<authorization>`       `<deny users=&quot;?&quot; />`       `</authorization>`       `<profile inherits=&quot;Samples.AspNet.Profile.EmployeeProfile&quot;`       `defaultProvider=&quot;SqlProvider&quot;>`       `<providers>`       `<clear />`       `<add`       `name=&quot;SqlProvider&quot;`       `type=&quot;System.Web.Profile.SqlProfileProvider&quot;`       `connectionStringName=&quot;SqlServices&quot;`       `description=&quot;SQL Profile Provider for Sample&quot;/>`       `<add`       `name=&quot;EmployeeInfoProvider&quot;`       `type=&quot;System.Web.Profile.SqlProfileProvider&quot;`       `connectionStringName=&quot;SqlServices&quot;`       `description=&quot;SQL Profile Provider for Employee Info&quot;/>`       `</providers>`       `<properties>`       `<add name=&quot;GarmentSize&quot; />`       `</properties>`       `</profile>`       `</system.web>`       `</configuration>`"
  example:
  - "The following code example defines a class that inherits from the <xref:System.Web.Profile.ProfileBase> to create a custom profile. The type of the custom profile is specified in the `inherits` attribute of the  configuration element in the Web.config file for an application.  \n  \n [!code-cs[System.Web.Profile.ProfileBase#1](~/add/codesnippet/csharp/t-system.web.profile.set_1.cs)]\n [!code-vb[System.Web.Profile.ProfileBase#1](~/add/codesnippet/visualbasic/t-system.web.profile.set_1.vb)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class SettingsAllowAnonymousAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.#ctor(System.Boolean)
  id: '#ctor(System.Boolean)'
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  langs:
  - csharp
  name: SettingsAllowAnonymousAttribute(Boolean)
  nameWithType: SettingsAllowAnonymousAttribute.SettingsAllowAnonymousAttribute(Boolean)
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute.SettingsAllowAnonymousAttribute(Boolean)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Profile
  summary: "新しいインスタンスを作成、 <xref href=&quot;System.Web.Profile.SettingsAllowAnonymousAttribute&quot;> </xref>クラスし、関連付けられているプロファイル プロパティへの匿名アクセスを許可するかどうかを指定します。"
  remarks: "<xref:System.Web.Profile.SettingsAllowAnonymousAttribute>場合は、ユーザーが匿名のユーザー プロファイルのカスタム実装のプロパティにアクセスするかどうかを識別するクラスを使用します</xref:System.Web.Profile.SettingsAllowAnonymousAttribute>。 匿名 id を有効にする方法については、構成要素を参照してください。       ない場合は<xref:System.Web.Profile.SettingsAllowAnonymousAttribute>プロファイル プロパティ、プロファイル プロパティへの匿名アクセスを許可しない場合を指定します</xref:System.Web.Profile.SettingsAllowAnonymousAttribute>。       カスタム プロファイルの実装が継承されたクラス、<xref:System.Web.Profile.ProfileBase>クラスを abstract であり、ユーザー プロファイルの構成要素で指定されていないプロパティを定義します</xref:System.Web.Profile.ProfileBase>。"
  example:
  - "The following example defines a class that inherits from the <xref:System.Web.Profile.ProfileBase> class to create a custom profile. The type of the custom profile is specified in the `inherits` attribute of the  configuration element in the Web.config file for an application. For an example of a configuration file that specifies a custom profile implementation, see the <xref:System.Web.Profile.SettingsAllowAnonymousAttribute> class overview.  \n  \n [!code-cs[System.Web.Profile.ProfileBase#1](~/add/codesnippet/csharp/m-system.web.profile.set_1.cs)]\n [!code-vb[System.Web.Profile.ProfileBase#1](~/add/codesnippet/visualbasic/m-system.web.profile.set_1.vb)]"
  syntax:
    content: public SettingsAllowAnonymousAttribute (bool allow);
    parameters:
    - id: allow
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>匿名ユーザーは、関連付けられているプロファイル プロパティにアクセスできる場合それ以外の場合<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>です。"
  overload: System.Web.Profile.SettingsAllowAnonymousAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.Allow
  id: Allow
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  langs:
  - csharp
  name: Allow
  nameWithType: SettingsAllowAnonymousAttribute.Allow
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute.Allow
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Profile
  summary: "ユーザーが匿名ユーザーの場合、カスタム プロファイルの実装の関連付けられているプロパティにアクセスできるかどうかを示す値を取得します。"
  syntax:
    content: public bool Allow { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>匿名ユーザーは、関連付けられているプロファイル プロパティにアクセスできる場合それ以外の場合、 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>です。"
  overload: System.Web.Profile.SettingsAllowAnonymousAttribute.Allow*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute
  id: IsDefaultAttribute
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  langs:
  - csharp
  name: IsDefaultAttribute()
  nameWithType: SettingsAllowAnonymousAttribute.IsDefaultAttribute()
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Profile
  summary: "示す値を取得するかどうか、<xref:System.Web.Profile.SettingsAllowAnonymousAttribute.Allow*>プロパティが既定値に設定します</xref:System.Web.Profile.SettingsAllowAnonymousAttribute.Allow*>。"
  syntax:
    content: public override bool IsDefaultAttribute ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>場合、<xref:System.Web.Profile.SettingsAllowAnonymousAttribute.Allow*>プロパティが既定値ですそれ以外の場合<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。</xref:System.Web.Profile.SettingsAllowAnonymousAttribute.Allow*> 。"
  overload: System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.#ctor(System.Boolean)
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  isExternal: false
  name: SettingsAllowAnonymousAttribute(Boolean)
  nameWithType: SettingsAllowAnonymousAttribute.SettingsAllowAnonymousAttribute(Boolean)
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute.SettingsAllowAnonymousAttribute(Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.Allow
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  isExternal: false
  name: Allow
  nameWithType: SettingsAllowAnonymousAttribute.Allow
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute.Allow
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  isExternal: false
  name: IsDefaultAttribute()
  nameWithType: SettingsAllowAnonymousAttribute.IsDefaultAttribute()
  fullName: System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute()
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.#ctor*
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  isExternal: false
  name: SettingsAllowAnonymousAttribute
  nameWithType: SettingsAllowAnonymousAttribute.SettingsAllowAnonymousAttribute
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.Allow*
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  isExternal: false
  name: Allow
  nameWithType: SettingsAllowAnonymousAttribute.Allow
- uid: System.Web.Profile.SettingsAllowAnonymousAttribute.IsDefaultAttribute*
  parent: System.Web.Profile.SettingsAllowAnonymousAttribute
  isExternal: false
  name: IsDefaultAttribute
  nameWithType: SettingsAllowAnonymousAttribute.IsDefaultAttribute
