### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.EndToEndTracingElement
  id: EndToEndTracingElement
  children:
  - System.ServiceModel.Configuration.EndToEndTracingElement.#ctor
  - System.ServiceModel.Configuration.EndToEndTracingElement.ActivityTracing
  - System.ServiceModel.Configuration.EndToEndTracingElement.MessageFlowTracing
  - System.ServiceModel.Configuration.EndToEndTracingElement.PropagateActivity
  - System.ServiceModel.Configuration.EndToEndTracingElement.Properties
  langs:
  - csharp
  name: EndToEndTracingElement
  nameWithType: EndToEndTracingElement
  fullName: System.ServiceModel.Configuration.EndToEndTracingElement
  type: Class
  summary: "構成ファイル要素の設定を有効にして、サービス アプリケーションの実行中のエンド ツー エンド トレースのさまざまな側面を無効化を処理します。"
  syntax:
    content: 'public sealed class EndToEndTracingElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  langs:
  - csharp
  name: EndToEndTracingElement()
  nameWithType: EndToEndTracingElement.EndToEndTracingElement()
  fullName: System.ServiceModel.Configuration.EndToEndTracingElement.EndToEndTracingElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "新しいインスタンスを作成、 <xref href=&quot;System.ServiceModel.Configuration.EndToEndTracingElement&quot;> </xref>クラスです。"
  syntax:
    content: public EndToEndTracingElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.EndToEndTracingElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.ActivityTracing
  id: ActivityTracing
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  langs:
  - csharp
  name: ActivityTracing
  nameWithType: EndToEndTracingElement.ActivityTracing
  fullName: System.ServiceModel.Configuration.EndToEndTracingElement.ActivityTracing
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "アクティビティ トレースが有効になっているかどうかを示す値を取得します。"
  syntax:
    content: public bool ActivityTracing { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>アクティビティ トレースが有効である場合それ以外の場合、 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>です。"
  overload: System.ServiceModel.Configuration.EndToEndTracingElement.ActivityTracing*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.MessageFlowTracing
  id: MessageFlowTracing
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  langs:
  - csharp
  name: MessageFlowTracing
  nameWithType: EndToEndTracingElement.MessageFlowTracing
  fullName: System.ServiceModel.Configuration.EndToEndTracingElement.MessageFlowTracing
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "メッセージ フローのトレースが有効かどうかを示す値を取得します。"
  syntax:
    content: public bool MessageFlowTracing { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>メッセージ フローのトレースが有効になっているとします。それ以外の場合、 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>です。"
  overload: System.ServiceModel.Configuration.EndToEndTracingElement.MessageFlowTracing*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.PropagateActivity
  id: PropagateActivity
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  langs:
  - csharp
  name: PropagateActivity
  nameWithType: EndToEndTracingElement.PropagateActivity
  fullName: System.ServiceModel.Configuration.EndToEndTracingElement.PropagateActivity
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "伝達属性に設定されているかどうかを示す値を取得<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>です。"
  syntax:
    content: public bool PropagateActivity { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>propagate アクティビティの属性に設定されている場合<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>、それ以外の<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>です。"
  overload: System.ServiceModel.Configuration.EndToEndTracingElement.PropagateActivity*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  langs:
  - csharp
  name: Properties
  nameWithType: EndToEndTracingElement.Properties
  fullName: System.ServiceModel.Configuration.EndToEndTracingElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "追加します。"
  overload: System.ServiceModel.Configuration.EndToEndTracingElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.#ctor
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  isExternal: false
  name: EndToEndTracingElement()
  nameWithType: EndToEndTracingElement.EndToEndTracingElement()
  fullName: System.ServiceModel.Configuration.EndToEndTracingElement.EndToEndTracingElement()
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.ActivityTracing
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  isExternal: false
  name: ActivityTracing
  nameWithType: EndToEndTracingElement.ActivityTracing
  fullName: System.ServiceModel.Configuration.EndToEndTracingElement.ActivityTracing
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.MessageFlowTracing
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  isExternal: false
  name: MessageFlowTracing
  nameWithType: EndToEndTracingElement.MessageFlowTracing
  fullName: System.ServiceModel.Configuration.EndToEndTracingElement.MessageFlowTracing
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.PropagateActivity
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  isExternal: false
  name: PropagateActivity
  nameWithType: EndToEndTracingElement.PropagateActivity
  fullName: System.ServiceModel.Configuration.EndToEndTracingElement.PropagateActivity
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.Properties
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  isExternal: false
  name: Properties
  nameWithType: EndToEndTracingElement.Properties
  fullName: System.ServiceModel.Configuration.EndToEndTracingElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.#ctor*
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  isExternal: false
  name: EndToEndTracingElement
  nameWithType: EndToEndTracingElement.EndToEndTracingElement
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.ActivityTracing*
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  isExternal: false
  name: ActivityTracing
  nameWithType: EndToEndTracingElement.ActivityTracing
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.MessageFlowTracing*
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  isExternal: false
  name: MessageFlowTracing
  nameWithType: EndToEndTracingElement.MessageFlowTracing
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.PropagateActivity*
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  isExternal: false
  name: PropagateActivity
  nameWithType: EndToEndTracingElement.PropagateActivity
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.Properties*
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  isExternal: false
  name: Properties
  nameWithType: EndToEndTracingElement.Properties
