### YamlMime:ManagedReference
items:
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute
  id: PositiveTimeSpanValidatorAttribute
  children:
  - System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor
  - System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: PositiveTimeSpanValidatorAttribute
  nameWithType: PositiveTimeSpanValidatorAttribute
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute
  type: Class
  summary: "宣言によって構成プロパティの時間検証の実行に .NET Framework に指示します。 このクラスは継承できません。"
  remarks: "構成プロパティを修飾するのにには、PositiveTimeSpanValidatorAttribute 属性を使用します。 これは、ポリシーでは、.NET Framework を使用してプロパティを検証する、<xref:System.Configuration.PositiveTimeSpanValidator>オブジェクトし、装飾のパラメーターの値を渡す</xref:System.Configuration.PositiveTimeSpanValidator>。       PositiveTimeSpanValidatorAttribute オブジェクトは、プロパティの型にのみ適用できます。"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class PositiveTimeSpanValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net462
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  langs:
  - csharp
  name: PositiveTimeSpanValidatorAttribute()
  nameWithType: PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute()
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Configuration.PositiveTimeSpanValidatorAttribute&quot;> </xref>クラスです。"
  remarks: "属性付きのモデルでこのコンス トラクターを使用して関連するプロパティに割り当てられている値の型が正であることを確認する<xref:System.TimeSpan>オブジェクト</xref:System.TimeSpan>。"
  syntax:
    content: public PositiveTimeSpanValidatorAttribute ();
    parameters: []
  overload: System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: PositiveTimeSpanValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "インスタンスを取得、 <xref href=&quot;System.Configuration.PositiveTimeSpanValidator&quot;> </xref>クラスです。"
  remarks: "正の値を実行する ValidatorInstance プロパティを使用する<xref:System.TimeSpan>検証を呼び出すことによってオブジェクト、<xref:System.Configuration.PositiveTimeSpanValidator.Validate%2A?displayProperty=fullName>メソッド</xref:System.Configuration.PositiveTimeSpanValidator.Validate%2A?displayProperty=fullName></xref:System.TimeSpan>。"
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "<xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref>バリデーターのインスタンス。"
  overload: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  isExternal: false
  name: PositiveTimeSpanValidatorAttribute()
  nameWithType: PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute()
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute()
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: PositiveTimeSpanValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor*
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  isExternal: false
  name: PositiveTimeSpanValidatorAttribute
  nameWithType: PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: PositiveTimeSpanValidatorAttribute.ValidatorInstance
