### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost
  id: IInternalConfigWebHost
  children:
  - System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(System.String,System.String)
  - System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(System.String,System.String@,System.String@)
  langs:
  - csharp
  name: IInternalConfigWebHost
  nameWithType: IInternalConfigWebHost
  fullName: System.Web.Configuration.Internal.IInternalConfigWebHost
  type: Interface
  summary: "アクセスし、ホストの構成ファイルを操作するために、内部の .NET Framework インフラストラクチャによって使用されるインターフェイスを定義します。"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IInternalConfigWebHost
  implements: []
  platform:
  - net462
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(System.String,System.String)
  id: GetConfigPathFromSiteIDAndVPath(System.String,System.String)
  parent: System.Web.Configuration.Internal.IInternalConfigWebHost
  langs:
  - csharp
  name: GetConfigPathFromSiteIDAndVPath(String,String)
  nameWithType: IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(String,String)
  fullName: System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration.Internal
  summary: "指定されたサイト id とアプリケーションの仮想パスに関連付けられている構成ファイルへのパスを表す値を返します。"
  syntax:
    content: public string GetConfigPathFromSiteIDAndVPath (string siteID, string vpath);
    parameters:
    - id: siteID
      type: System.String
      description: "アプリケーションのサイトの識別子です。 詳細については、ASP.NET の構成の概要を参照してください。"
    - id: vpath
      type: System.String
      description: "文字列として、アプリケーションの仮想パス。 詳細については、ASP.NET Web サイトのパスを参照してください。"
    return:
      type: System.String
      description: "構成ファイルへのパスを表す文字列。"
  overload: System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(System.String,System.String@,System.String@)
  id: GetSiteIDAndVPathFromConfigPath(System.String,System.String@,System.String@)
  parent: System.Web.Configuration.Internal.IInternalConfigWebHost
  langs:
  - csharp
  name: GetSiteIDAndVPathFromConfigPath(String,String,String)
  nameWithType: IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(String,String,String)
  fullName: System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(String,String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration.Internal
  summary: "アプリケーションの仮想パスおよびアプリケーションの構成パスに基づく構成オブジェクトの現在のサイト id を設定します。"
  syntax:
    content: public void GetSiteIDAndVPathFromConfigPath (string configPath, out string siteID, out string vpath);
    parameters:
    - id: configPath
      type: System.String
      description: "アプリケーションの構成ファイルへのパスを表す文字列。"
    - id: siteID
      type: System.String
      description: "アプリケーションのサイトの識別子。 詳細については、ASP.NET の構成の概要を参照してください。"
    - id: vpath
      type: System.String
      description: "文字列として、アプリケーションの仮想パス。 詳細については、ASP.NET Web サイトのパスを参照してください。"
  overload: System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(System.String,System.String)
  parent: System.Web.Configuration.Internal.IInternalConfigWebHost
  isExternal: false
  name: GetConfigPathFromSiteIDAndVPath(String,String)
  nameWithType: IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(String,String)
  fullName: System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(System.String,System.String@,System.String@)
  parent: System.Web.Configuration.Internal.IInternalConfigWebHost
  isExternal: false
  name: GetSiteIDAndVPathFromConfigPath(String,String,String)
  nameWithType: IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(String,String,String)
  fullName: System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath(String,String,String)
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath*
  parent: System.Web.Configuration.Internal.IInternalConfigWebHost
  isExternal: false
  name: GetConfigPathFromSiteIDAndVPath
  nameWithType: IInternalConfigWebHost.GetConfigPathFromSiteIDAndVPath
- uid: System.Web.Configuration.Internal.IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath*
  parent: System.Web.Configuration.Internal.IInternalConfigWebHost
  isExternal: false
  name: GetSiteIDAndVPathFromConfigPath
  nameWithType: IInternalConfigWebHost.GetSiteIDAndVPathFromConfigPath
