### YamlMime:ManagedReference
items:
- uid: System.Windows.Converters.Int32RectValueSerializer
  id: Int32RectValueSerializer
  children:
  - System.Windows.Converters.Int32RectValueSerializer.#ctor
  - System.Windows.Converters.Int32RectValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Converters.Int32RectValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Converters.Int32RectValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Converters.Int32RectValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: Int32RectValueSerializer
  nameWithType: Int32RectValueSerializer
  fullName: System.Windows.Converters.Int32RectValueSerializer
  type: Class
  summary: "インスタンスに変換します<xref:System.String>のインスタンスと<xref href=&quot;System.Windows.Int32Rect&quot;> </xref></xref:System.String> 。"
  remarks: "このクラスは、通常のみで使用される、<xref:System.Windows.Markup.Primitives.MarkupWriter>シリアル化のためです</xref:System.Windows.Markup.Primitives.MarkupWriter>。      <a name=&quot;xamlTextUsage_Int32RectValueSerializer&quot;></a>## XAML テキストの使用方法"
  syntax:
    content: 'public class Int32RectValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Windows.Converters.Int32RectValueSerializer.#ctor
  id: '#ctor'
  parent: System.Windows.Converters.Int32RectValueSerializer
  langs:
  - csharp
  name: Int32RectValueSerializer()
  nameWithType: Int32RectValueSerializer.Int32RectValueSerializer()
  fullName: System.Windows.Converters.Int32RectValueSerializer.Int32RectValueSerializer()
  type: Constructor
  assemblies:
  - WindowsBase
  namespace: System.Windows.Converters
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Windows.Converters.Int32RectValueSerializer&quot;> </xref>クラスです。"
  syntax:
    content: public Int32RectValueSerializer ();
    parameters: []
  overload: System.Windows.Converters.Int32RectValueSerializer.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Converters.Int32RectValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Converters.Int32RectValueSerializer
  langs:
  - csharp
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: Int32RectValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Converters.Int32RectValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - WindowsBase
  namespace: System.Windows.Converters
  summary: "決定するかどうか、指定した<xref:System.String>のインスタンスに変換できる<xref href=&quot;System.Windows.Int32Rect&quot;> </xref></xref:System.String> 。"
  syntax:
    content: public override bool CanConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "変換の評価する文字列。"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "変換に使用されるコンテキスト情報。"
    return:
      type: System.Boolean
      description: "常に返します<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>です。"
  overload: System.Windows.Converters.Int32RectValueSerializer.CanConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Converters.Int32RectValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Converters.Int32RectValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: Int32RectValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Converters.Int32RectValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - WindowsBase
  namespace: System.Windows.Converters
  summary: "指定するかどうか、指定した<xref href=&quot;System.Windows.Int32Rect&quot;> </xref> <xref:System.String>.</xref:System.String>を変換することができます"
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "変換の評価対象のオブジェクト。"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "変換に使用されるコンテキスト情報。"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>場合<code> value </code>に変換できる、 <xref:System.String>、それ以外の<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref></xref:System.String> 。"
  overload: System.Windows.Converters.Int32RectValueSerializer.CanConvertToString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Converters.Int32RectValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Converters.Int32RectValueSerializer
  langs:
  - csharp
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: Int32RectValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Converters.Int32RectValueSerializer.ConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - WindowsBase
  namespace: System.Windows.Converters
  summary: "変換、<xref:System.String>に、 <xref href=&quot;System.Windows.Int32Rect&quot;> </xref></xref:System.String> 。"
  remarks: "実装を使用して<xref:System.Windows.Int32Rect.Parse%2A?displayProperty=fullName>内部的にします</xref:System.Windows.Int32Rect.Parse%2A?displayProperty=fullName>。"
  syntax:
    content: public override object ConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "変換する文字列。"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "変換に使用されるコンテキスト情報。"
    return:
      type: System.Object
      description: "新しいインスタンスを<xref href=&quot;System.Windows.Int32Rect&quot;></xref>に基づいて、指定された<code> value</code>です。"
  overload: System.Windows.Converters.Int32RectValueSerializer.ConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Converters.Int32RectValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Converters.Int32RectValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: Int32RectValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Converters.Int32RectValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - WindowsBase
  namespace: System.Windows.Converters
  summary: "インスタンスに変換します<xref href=&quot;System.Windows.Int32Rect&quot;> </xref> <xref:System.String></xref:System.String> 。"
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "文字列に変換するオブジェクト。"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "変換に使用されるコンテキスト情報。"
    return:
      type: System.String
      description: "指定した文字列形式<xref href=&quot;System.Windows.Int32Rect&quot;></xref>です。"
  overload: System.Windows.Converters.Int32RectValueSerializer.ConvertToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.Windows.Converters.Int32RectValueSerializer.#ctor
  parent: System.Windows.Converters.Int32RectValueSerializer
  isExternal: false
  name: Int32RectValueSerializer()
  nameWithType: Int32RectValueSerializer.Int32RectValueSerializer()
  fullName: System.Windows.Converters.Int32RectValueSerializer.Int32RectValueSerializer()
- uid: System.Windows.Converters.Int32RectValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Converters.Int32RectValueSerializer
  isExternal: false
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: Int32RectValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Converters.Int32RectValueSerializer.CanConvertFromString(String,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Converters.Int32RectValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Converters.Int32RectValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: Int32RectValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Converters.Int32RectValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Converters.Int32RectValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Converters.Int32RectValueSerializer
  isExternal: false
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: Int32RectValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Converters.Int32RectValueSerializer.ConvertFromString(String,IValueSerializerContext)
- uid: System.Windows.Converters.Int32RectValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Converters.Int32RectValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: Int32RectValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Converters.Int32RectValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.Windows.Converters.Int32RectValueSerializer.#ctor*
  parent: System.Windows.Converters.Int32RectValueSerializer
  isExternal: false
  name: Int32RectValueSerializer
  nameWithType: Int32RectValueSerializer.Int32RectValueSerializer
- uid: System.Windows.Converters.Int32RectValueSerializer.CanConvertFromString*
  parent: System.Windows.Converters.Int32RectValueSerializer
  isExternal: false
  name: CanConvertFromString
  nameWithType: Int32RectValueSerializer.CanConvertFromString
- uid: System.Windows.Converters.Int32RectValueSerializer.CanConvertToString*
  parent: System.Windows.Converters.Int32RectValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: Int32RectValueSerializer.CanConvertToString
- uid: System.Windows.Converters.Int32RectValueSerializer.ConvertFromString*
  parent: System.Windows.Converters.Int32RectValueSerializer
  isExternal: false
  name: ConvertFromString
  nameWithType: Int32RectValueSerializer.ConvertFromString
- uid: System.Windows.Converters.Int32RectValueSerializer.ConvertToString*
  parent: System.Windows.Converters.Int32RectValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: Int32RectValueSerializer.ConvertToString
