### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Discovery.UdpTransportSettings
  id: UdpTransportSettings
  children:
  - System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength
  - System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize
  - System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount
  - System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount
  - System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize
  - System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount
  - System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId
  - System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize
  - System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive
  langs:
  - csharp
  name: UdpTransportSettings
  nameWithType: UdpTransportSettings
  fullName: System.ServiceModel.Discovery.UdpTransportSettings
  type: Class
  summary: "UDP トランスポート設定を設定できます。"
  syntax:
    content: public class UdpTransportSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength
  id: DuplicateMessageHistoryLength
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: DuplicateMessageHistoryLength
  nameWithType: UdpTransportSettings.DuplicateMessageHistoryLength
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "取得または重複メッセージを識別するためにトランスポートによって使用されるメッセージ ハッシュの最大数を指定する値を設定します。"
  remarks: "このプロパティは、システム管理者および開発者にも重複するメッセージの検出アルゴリズムをオフにする方法を示します。 この値を 0 に設定すると、重複するメッセージの検出が無効にします。 既定値は 4112 です。"
  syntax:
    content: public int DuplicateMessageHistoryLength { get; set; }
    return:
      type: System.Int32
      description: "使用するメッセージ ハッシュの最大数。"
  overload: System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize
  id: MaxBufferPoolSize
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: MaxBufferPoolSize
  nameWithType: UdpTransportSettings.MaxBufferPoolSize
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "取得または (バイト単位)、トランスポートによって使用されるバッファー プールの最大サイズを設定します。"
  syntax:
    content: public long MaxBufferPoolSize { get; set; }
    return:
      type: System.Int64
      description: "最大バッファー プール サイズ。"
  overload: System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount
  id: MaxMulticastRetransmitCount
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: MaxMulticastRetransmitCount
  nameWithType: UdpTransportSettings.MaxMulticastRetransmitCount
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "取得または (最初の送信) だけでなく、マルチキャスト メッセージを再送信する最大回数を指定する値を設定します。"
  remarks: "既定値は 2 です。"
  syntax:
    content: public int MaxMulticastRetransmitCount { get; set; }
    return:
      type: System.Int32
      description: "マルチキャストのメッセージが再送信される最大回数。"
  overload: System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount
  id: MaxPendingMessageCount
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: MaxPendingMessageCount
  nameWithType: UdpTransportSettings.MaxPendingMessageCount
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "取得または受信したものの、各チャネル インスタンスの入力キューから削除されていないメッセージの最大数を指定する値を設定します。"
  remarks: "入力キューが、保留中のメッセージ数の上限に達すると、メッセージは削除されます。 既定値は 32 です。"
  syntax:
    content: public int MaxPendingMessageCount { get; set; }
    return:
      type: System.Int32
      description: "メッセージの数。"
  overload: System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize
  id: MaxReceivedMessageSize
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: MaxReceivedMessageSize
  nameWithType: UdpTransportSettings.MaxReceivedMessageSize
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "取得または、バインディングにより処理可能なメッセージのバイト単位で最大のサイズを設定します。"
  remarks: "既定値は 65507 です。"
  syntax:
    content: public long MaxReceivedMessageSize { get; set; }
    return:
      type: System.Int64
      description: "メッセージの最大サイズ。"
  overload: System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount
  id: MaxUnicastRetransmitCount
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: MaxUnicastRetransmitCount
  nameWithType: UdpTransportSettings.MaxUnicastRetransmitCount
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "取得またはユニキャスト メッセージを (最初の送信) だけでなく再送信する最大回数を指定する値を設定します。"
  remarks: "既定値は 1 です。"
  syntax:
    content: public int MaxUnicastRetransmitCount { get; set; }
    return:
      type: System.Int32
      description: "ユニキャスト メッセージが再送信される最大回数。"
  overload: System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId
  id: MulticastInterfaceId
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: MulticastInterfaceId
  nameWithType: UdpTransportSettings.MulticastInterfaceId
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "取得またはマルチキャストのメッセージを送受信するときに使用されるネットワーク アダプターを一意に識別する値を設定します。"
  remarks: "トランスポートは、実行時に、設定を使用して、インターフェイスのインデックスを検索する値を使用して、`IP_MULTICAST_IF`と`IPV6_MULTICAST_IF`ソケット オプション。 マルチキャスト グループに参加させる、同じインターフェイス インデックスが使用されます。 既定値は `null` です。"
  syntax:
    content: public string MulticastInterfaceId { get; set; }
    return:
      type: System.String
      description: "ネットワーク アダプター識別子。"
  overload: System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize
  id: SocketReceiveBufferSize
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: SocketReceiveBufferSize
  nameWithType: UdpTransportSettings.SocketReceiveBufferSize
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "取得または基になる WinSock ソケットの受信バッファー サイズを設定します。"
  remarks: "受信チャネルのユーザーは、バインディングのこの値を使用して、システムでのデータを受信したときの動作方法を制御します。 たとえばにアクセスするアプリケーションを指定受信[!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)]より高い値を使用して、最大しきい値でのメッセージがメッセージにそれを処理するアプリケーションの待機中に、WinSock バッファーにスタックを許可します。 同じ状況で低い値を使用すると、メッセージが破棄されるが起こる可能性があります。 このプロパティを公開、基になる WinSock`SO_RCVBUF`ソケット設定します。 このプロパティの値が、少なくとも<xref:System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize%2A>。</xref:System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize%2A>のサイズである必要があります。 も小さい値に設定する、<xref:System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize%2A>でランタイム例外が発生します</xref:System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize%2A>。 既定値は 65536 です。"
  syntax:
    content: public int SocketReceiveBufferSize { get; set; }
    return:
      type: System.Int32
      description: "受信バッファー サイズ。"
  overload: System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive
  id: TimeToLive
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: TimeToLive
  nameWithType: UdpTransportSettings.TimeToLive
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "取得またはマルチキャスト パケットが走査できるネットワーク セグメント ホップの数を指定する値を設定します。"
  remarks: "このプロパティに関連付けられている機能を公開する、`IP_MULTICAST_TTL`と`IP_TTL`ソケット オプション。 既定値は 1 です。"
  syntax:
    content: public int TimeToLive { get; set; }
    return:
      type: System.Int32
      description: "ネットワーク セグメント ホップの数。"
  overload: System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: DuplicateMessageHistoryLength
  nameWithType: UdpTransportSettings.DuplicateMessageHistoryLength
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxBufferPoolSize
  nameWithType: UdpTransportSettings.MaxBufferPoolSize
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxMulticastRetransmitCount
  nameWithType: UdpTransportSettings.MaxMulticastRetransmitCount
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxPendingMessageCount
  nameWithType: UdpTransportSettings.MaxPendingMessageCount
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxReceivedMessageSize
  nameWithType: UdpTransportSettings.MaxReceivedMessageSize
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxUnicastRetransmitCount
  nameWithType: UdpTransportSettings.MaxUnicastRetransmitCount
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MulticastInterfaceId
  nameWithType: UdpTransportSettings.MulticastInterfaceId
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: SocketReceiveBufferSize
  nameWithType: UdpTransportSettings.SocketReceiveBufferSize
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize
- uid: System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: TimeToLive
  nameWithType: UdpTransportSettings.TimeToLive
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive
- uid: System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: DuplicateMessageHistoryLength
  nameWithType: UdpTransportSettings.DuplicateMessageHistoryLength
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxBufferPoolSize
  nameWithType: UdpTransportSettings.MaxBufferPoolSize
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxMulticastRetransmitCount
  nameWithType: UdpTransportSettings.MaxMulticastRetransmitCount
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxPendingMessageCount
  nameWithType: UdpTransportSettings.MaxPendingMessageCount
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxReceivedMessageSize
  nameWithType: UdpTransportSettings.MaxReceivedMessageSize
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxUnicastRetransmitCount
  nameWithType: UdpTransportSettings.MaxUnicastRetransmitCount
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MulticastInterfaceId
  nameWithType: UdpTransportSettings.MulticastInterfaceId
- uid: System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: SocketReceiveBufferSize
  nameWithType: UdpTransportSettings.SocketReceiveBufferSize
- uid: System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: TimeToLive
  nameWithType: UdpTransportSettings.TimeToLive
