### YamlMime:ManagedReference
items:
- uid: System.Configuration.SingleTagSectionHandler
  id: SingleTagSectionHandler
  children:
  - System.Configuration.SingleTagSectionHandler.#ctor
  - System.Configuration.SingleTagSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: SingleTagSectionHandler
  nameWithType: SingleTagSectionHandler
  fullName: System.Configuration.SingleTagSectionHandler
  type: Class
  summary: ".Config ファイルで&1; つの XML タグで表される構成セクションを処理します。"
  syntax:
    content: 'public class SingleTagSectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SingleTagSectionHandler.#ctor
  id: '#ctor'
  parent: System.Configuration.SingleTagSectionHandler
  langs:
  - csharp
  name: SingleTagSectionHandler()
  nameWithType: SingleTagSectionHandler.SingleTagSectionHandler()
  fullName: System.Configuration.SingleTagSectionHandler.SingleTagSectionHandler()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Configuration.SingleTagSectionHandler&quot;> </xref>クラスです。"
  syntax:
    content: public SingleTagSectionHandler ();
    parameters: []
  overload: System.Configuration.SingleTagSectionHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SingleTagSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.SingleTagSectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: SingleTagSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.SingleTagSectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "このオブジェクトの新しいインスタンスを作成するには、内部的に使用します。"
  syntax:
    content: public virtual object Create (object parent, object context, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "このオブジェクトの親です。"
    - id: context
      type: System.Object
      description: "このオブジェクトのコンテキスト。"
    - id: section
      type: System.Xml.XmlNode
      description: "<xref href=&quot;System.Xml.XmlNode&quot;> </xref>構成内のオブジェクト。"
    return:
      type: System.Object
      description: "作成されたオブジェクト ハンドラー。"
  overload: System.Configuration.SingleTagSectionHandler.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.SingleTagSectionHandler.#ctor
  parent: System.Configuration.SingleTagSectionHandler
  isExternal: false
  name: SingleTagSectionHandler()
  nameWithType: SingleTagSectionHandler.SingleTagSectionHandler()
  fullName: System.Configuration.SingleTagSectionHandler.SingleTagSectionHandler()
- uid: System.Configuration.SingleTagSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.SingleTagSectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: SingleTagSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.SingleTagSectionHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.SingleTagSectionHandler.#ctor*
  parent: System.Configuration.SingleTagSectionHandler
  isExternal: false
  name: SingleTagSectionHandler
  nameWithType: SingleTagSectionHandler.SingleTagSectionHandler
- uid: System.Configuration.SingleTagSectionHandler.Create*
  parent: System.Configuration.SingleTagSectionHandler
  isExternal: false
  name: Create
  nameWithType: SingleTagSectionHandler.Create
