### YamlMime:ManagedReference
items:
- uid: System.Windows.Input.KeyGestureValueSerializer
  id: KeyGestureValueSerializer
  children:
  - System.Windows.Input.KeyGestureValueSerializer.#ctor
  - System.Windows.Input.KeyGestureValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Input.KeyGestureValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Input.KeyGestureValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Input.KeyGestureValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: KeyGestureValueSerializer
  nameWithType: KeyGestureValueSerializer
  fullName: System.Windows.Input.KeyGestureValueSerializer
  type: Class
  summary: "インスタンスに変換します<xref:System.String>のインスタンスと<xref href=&quot;System.Windows.Input.KeyGesture&quot;> </xref></xref:System.String> 。"
  remarks: "このクラスは、通常のみで使用される、<xref:System.Windows.Markup.Primitives.MarkupWriter>シリアル化のためです</xref:System.Windows.Markup.Primitives.MarkupWriter>。      <a name=&quot;xamlTextUsage_KeyGestureValueSerializer&quot;></a>## XAML テキストの使用方法"
  syntax:
    content: 'public class KeyGestureValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Windows.Input.KeyGestureValueSerializer.#ctor
  id: '#ctor'
  parent: System.Windows.Input.KeyGestureValueSerializer
  langs:
  - csharp
  name: KeyGestureValueSerializer()
  nameWithType: KeyGestureValueSerializer.KeyGestureValueSerializer()
  fullName: System.Windows.Input.KeyGestureValueSerializer.KeyGestureValueSerializer()
  type: Constructor
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Windows.Input.KeyGestureValueSerializer&quot;> </xref>クラスです。"
  syntax:
    content: public KeyGestureValueSerializer ();
    parameters: []
  overload: System.Windows.Input.KeyGestureValueSerializer.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.KeyGestureValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.KeyGestureValueSerializer
  langs:
  - csharp
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: KeyGestureValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.KeyGestureValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "かどうかを指定した<xref:System.String>のインスタンスに変換できる<xref href=&quot;System.Windows.Input.KeyGesture&quot;> </xref></xref:System.String> 。"
  syntax:
    content: public override bool CanConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "変換の評価する文字列。"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "変換に使用されるコンテキスト情報。"
    return:
      type: System.Boolean
      description: "常に返します<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>です。"
  overload: System.Windows.Input.KeyGestureValueSerializer.CanConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.KeyGestureValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.KeyGestureValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: KeyGestureValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.KeyGestureValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "かどうかを指定した<xref href=&quot;System.Windows.Input.KeyGesture&quot;> </xref> <xref:System.String>.</xref:System.String>に変換できます"
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "変換の評価対象ジェスチャ。"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "変換に使用されるコンテキスト情報。"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>場合<code> value </code>に変換できる、 <xref:System.String>、それ以外の<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref></xref:System.String> 。"
  overload: System.Windows.Input.KeyGestureValueSerializer.CanConvertToString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.KeyGestureValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.KeyGestureValueSerializer
  langs:
  - csharp
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: KeyGestureValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.KeyGestureValueSerializer.ConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "変換、<xref:System.String>に、 <xref href=&quot;System.Windows.Input.KeyGesture&quot;> </xref></xref:System.String> 。"
  syntax:
    content: public override object ConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "変換する文字列、 <xref href=&quot;System.Windows.Input.KeyGesture&quot;></xref>です。"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "変換に使用されるコンテキスト情報。"
    return:
      type: System.Object
      description: "新しいインスタンスを<xref href=&quot;System.Windows.Input.KeyGesture&quot;></xref>に基づいて、指定された<code> value</code>です。"
  overload: System.Windows.Input.KeyGestureValueSerializer.ConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.KeyGestureValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.KeyGestureValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: KeyGestureValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.KeyGestureValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "インスタンスに変換します<xref href=&quot;System.Windows.Input.KeyGesture&quot;> </xref> <xref:System.String></xref:System.String> 。"
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "文字列に変換するジェスチャ。"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "変換に使用されるコンテキスト情報。"
    return:
      type: System.String
      description: "指定した、不変の文字列表現<xref href=&quot;System.Windows.Input.KeyGesture&quot;></xref>です。"
  overload: System.Windows.Input.KeyGestureValueSerializer.ConvertToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.Windows.Input.KeyGestureValueSerializer.#ctor
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: KeyGestureValueSerializer()
  nameWithType: KeyGestureValueSerializer.KeyGestureValueSerializer()
  fullName: System.Windows.Input.KeyGestureValueSerializer.KeyGestureValueSerializer()
- uid: System.Windows.Input.KeyGestureValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: KeyGestureValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.KeyGestureValueSerializer.CanConvertFromString(String,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Input.KeyGestureValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: KeyGestureValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.KeyGestureValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Input.KeyGestureValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: KeyGestureValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.KeyGestureValueSerializer.ConvertFromString(String,IValueSerializerContext)
- uid: System.Windows.Input.KeyGestureValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: KeyGestureValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.KeyGestureValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.Windows.Input.KeyGestureValueSerializer.#ctor*
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: KeyGestureValueSerializer
  nameWithType: KeyGestureValueSerializer.KeyGestureValueSerializer
- uid: System.Windows.Input.KeyGestureValueSerializer.CanConvertFromString*
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: CanConvertFromString
  nameWithType: KeyGestureValueSerializer.CanConvertFromString
- uid: System.Windows.Input.KeyGestureValueSerializer.CanConvertToString*
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: KeyGestureValueSerializer.CanConvertToString
- uid: System.Windows.Input.KeyGestureValueSerializer.ConvertFromString*
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: ConvertFromString
  nameWithType: KeyGestureValueSerializer.ConvertFromString
- uid: System.Windows.Input.KeyGestureValueSerializer.ConvertToString*
  parent: System.Windows.Input.KeyGestureValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: KeyGestureValueSerializer.ConvertToString
