### YamlMime:ManagedReference
items:
- uid: System.Transactions.Configuration.DefaultSettingsSection
  id: DefaultSettingsSection
  children:
  - System.Transactions.Configuration.DefaultSettingsSection.#ctor
  - System.Transactions.Configuration.DefaultSettingsSection.DistributedTransactionManagerName
  - System.Transactions.Configuration.DefaultSettingsSection.Properties
  - System.Transactions.Configuration.DefaultSettingsSection.Timeout
  langs:
  - csharp
  name: DefaultSettingsSection
  nameWithType: DefaultSettingsSection
  fullName: System.Transactions.Configuration.DefaultSettingsSection
  type: Class
  summary: "トランザクションの既定値を含む構成ファイルの XML セクションを表します。 このクラスは継承できません。"
  remarks: ''
  example:
  - "An example configuration file used by your transaction application can be as follows,  \n  \n `<configuration>`  \n  \n `<system.transactions>`  \n  \n `<defaultSettings distributedTransactionManagerName=\"F04M25\" timeout=\"02:00:00\"/>`  \n  \n `<machineSettings maxTimeout=\"02:00:00\"/>`  \n  \n `</system.transactions>`  \n  \n `</configuration>`  \n  \n This example specifies the default values of a transaction. Specifically, it sets the the computer name of the Distributed Transaction Coordinator (MSDTC) that is responsible for coordinating all distributed transactions started locally, and the default time after which a transaction times out. In addition, it specifies a setting that can only be modified at the machine level, which is the maximum amount of time allowed before a transaction times out."
  syntax:
    content: 'public sealed class DefaultSettingsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Transactions.Configuration.DefaultSettingsSection.#ctor
  id: '#ctor'
  parent: System.Transactions.Configuration.DefaultSettingsSection
  langs:
  - csharp
  name: DefaultSettingsSection()
  nameWithType: DefaultSettingsSection.DefaultSettingsSection()
  fullName: System.Transactions.Configuration.DefaultSettingsSection.DefaultSettingsSection()
  type: Constructor
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Transactions.Configuration.DefaultSettingsSection&quot;> </xref>クラスです。"
  syntax:
    content: public DefaultSettingsSection ();
    parameters: []
  overload: System.Transactions.Configuration.DefaultSettingsSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Transactions.Configuration.DefaultSettingsSection.DistributedTransactionManagerName
  id: DistributedTransactionManagerName
  parent: System.Transactions.Configuration.DefaultSettingsSection
  langs:
  - csharp
  name: DistributedTransactionManagerName
  nameWithType: DefaultSettingsSection.DistributedTransactionManagerName
  fullName: System.Transactions.Configuration.DefaultSettingsSection.DistributedTransactionManagerName
  type: Property
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  summary: "トランザクション マネージャーの名前を取得します。"
  remarks: "このプロパティには、Microsoft 分散トランザクション コーディネーター (MSDTC) を実行しているし、は、ローカルで開始されるすべての分散トランザクションをコーディネートを担当するコンピューターの名前が含まれています。       <xref:System.Transactions>。</xref:System.Transactions> リモートのトランザクション マネージャーを有効にするには、このプロパティの値を設定することができます。 場合は、このプロパティは`null`または空の文字列が含まれているローカル トランザクション マネージャーは、リモート トランザクション マネージャーとして使用します。 このプロパティを既定の空の文字列以外の値を設定する場合は、Windows Server 2003 Service Pack 1 をインストールする必要があります。 <xref:System.NotSupportedException>。</xref:System.NotSupportedException>トランザクション操作が失敗した場合は、 トランザクションは MSDTC によって管理されるエスカレートはローカルの MSDTC は使用されませんが、代わりにこのプロパティによって指定されたコンピューターで&1; つを使用します。 そのトランザクション マネージャーが使用できないなんらかの理由で例外がスローされます。       このプロパティは、大文字小文字を区別は、コンピューターの短い名前のみを含める必要があります。  完全修飾ドメイン名、localhost、または IP アドレスは受け入れられません。 このプロパティに無効なリモート コンピューター名が含まれている場合、「構成情報を読み取れません。」例外がスローされます。       リモートの MSDTC を使用する適切なセキュリティ アクセス許可が必要です。 DTC セキュリティ設定を構成する方法の詳細についてを参照してください、 [MSDTC の構成のセキュリティ プロパティ](http://msdn.microsoft.com/library/cossdk/html/2627a956-60b3-4d26-bc04-e0676ec97786.asp?frame=true)トピックです。"
  syntax:
    content: public string DistributedTransactionManagerName { get; set; }
    return:
      type: System.String
      description: "トランザクション マネージャーの名前です。 既定値は、空の文字列です。"
  overload: System.Transactions.Configuration.DefaultSettingsSection.DistributedTransactionManagerName*
  exceptions:
  - type: System.NotSupportedException
    commentId: T:System.NotSupportedException
    description: "完全修飾ドメイン名または IP アドレスにこのプロパティを設定しようとしました。"
  - type: System.Transactions.TransactionAbortedException
    commentId: T:System.Transactions.TransactionAbortedException
    description: "このプロパティを localhost に設定しようとしました。"
  platform:
  - net462
- uid: System.Transactions.Configuration.DefaultSettingsSection.Properties
  id: Properties
  parent: System.Transactions.Configuration.DefaultSettingsSection
  langs:
  - csharp
  name: Properties
  nameWithType: DefaultSettingsSection.Properties
  fullName: System.Transactions.Configuration.DefaultSettingsSection.Properties
  type: Property
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "追加します。"
  overload: System.Transactions.Configuration.DefaultSettingsSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Transactions.Configuration.DefaultSettingsSection.Timeout
  id: Timeout
  parent: System.Transactions.Configuration.DefaultSettingsSection
  langs:
  - csharp
  name: Timeout
  nameWithType: DefaultSettingsSection.Timeout
  fullName: System.Transactions.Configuration.DefaultSettingsSection.Timeout
  type: Property
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  summary: "取得またはトランザクションがタイムアウトするまで既定の時間を設定します。"
  remarks: "このプロパティは、構成ファイルに既定のタイムアウト値からその値を取得します。 によって自動的に調整、<xref:System.Transactions.Configuration.MachineSettingsSection.MaxTimeout%2A>値は実行時</xref:System.Transactions.Configuration.MachineSettingsSection.MaxTimeout%2A>。       00時 00分: 00 (またはゼロ) の値は、無限大として解釈されます。"
  syntax:
    content: public TimeSpan Timeout { get; set; }
    return:
      type: System.TimeSpan
      description: "A<xref:System.TimeSpan>オブジェクト</xref:System.TimeSpan>。 既定のプロパティは、00時 01分: 00 です。"
  overload: System.Transactions.Configuration.DefaultSettingsSection.Timeout*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "このプロパティを負の値に設定しようとしました。"
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.NotSupportedException
  isExternal: true
  name: System.NotSupportedException
- uid: System.Transactions.TransactionAbortedException
  parent: System.Transactions
  isExternal: false
  name: TransactionAbortedException
  nameWithType: TransactionAbortedException
  fullName: System.Transactions.TransactionAbortedException
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.Transactions.Configuration.DefaultSettingsSection.#ctor
  parent: System.Transactions.Configuration.DefaultSettingsSection
  isExternal: false
  name: DefaultSettingsSection()
  nameWithType: DefaultSettingsSection.DefaultSettingsSection()
  fullName: System.Transactions.Configuration.DefaultSettingsSection.DefaultSettingsSection()
- uid: System.Transactions.Configuration.DefaultSettingsSection.DistributedTransactionManagerName
  parent: System.Transactions.Configuration.DefaultSettingsSection
  isExternal: false
  name: DistributedTransactionManagerName
  nameWithType: DefaultSettingsSection.DistributedTransactionManagerName
  fullName: System.Transactions.Configuration.DefaultSettingsSection.DistributedTransactionManagerName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Transactions.Configuration.DefaultSettingsSection.Properties
  parent: System.Transactions.Configuration.DefaultSettingsSection
  isExternal: false
  name: Properties
  nameWithType: DefaultSettingsSection.Properties
  fullName: System.Transactions.Configuration.DefaultSettingsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Transactions.Configuration.DefaultSettingsSection.Timeout
  parent: System.Transactions.Configuration.DefaultSettingsSection
  isExternal: false
  name: Timeout
  nameWithType: DefaultSettingsSection.Timeout
  fullName: System.Transactions.Configuration.DefaultSettingsSection.Timeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Transactions.Configuration.DefaultSettingsSection.#ctor*
  parent: System.Transactions.Configuration.DefaultSettingsSection
  isExternal: false
  name: DefaultSettingsSection
  nameWithType: DefaultSettingsSection.DefaultSettingsSection
- uid: System.Transactions.Configuration.DefaultSettingsSection.DistributedTransactionManagerName*
  parent: System.Transactions.Configuration.DefaultSettingsSection
  isExternal: false
  name: DistributedTransactionManagerName
  nameWithType: DefaultSettingsSection.DistributedTransactionManagerName
- uid: System.Transactions.Configuration.DefaultSettingsSection.Properties*
  parent: System.Transactions.Configuration.DefaultSettingsSection
  isExternal: false
  name: Properties
  nameWithType: DefaultSettingsSection.Properties
- uid: System.Transactions.Configuration.DefaultSettingsSection.Timeout*
  parent: System.Transactions.Configuration.DefaultSettingsSection
  isExternal: false
  name: Timeout
  nameWithType: DefaultSettingsSection.Timeout
