### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.AssemblyInfo
  id: AssemblyInfo
  children:
  - System.Web.Configuration.AssemblyInfo.#ctor(System.String)
  - System.Web.Configuration.AssemblyInfo.Assembly
  - System.Web.Configuration.AssemblyInfo.Properties
  langs:
  - csharp
  name: AssemblyInfo
  nameWithType: AssemblyInfo
  fullName: System.Web.Configuration.AssemblyInfo
  type: Class
  summary: "関連する動的なリソースのコンパイル時にアセンブリを参照します。 このクラスは継承できません。"
  remarks: "ASP.NET は、各コード モジュールをコンパイルするときに自動的にアセンブリとリソースをリンクします。 AssemblyInfo オブジェクトは、アセンブリを参照します。 アセンブリは、型と連携して機能の論理単位を形成するように構築されたリソースのコレクションです。 アセンブリは、型の実装を識別する必要がある情報を使用して、共通言語ランタイムを提供します。 ランタイムに、型がアセンブリのコンテキスト外ありません。       一般的にリンクされているアセンブリが一覧表示、`assemblies`のノード、`compilation`構成セクション。 さらに、アセンブリできます手動で追加するコード リソースをアプリケーションに追加機能が必要なときにします。"
  syntax:
    content: 'public sealed class AssemblyInfo : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.AssemblyInfo.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Web.Configuration.AssemblyInfo
  langs:
  - csharp
  name: AssemblyInfo(String)
  nameWithType: AssemblyInfo.AssemblyInfo(String)
  fullName: System.Web.Configuration.AssemblyInfo.AssemblyInfo(String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "インスタンスを作成、 <xref href=&quot;System.Web.Configuration.AssemblyInfo&quot;> </xref>クラスです。"
  remarks: "場合、<xref:System.Web.Configuration.AssemblyInfo>アセンブリ情報を含むインスタンスが初期化されていない、例外がスローされます</xref:System.Web.Configuration.AssemblyInfo>。"
  example:
  - "The following code example demonstrates how to create an <xref:System.Web.Configuration.AssemblyInfo> object. This code example is part of a larger example provided for the <xref:System.Web.Configuration.AssemblyCollection> class.  \n  \n [!code-vb[System.Web.Configuration.AssemblyCollection#2](~/add/codesnippet/visualbasic/m-system.web.configurati_4_1.vb)]\n [!code-cs[System.Web.Configuration.AssemblyCollection#2](~/add/codesnippet/csharp/m-system.web.configurati_4_1.cs)]"
  syntax:
    content: public AssemblyInfo (string assemblyName);
    parameters:
    - id: assemblyName
      type: System.String
      description: "バージョン、カルチャ、および公開キー トークンで構成されるコンマ区切りのアセンブリ名の組み合わせを指定します。"
  overload: System.Web.Configuration.AssemblyInfo.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.AssemblyInfo.Assembly
  id: Assembly
  parent: System.Web.Configuration.AssemblyInfo
  langs:
  - csharp
  name: Assembly
  nameWithType: AssemblyInfo.Assembly
  fullName: System.Web.Configuration.AssemblyInfo.Assembly
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "取得または動的なリソースのコンパイル時に使用するアセンブリ参照を設定します。"
  remarks: "ASP.NET は、まずアセンブリ DLL アプリケーションの Bin ディレクトリでプライベートにし、システム アセンブリ キャッシュ内を検索します。"
  syntax:
    content: public string Assembly { get; set; }
    return:
      type: System.String
      description: "バージョン、カルチャ、およびアセンブリの公開キー トークンを指定するコンマ区切りの文字列値。"
  overload: System.Web.Configuration.AssemblyInfo.Assembly*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.AssemblyInfo.Properties
  id: Properties
  parent: System.Web.Configuration.AssemblyInfo
  langs:
  - csharp
  name: Properties
  nameWithType: AssemblyInfo.Properties
  fullName: System.Web.Configuration.AssemblyInfo.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "追加します。"
  overload: System.Web.Configuration.AssemblyInfo.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.AssemblyInfo.#ctor(System.String)
  parent: System.Web.Configuration.AssemblyInfo
  isExternal: false
  name: AssemblyInfo(String)
  nameWithType: AssemblyInfo.AssemblyInfo(String)
  fullName: System.Web.Configuration.AssemblyInfo.AssemblyInfo(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.AssemblyInfo.Assembly
  parent: System.Web.Configuration.AssemblyInfo
  isExternal: false
  name: Assembly
  nameWithType: AssemblyInfo.Assembly
  fullName: System.Web.Configuration.AssemblyInfo.Assembly
- uid: System.Web.Configuration.AssemblyInfo.Properties
  parent: System.Web.Configuration.AssemblyInfo
  isExternal: false
  name: Properties
  nameWithType: AssemblyInfo.Properties
  fullName: System.Web.Configuration.AssemblyInfo.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.AssemblyInfo.#ctor*
  parent: System.Web.Configuration.AssemblyInfo
  isExternal: false
  name: AssemblyInfo
  nameWithType: AssemblyInfo.AssemblyInfo
- uid: System.Web.Configuration.AssemblyInfo.Assembly*
  parent: System.Web.Configuration.AssemblyInfo
  isExternal: false
  name: Assembly
  nameWithType: AssemblyInfo.Assembly
- uid: System.Web.Configuration.AssemblyInfo.Properties*
  parent: System.Web.Configuration.AssemblyInfo
  isExternal: false
  name: Properties
  nameWithType: AssemblyInfo.Properties
