### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.SerializationMode
  id: SerializationMode
  children:
  - System.Web.Configuration.SerializationMode.Binary
  - System.Web.Configuration.SerializationMode.ProviderSpecific
  - System.Web.Configuration.SerializationMode.String
  - System.Web.Configuration.SerializationMode.Xml
  langs:
  - csharp
  name: SerializationMode
  nameWithType: SerializationMode
  fullName: System.Web.Configuration.SerializationMode
  type: Enum
  summary: "シリアル化方法を決定する<xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;></xref>オブジェクト。"
  remarks: "<xref:System.Web.Configuration.ProfilePropertySettings.SerializeAs%2A>のプロパティ、<xref:System.Web.Configuration.ProfilePropertySettings>オブジェクトは、シリアル化モードでの&1; つのプロファイル プロパティの設定を制御します</xref:System.Web.Configuration.ProfilePropertySettings></xref:System.Web.Configuration.ProfilePropertySettings.SerializeAs%2A>。"
  example:
  - "The following code example shows how to use the <xref:System.Web.Configuration.ProfilePropertySettings.SerializeAs%2A> property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.ProfileSection> class.  \n  \n [!code-cs[System.Web.Configuration.ProfileSection#17](~/add/codesnippet/csharp/t-system.web.configurati_92_1.cs)]\n [!code-vb[System.Web.Configuration.ProfileSection#17](~/add/codesnippet/visualbasic/t-system.web.configurati_92_1.vb)]"
  syntax:
    content: public enum SerializationMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.SerializationMode.Binary
  id: Binary
  parent: System.Web.Configuration.SerializationMode
  langs:
  - csharp
  name: Binary
  nameWithType: SerializationMode.Binary
  fullName: System.Web.Configuration.SerializationMode.Binary
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "<xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref>バイナリのシリアル化を使用してオブジェクトをシリアル化します。"
  syntax:
    content: Binary
    return:
      type: System.Web.Configuration.SerializationMode
      description: "追加します。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SerializationMode.ProviderSpecific
  id: ProviderSpecific
  parent: System.Web.Configuration.SerializationMode
  langs:
  - csharp
  name: ProviderSpecific
  nameWithType: SerializationMode.ProviderSpecific
  fullName: System.Web.Configuration.SerializationMode.ProviderSpecific
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "プロバイダーの種類に関して絶対的な知識を持つし、はシリアル化する方法を決定します、 <xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref>データ ストアにオブジェクト。"
  syntax:
    content: ProviderSpecific
    return:
      type: System.Web.Configuration.SerializationMode
      description: "追加します。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SerializationMode.String
  id: String
  parent: System.Web.Configuration.SerializationMode
  langs:
  - csharp
  name: String
  nameWithType: SerializationMode.String
  fullName: System.Web.Configuration.SerializationMode.String
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "<xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref>単純な文字列にシリアル化するオブジェクト。"
  syntax:
    content: String
    return:
      type: System.Web.Configuration.SerializationMode
      description: "追加します。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SerializationMode.Xml
  id: Xml
  parent: System.Web.Configuration.SerializationMode
  langs:
  - csharp
  name: Xml
  nameWithType: SerializationMode.Xml
  fullName: System.Web.Configuration.SerializationMode.Xml
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "プロファイル<xref href=&quot;System.Web.Configuration.ProfilePropertySettings&quot;> </xref> XML シリアル化を使用して XML としてシリアル化します。"
  syntax:
    content: Xml
    return:
      type: System.Web.Configuration.SerializationMode
      description: "追加します。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.SerializationMode.Binary
  parent: System.Web.Configuration.SerializationMode
  isExternal: false
  name: Binary
  nameWithType: SerializationMode.Binary
  fullName: System.Web.Configuration.SerializationMode.Binary
- uid: System.Web.Configuration.SerializationMode
  parent: System.Web.Configuration
  isExternal: false
  name: SerializationMode
  nameWithType: SerializationMode
  fullName: System.Web.Configuration.SerializationMode
- uid: System.Web.Configuration.SerializationMode.ProviderSpecific
  parent: System.Web.Configuration.SerializationMode
  isExternal: false
  name: ProviderSpecific
  nameWithType: SerializationMode.ProviderSpecific
  fullName: System.Web.Configuration.SerializationMode.ProviderSpecific
- uid: System.Web.Configuration.SerializationMode.String
  parent: System.Web.Configuration.SerializationMode
  isExternal: false
  name: String
  nameWithType: SerializationMode.String
  fullName: System.Web.Configuration.SerializationMode.String
- uid: System.Web.Configuration.SerializationMode.Xml
  parent: System.Web.Configuration.SerializationMode
  isExternal: false
  name: Xml
  nameWithType: SerializationMode.Xml
  fullName: System.Web.Configuration.SerializationMode.Xml
