### YamlMime:ManagedReference
items:
- uid: System.Configuration.SubclassTypeValidatorAttribute
  id: SubclassTypeValidatorAttribute
  children:
  - System.Configuration.SubclassTypeValidatorAttribute.#ctor(System.Type)
  - System.Configuration.SubclassTypeValidatorAttribute.BaseClass
  - System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: SubclassTypeValidatorAttribute
  nameWithType: SubclassTypeValidatorAttribute
  fullName: System.Configuration.SubclassTypeValidatorAttribute
  type: Class
  summary: "宣言によって構成プロパティの検証を実行する .NET Framework に指示します。 このクラスは継承できません。"
  remarks: "使用する、<xref:System.Configuration.IntegerValidatorAttribute>構成プロパティを装飾する属性</xref:System.Configuration.IntegerValidatorAttribute>。 これは、.NET Framework SubclassTypeValidatorAttribute 属性を使用してプロパティを検証するように指示して、装飾のパラメーターの値を渡すにです。       SubclassTypeValidatorAttribute 属性は、プロパティ型にのみ適用できます。"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class SubclassTypeValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net462
- uid: System.Configuration.SubclassTypeValidatorAttribute.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.Configuration.SubclassTypeValidatorAttribute
  langs:
  - csharp
  name: SubclassTypeValidatorAttribute(Type)
  nameWithType: SubclassTypeValidatorAttribute.SubclassTypeValidatorAttribute(Type)
  fullName: System.Configuration.SubclassTypeValidatorAttribute.SubclassTypeValidatorAttribute(Type)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Configuration.SubclassTypeValidatorAttribute&quot;> </xref>クラスです。"
  remarks: "属性付きのモデルでこのコンス トラクターを使用すると、関連するプロパティに割り当てられた値が基底クラスであることを確認します。"
  syntax:
    content: public SubclassTypeValidatorAttribute (Type baseClass);
    parameters:
    - id: baseClass
      type: System.Type
      description: "基本クラス型。"
  overload: System.Configuration.SubclassTypeValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SubclassTypeValidatorAttribute.BaseClass
  id: BaseClass
  parent: System.Configuration.SubclassTypeValidatorAttribute
  langs:
  - csharp
  name: BaseClass
  nameWithType: SubclassTypeValidatorAttribute.BaseClass
  fullName: System.Configuration.SubclassTypeValidatorAttribute.BaseClass
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "検証されるオブジェクトの基本型を取得します。"
  syntax:
    content: public Type BaseClass { get; }
    return:
      type: System.Type
      description: "検証されるオブジェクトの基本データ型。"
  overload: System.Configuration.SubclassTypeValidatorAttribute.BaseClass*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.SubclassTypeValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: SubclassTypeValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "属性のインスタンスの検証コントロールを取得します。"
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "現在<xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;></xref>インスタンス。"
  overload: System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.Configuration.SubclassTypeValidatorAttribute.#ctor(System.Type)
  parent: System.Configuration.SubclassTypeValidatorAttribute
  isExternal: false
  name: SubclassTypeValidatorAttribute(Type)
  nameWithType: SubclassTypeValidatorAttribute.SubclassTypeValidatorAttribute(Type)
  fullName: System.Configuration.SubclassTypeValidatorAttribute.SubclassTypeValidatorAttribute(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.SubclassTypeValidatorAttribute.BaseClass
  parent: System.Configuration.SubclassTypeValidatorAttribute
  isExternal: false
  name: BaseClass
  nameWithType: SubclassTypeValidatorAttribute.BaseClass
  fullName: System.Configuration.SubclassTypeValidatorAttribute.BaseClass
- uid: System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance
  parent: System.Configuration.SubclassTypeValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: SubclassTypeValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.SubclassTypeValidatorAttribute.#ctor*
  parent: System.Configuration.SubclassTypeValidatorAttribute
  isExternal: false
  name: SubclassTypeValidatorAttribute
  nameWithType: SubclassTypeValidatorAttribute.SubclassTypeValidatorAttribute
- uid: System.Configuration.SubclassTypeValidatorAttribute.BaseClass*
  parent: System.Configuration.SubclassTypeValidatorAttribute
  isExternal: false
  name: BaseClass
  nameWithType: SubclassTypeValidatorAttribute.BaseClass
- uid: System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.SubclassTypeValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: SubclassTypeValidatorAttribute.ValidatorInstance
