### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationCompletedException
  id: WorkflowApplicationCompletedException
  children:
  - System.Activities.WorkflowApplicationCompletedException.#ctor
  - System.Activities.WorkflowApplicationCompletedException.#ctor(System.String)
  - System.Activities.WorkflowApplicationCompletedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Exception)
  - System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Guid)
  - System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Guid,System.Exception)
  langs:
  - csharp
  name: WorkflowApplicationCompletedException
  nameWithType: WorkflowApplicationCompletedException
  fullName: System.Activities.WorkflowApplicationCompletedException
  type: Class
  summary: "インスタンスが完了したため、ワークフロー インスタンスに対して操作が無効な場合にスローされる例外を表します。"
  syntax:
    content: 'public class WorkflowApplicationCompletedException : System.Activities.WorkflowApplicationException'
  inheritance:
  - System.Exception
  - System.Activities.WorkflowApplicationException
  implements: []
  inheritedMembers:
  - System.Activities.WorkflowApplicationException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Activities.WorkflowApplicationException.InstanceId
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor
  id: '#ctor'
  parent: System.Activities.WorkflowApplicationCompletedException
  langs:
  - csharp
  name: WorkflowApplicationCompletedException()
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException()
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "新しいインスタンスを作成、 <xref href=&quot;System.Activities.WorkflowApplicationCompletedException&quot;> </xref>クラスです。"
  syntax:
    content: public WorkflowApplicationCompletedException ();
    parameters: []
  overload: System.Activities.WorkflowApplicationCompletedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Activities.WorkflowApplicationCompletedException
  langs:
  - csharp
  name: WorkflowApplicationCompletedException(String)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "新しいインスタンスを作成、 <xref href=&quot;System.Activities.WorkflowApplicationCompletedException&quot;> </xref>例外のテキスト文字列説明を持つクラス。"
  syntax:
    content: public WorkflowApplicationCompletedException (string message);
    parameters:
    - id: message
      type: System.String
      description: "アプリケーションの説明には、例外が完了しました。"
  overload: System.Activities.WorkflowApplicationCompletedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Activities.WorkflowApplicationCompletedException
  langs:
  - csharp
  name: WorkflowApplicationCompletedException(SerializationInfo,StreamingContext)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(SerializationInfo,StreamingContext)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "新しいインスタンスを作成、 <xref href=&quot;System.Activities.WorkflowApplicationCompletedException&quot;> </xref>シリアル化されたストリームからこの例外に関するデータを取得するために必要なコンテキストおよびシリアル化情報を持つクラス。"
  syntax:
    content: protected WorkflowApplicationCompletedException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "アプリケーション完了例外オブジェクトを逆シリアル化または逆シリアル化に必要なすべての情報です。"
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "ソースと指定したシリアル化されたストリームと追加の呼び出し元が定義のコンテキストのコピー先。"
  overload: System.Activities.WorkflowApplicationCompletedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Activities.WorkflowApplicationCompletedException
  langs:
  - csharp
  name: WorkflowApplicationCompletedException(String,Exception)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Exception)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Exception)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "新しいインスタンスを作成、 <xref href=&quot;System.Activities.WorkflowApplicationCompletedException&quot;> </xref>クラスおよびアプリケーション完了例外の原因である追加の例外と例外のテキスト文字列説明。"
  syntax:
    content: public WorkflowApplicationCompletedException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "アプリケーションの説明には、例外が完了しました。"
    - id: innerException
      type: System.Exception
      description: "アプリケーションの因果関係がある例外は、例外を完了します。 アプリケーション完了例外は、反応してスローされる、内部例外には、内部例外からの情報を使用して、エラーをより適切に処理します。"
  overload: System.Activities.WorkflowApplicationCompletedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Guid)
  id: '#ctor(System.String,System.Guid)'
  parent: System.Activities.WorkflowApplicationCompletedException
  langs:
  - csharp
  name: WorkflowApplicationCompletedException(String,Guid)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Guid)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Guid)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "新しいインスタンスを作成、 <xref href=&quot;System.Activities.WorkflowApplicationCompletedException&quot;> </xref>クラス、例外のテキスト文字列説明と、例外の一意の識別子。"
  syntax:
    content: public WorkflowApplicationCompletedException (string message, Guid instanceId);
    parameters:
    - id: message
      type: System.String
      description: "アプリケーションの説明には、例外が完了しました。"
    - id: instanceId
      type: System.Guid
      description: "グローバルに一意の識別子。"
  overload: System.Activities.WorkflowApplicationCompletedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Guid,System.Exception)
  id: '#ctor(System.String,System.Guid,System.Exception)'
  parent: System.Activities.WorkflowApplicationCompletedException
  langs:
  - csharp
  name: WorkflowApplicationCompletedException(String,Guid,Exception)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Guid,Exception)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Guid,Exception)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "新しいインスタンスを作成、 <xref href=&quot;System.Activities.WorkflowApplicationCompletedException&quot;> </xref>例外、一意の識別子、およびアプリケーション完了例外の原因である追加の例外のテキスト文字の説明を持つクラス。"
  syntax:
    content: public WorkflowApplicationCompletedException (string message, Guid instanceId, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "アプリケーションの説明には、例外が完了しました。"
    - id: instanceId
      type: System.Guid
      description: "グローバルに一意の識別子。"
    - id: innerException
      type: System.Exception
      description: "アプリケーションの因果関係がある例外は、例外を完了します。 アプリケーション完了例外は、反応してスローされる、内部例外には、内部例外からの情報を使用して、エラーをより適切に処理します。"
  overload: System.Activities.WorkflowApplicationCompletedException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Activities.WorkflowApplicationException
  isExternal: false
  name: System.Activities.WorkflowApplicationException
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor
  parent: System.Activities.WorkflowApplicationCompletedException
  isExternal: false
  name: WorkflowApplicationCompletedException()
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException()
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException()
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.String)
  parent: System.Activities.WorkflowApplicationCompletedException
  isExternal: false
  name: WorkflowApplicationCompletedException(String)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Activities.WorkflowApplicationCompletedException
  isExternal: false
  name: WorkflowApplicationCompletedException(SerializationInfo,StreamingContext)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(SerializationInfo,StreamingContext)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Exception)
  parent: System.Activities.WorkflowApplicationCompletedException
  isExternal: false
  name: WorkflowApplicationCompletedException(String,Exception)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Exception)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Guid)
  parent: System.Activities.WorkflowApplicationCompletedException
  isExternal: false
  name: WorkflowApplicationCompletedException(String,Guid)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Guid)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Guid)
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor(System.String,System.Guid,System.Exception)
  parent: System.Activities.WorkflowApplicationCompletedException
  isExternal: false
  name: WorkflowApplicationCompletedException(String,Guid,Exception)
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Guid,Exception)
  fullName: System.Activities.WorkflowApplicationCompletedException.WorkflowApplicationCompletedException(String,Guid,Exception)
- uid: System.Activities.WorkflowApplicationCompletedException.#ctor*
  parent: System.Activities.WorkflowApplicationCompletedException
  isExternal: false
  name: WorkflowApplicationCompletedException
  nameWithType: WorkflowApplicationCompletedException.WorkflowApplicationCompletedException
