### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationAllowExeDefinition
  id: ConfigurationAllowExeDefinition
  children:
  - System.Configuration.ConfigurationAllowExeDefinition.MachineOnly
  - System.Configuration.ConfigurationAllowExeDefinition.MachineToApplication
  - System.Configuration.ConfigurationAllowExeDefinition.MachineToLocalUser
  - System.Configuration.ConfigurationAllowExeDefinition.MachineToRoamingUser
  langs:
  - csharp
  name: ConfigurationAllowExeDefinition
  nameWithType: ConfigurationAllowExeDefinition
  fullName: System.Configuration.ConfigurationAllowExeDefinition
  type: Enum
  summary: "設定または内に含まれるプロパティを上書きする構成ファイルの階層内の場所を指定します、 <xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref>オブジェクト。"
  remarks: "<xref:System.Configuration.ConfigurationSection>クラス</xref:System.Configuration.ConfigurationSection>の新しいインスタンスを作成するときに、この列挙体の値が使用必要に応じて この列挙は、クライアント アプリケーションにのみ適用に注意してください。"
  syntax:
    content: public enum ConfigurationAllowExeDefinition
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.ConfigurationAllowExeDefinition.MachineOnly
  id: MachineOnly
  parent: System.Configuration.ConfigurationAllowExeDefinition
  langs:
  - csharp
  name: MachineOnly
  nameWithType: ConfigurationAllowExeDefinition.MachineOnly
  fullName: System.Configuration.ConfigurationAllowExeDefinition.MachineOnly
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "<xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref> Machine.config ファイルでのみ定義できます。"
  syntax:
    content: MachineOnly
    return:
      type: System.Configuration.ConfigurationAllowExeDefinition
      description: "追加します。"
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationAllowExeDefinition.MachineToApplication
  id: MachineToApplication
  parent: System.Configuration.ConfigurationAllowExeDefinition
  langs:
  - csharp
  name: MachineToApplication
  nameWithType: ConfigurationAllowExeDefinition.MachineToApplication
  fullName: System.Configuration.ConfigurationAllowExeDefinition.MachineToApplication
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "<xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref> Machine.config ファイルで、またはクライアント アプリケーションのディレクトリ内の *.exe.config ファイルで定義されていることができます。 これは既定値です。"
  syntax:
    content: MachineToApplication
    return:
      type: System.Configuration.ConfigurationAllowExeDefinition
      description: "追加します。"
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationAllowExeDefinition.MachineToLocalUser
  id: MachineToLocalUser
  parent: System.Configuration.ConfigurationAllowExeDefinition
  langs:
  - csharp
  name: MachineToLocalUser
  nameWithType: ConfigurationAllowExeDefinition.MachineToLocalUser
  fullName: System.Configuration.ConfigurationAllowExeDefinition.MachineToLocalUser
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "<xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref> *.Exe.config ファイルをクライアント アプリケーション ディレクトリのローミング ユーザーのディレクトリに User.config ファイルに、またはローカル ユーザーのディレクトリに User.config ファイル内で、Machine.config ファイルで定義されていることができます。"
  syntax:
    content: MachineToLocalUser
    return:
      type: System.Configuration.ConfigurationAllowExeDefinition
      description: "追加します。"
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationAllowExeDefinition.MachineToRoamingUser
  id: MachineToRoamingUser
  parent: System.Configuration.ConfigurationAllowExeDefinition
  langs:
  - csharp
  name: MachineToRoamingUser
  nameWithType: ConfigurationAllowExeDefinition.MachineToRoamingUser
  fullName: System.Configuration.ConfigurationAllowExeDefinition.MachineToRoamingUser
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "<xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref>またはローミング ユーザーのディレクトリに User.config ファイルにクライアント アプリケーションのディレクトリ内の *.exe.config ファイルで、Machine.config ファイルで定義されていることができます。"
  syntax:
    content: MachineToRoamingUser
    return:
      type: System.Configuration.ConfigurationAllowExeDefinition
      description: "追加します。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.ConfigurationAllowExeDefinition.MachineOnly
  parent: System.Configuration.ConfigurationAllowExeDefinition
  isExternal: false
  name: MachineOnly
  nameWithType: ConfigurationAllowExeDefinition.MachineOnly
  fullName: System.Configuration.ConfigurationAllowExeDefinition.MachineOnly
- uid: System.Configuration.ConfigurationAllowExeDefinition
  parent: System.Configuration
  isExternal: false
  name: ConfigurationAllowExeDefinition
  nameWithType: ConfigurationAllowExeDefinition
  fullName: System.Configuration.ConfigurationAllowExeDefinition
- uid: System.Configuration.ConfigurationAllowExeDefinition.MachineToApplication
  parent: System.Configuration.ConfigurationAllowExeDefinition
  isExternal: false
  name: MachineToApplication
  nameWithType: ConfigurationAllowExeDefinition.MachineToApplication
  fullName: System.Configuration.ConfigurationAllowExeDefinition.MachineToApplication
- uid: System.Configuration.ConfigurationAllowExeDefinition.MachineToLocalUser
  parent: System.Configuration.ConfigurationAllowExeDefinition
  isExternal: false
  name: MachineToLocalUser
  nameWithType: ConfigurationAllowExeDefinition.MachineToLocalUser
  fullName: System.Configuration.ConfigurationAllowExeDefinition.MachineToLocalUser
- uid: System.Configuration.ConfigurationAllowExeDefinition.MachineToRoamingUser
  parent: System.Configuration.ConfigurationAllowExeDefinition
  isExternal: false
  name: MachineToRoamingUser
  nameWithType: ConfigurationAllowExeDefinition.MachineToRoamingUser
  fullName: System.Configuration.ConfigurationAllowExeDefinition.MachineToRoamingUser
