### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  id: TrackingQueryElement
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.Annotations
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.ElementKey
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.NewTrackingQuery
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.Properties
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.UpdateTrackingQuery(System.Activities.Tracking.TrackingQuery)
  langs:
  - csharp
  name: TrackingQueryElement
  nameWithType: TrackingQueryElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  type: Class
  summary: "表す構成要素、 <xref href=&quot;System.Activities.Tracking.TrackingQuery&quot;> </xref>追跡プロファイルを指定する場合をインスタンス化します。"
  remarks: "すべての基底クラスは、このクエリの要素を追跡します。"
  syntax:
    content: 'public abstract class TrackingQueryElement : System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement.GetStringPairKey(System.String,System.String)
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  langs:
  - csharp
  name: TrackingQueryElement()
  nameWithType: TrackingQueryElement.TrackingQueryElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.TrackingQueryElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement&quot;> </xref>クラスです。"
  syntax:
    content: protected TrackingQueryElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.Annotations
  id: Annotations
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  langs:
  - csharp
  name: Annotations
  nameWithType: TrackingQueryElement.Annotations
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.Annotations
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "関連付けられている注釈のコレクションを取得、 <xref href=&quot;System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement&quot;></xref>です。"
  syntax:
    content: public System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection Annotations { get; }
    return:
      type: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection
      description: "注釈のコレクション。"
  overload: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.Annotations*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.ElementKey
  id: ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  langs:
  - csharp
  name: ElementKey
  nameWithType: TrackingQueryElement.ElementKey
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.ElementKey
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "追跡クエリを一意に識別するキー。"
  syntax:
    content: public override object ElementKey { get; }
    return:
      type: System.Object
      description: "要素キー。"
  overload: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.ElementKey*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.NewTrackingQuery
  id: NewTrackingQuery
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  langs:
  - csharp
  name: NewTrackingQuery()
  nameWithType: TrackingQueryElement.NewTrackingQuery()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.NewTrackingQuery()
  type: Method
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "クエリ インスタンスを作成し、派生クラスによって継承されないプロパティを設定するには、このメソッドをオーバーライドします。"
  syntax:
    content: protected abstract System.Activities.Tracking.TrackingQuery NewTrackingQuery ();
    parameters: []
    return:
      type: System.Activities.Tracking.TrackingQuery
      description: "A <xref href=&quot;System.Activities.Tracking.TrackingQuery&quot;> </xref>インスタンス。"
  overload: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.NewTrackingQuery*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  langs:
  - csharp
  name: Properties
  nameWithType: TrackingQueryElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "プロパティのコレクションを取得します。"
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要素のプロパティのコレクション。"
  overload: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.UpdateTrackingQuery(System.Activities.Tracking.TrackingQuery)
  id: UpdateTrackingQuery(System.Activities.Tracking.TrackingQuery)
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  langs:
  - csharp
  name: UpdateTrackingQuery(TrackingQuery)
  nameWithType: TrackingQueryElement.UpdateTrackingQuery(TrackingQuery)
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.UpdateTrackingQuery(TrackingQuery)
  type: Method
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "派生クラスが継承プロパティを設定するには、このメソッドをオーバーライドします。"
  syntax:
    content: protected virtual void UpdateTrackingQuery (System.Activities.Tracking.TrackingQuery trackingQuery);
    parameters:
    - id: trackingQuery
      type: System.Activities.Tracking.TrackingQuery
      description: "追跡クエリ。"
  overload: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.UpdateTrackingQuery*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  isExternal: false
  name: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  isExternal: false
  name: TrackingQueryElement()
  nameWithType: TrackingQueryElement.TrackingQueryElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.TrackingQueryElement()
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.Annotations
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  isExternal: false
  name: Annotations
  nameWithType: TrackingQueryElement.Annotations
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.Annotations
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection
  parent: System.ServiceModel.Activities.Tracking.Configuration
  isExternal: false
  name: AnnotationElementCollection
  nameWithType: AnnotationElementCollection
  fullName: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  isExternal: false
  name: ElementKey
  nameWithType: TrackingQueryElement.ElementKey
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.ElementKey
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.NewTrackingQuery
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  isExternal: false
  name: NewTrackingQuery()
  nameWithType: TrackingQueryElement.NewTrackingQuery()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.NewTrackingQuery()
- uid: System.Activities.Tracking.TrackingQuery
  parent: System.Activities.Tracking
  isExternal: false
  name: TrackingQuery
  nameWithType: TrackingQuery
  fullName: System.Activities.Tracking.TrackingQuery
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  isExternal: false
  name: Properties
  nameWithType: TrackingQueryElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.UpdateTrackingQuery(System.Activities.Tracking.TrackingQuery)
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  isExternal: false
  name: UpdateTrackingQuery(TrackingQuery)
  nameWithType: TrackingQueryElement.UpdateTrackingQuery(TrackingQuery)
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.UpdateTrackingQuery(TrackingQuery)
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  isExternal: false
  name: TrackingQueryElement
  nameWithType: TrackingQueryElement.TrackingQueryElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.Annotations*
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  isExternal: false
  name: Annotations
  nameWithType: TrackingQueryElement.Annotations
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.ElementKey*
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  isExternal: false
  name: ElementKey
  nameWithType: TrackingQueryElement.ElementKey
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.NewTrackingQuery*
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  isExternal: false
  name: NewTrackingQuery
  nameWithType: TrackingQueryElement.NewTrackingQuery
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.Properties*
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  isExternal: false
  name: Properties
  nameWithType: TrackingQueryElement.Properties
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.UpdateTrackingQuery*
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  isExternal: false
  name: UpdateTrackingQuery
  nameWithType: TrackingQueryElement.UpdateTrackingQuery
