### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.HttpWebRequestElement
  id: HttpWebRequestElement
  children:
  - System.Net.Configuration.HttpWebRequestElement.#ctor
  - System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength
  - System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength
  - System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength
  - System.Net.Configuration.HttpWebRequestElement.PostDeserialize
  - System.Net.Configuration.HttpWebRequestElement.Properties
  - System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing
  langs:
  - csharp
  name: HttpWebRequestElement
  nameWithType: HttpWebRequestElement
  fullName: System.Net.Configuration.HttpWebRequestElement
  type: Class
  summary: "応答ヘッダーの最大の長さを表します。 このクラスは継承できません。"
  remarks: "This class corresponds to the `maximumResponseHeadersLength` attribute of the [\\&lt;httpWebRequest\\&gt; Element (Network Settings)](../Topic/%3ChttpWebRequest%3E%20Element%20\\(Network%20Settings\\).md) configuration element.  \n  \n The information in this class applies to responses to requests made with the <xref:System.Net.WebRequest> and <xref:System.Net.WebClient> classes.  \n  \n This class provides programmatic access to information that can be stored in configuration files."
  syntax:
    content: 'public sealed class HttpWebRequestElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Net.Configuration.HttpWebRequestElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: HttpWebRequestElement()
  nameWithType: HttpWebRequestElement.HttpWebRequestElement()
  fullName: System.Net.Configuration.HttpWebRequestElement.HttpWebRequestElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Net.Configuration.HttpWebRequestElement&quot;> </xref>クラスです。"
  remarks: "このコンス トラクターを追加、<xref:System.Configuration.ConfigurationProperty>を表すオブジェクト、<xref:System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength%2A>を<xref:System.Configuration.ConfigurationElement.Properties%2A>コレクションです</xref:System.Configuration.ConfigurationElement.Properties%2A></xref:System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength%2A></xref:System.Configuration.ConfigurationProperty>。"
  syntax:
    content: public HttpWebRequestElement ();
    parameters: []
  overload: System.Net.Configuration.HttpWebRequestElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength
  id: MaximumErrorResponseLength
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: MaximumErrorResponseLength
  nameWithType: HttpWebRequestElement.MaximumErrorResponseLength
  fullName: System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "取得またはエラー応答の最大許容長を設定します。"
  syntax:
    content: public int MaximumErrorResponseLength { get; set; }
    return:
      type: System.Int32
      description: "32 ビットに符号付き整数。 エラー応答のキロバイト (1024 バイト) の最大長を格納します。 既定値は 64 です。"
  overload: System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength
  id: MaximumResponseHeadersLength
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: MaximumResponseHeadersLength
  nameWithType: HttpWebRequestElement.MaximumResponseHeadersLength
  fullName: System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "取得または応答ヘッダーの許容最大長を設定します。"
  remarks: "長さをキロバイト (1024 バイト) で測定され、応答のステータス行と応答ヘッダーだけでなく、HTTP プロトコルの一部として受信したすべての余分な制御文字が含まれています。       値の-1 の場合は、応答ヘッダーに制限は適用されません。値 0 は、すべての要求が失敗することを意味します。"
  syntax:
    content: public int MaximumResponseHeadersLength { get; set; }
    return:
      type: System.Int32
      description: "32 ビットに符号付き整数。 応答ヘッダーのキロバイト (1024 バイト) の最大長を格納します。 既定値は 64 です。"
  overload: System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength
  id: MaximumUnauthorizedUploadLength
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: MaximumUnauthorizedUploadLength
  nameWithType: HttpWebRequestElement.MaximumUnauthorizedUploadLength
  fullName: System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "取得または承認されていないエラー コードへの応答でアップロードの最大長を設定します。"
  syntax:
    content: public int MaximumUnauthorizedUploadLength { get; set; }
    return:
      type: System.Int32
      description: "未承認のエラー コードへの応答のアップロードの最大長 (で 1,024 バイト単位の複数) を含む、32 ビットの符号付き整数。 値-1 は、アップロード時にサイズの制限が設定されていないことを示します。 指定されたバイト数よりも小さい場合、MaximumUnauthorizedUploadLength プロパティその他の値に設定は、要求本文のみ送信します。 1 の値は 1,024 バイト未満である場合のみ、要求本文を送信することを示します。       このプロパティの既定値は-1 です。"
  overload: System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpWebRequestElement.PostDeserialize
  id: PostDeserialize
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: PostDeserialize()
  nameWithType: HttpWebRequestElement.PostDeserialize()
  fullName: System.Net.Configuration.HttpWebRequestElement.PostDeserialize()
  type: Method
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override void PostDeserialize ();
    parameters: []
  overload: System.Net.Configuration.HttpWebRequestElement.PostDeserialize*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpWebRequestElement.Properties
  id: Properties
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: Properties
  nameWithType: HttpWebRequestElement.Properties
  fullName: System.Net.Configuration.HttpWebRequestElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "追加します。"
  overload: System.Net.Configuration.HttpWebRequestElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing
  id: UseUnsafeHeaderParsing
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: UseUnsafeHeaderParsing
  nameWithType: HttpWebRequestElement.UseUnsafeHeaderParsing
  fullName: System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "このプロパティの設定には、HTTP の解析中に発生した検証エラーは無視されます。"
  remarks: "このプロパティに設定するときに`false`HTTP の解析中に次の検証が実行:-で行の終了コード、CRLF。 CR または LF のみを使用することはできません。      ヘッダー名にスペースを含めるにはできません。      -複数のステータス行が存在する場合は、追加の状態のすべての行が名前/値ペアの形式が正しくないヘッダーとして扱われます。      ステータス行には、ステータス コードに加えて、ステータスの説明が必要です。      ヘッダー名に非 ASCII 文字を持つことはできません。 このプロパティに設定するかどうか、この検証は実行`true`または`false`です。       プロトコル違反が発生すると、<xref:System.Net.WebException>状態の<xref:System.Net.WebExceptionStatus>。</xref:System.Net.WebExceptionStatus>設定で例外がスローされます。</xref:System.Net.WebException> 場合、`UseUnsafeHeaderParsing`プロパティに設定されている`true`、検証エラーは無視されます。       このプロパティを設定`true`のため、これは、サーバーとの下位互換性が必要な場合にのみ実行するセキュリティへの影響がします。"
  syntax:
    content: public bool UseUnsafeHeaderParsing { get; set; }
    return:
      type: System.Boolean
      description: "このプロパティが設定されているかどうかを示すブール値。"
  overload: System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.HttpWebRequestElement.#ctor
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: HttpWebRequestElement()
  nameWithType: HttpWebRequestElement.HttpWebRequestElement()
  fullName: System.Net.Configuration.HttpWebRequestElement.HttpWebRequestElement()
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: MaximumErrorResponseLength
  nameWithType: HttpWebRequestElement.MaximumErrorResponseLength
  fullName: System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: MaximumResponseHeadersLength
  nameWithType: HttpWebRequestElement.MaximumResponseHeadersLength
  fullName: System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: MaximumUnauthorizedUploadLength
  nameWithType: HttpWebRequestElement.MaximumUnauthorizedUploadLength
  fullName: System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength
- uid: System.Net.Configuration.HttpWebRequestElement.PostDeserialize
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: PostDeserialize()
  nameWithType: HttpWebRequestElement.PostDeserialize()
  fullName: System.Net.Configuration.HttpWebRequestElement.PostDeserialize()
- uid: System.Net.Configuration.HttpWebRequestElement.Properties
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: Properties
  nameWithType: HttpWebRequestElement.Properties
  fullName: System.Net.Configuration.HttpWebRequestElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: UseUnsafeHeaderParsing
  nameWithType: HttpWebRequestElement.UseUnsafeHeaderParsing
  fullName: System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Net.Configuration.HttpWebRequestElement.#ctor*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: HttpWebRequestElement
  nameWithType: HttpWebRequestElement.HttpWebRequestElement
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: MaximumErrorResponseLength
  nameWithType: HttpWebRequestElement.MaximumErrorResponseLength
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: MaximumResponseHeadersLength
  nameWithType: HttpWebRequestElement.MaximumResponseHeadersLength
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: MaximumUnauthorizedUploadLength
  nameWithType: HttpWebRequestElement.MaximumUnauthorizedUploadLength
- uid: System.Net.Configuration.HttpWebRequestElement.PostDeserialize*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: PostDeserialize
  nameWithType: HttpWebRequestElement.PostDeserialize
- uid: System.Net.Configuration.HttpWebRequestElement.Properties*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: Properties
  nameWithType: HttpWebRequestElement.Properties
- uid: System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: UseUnsafeHeaderParsing
  nameWithType: HttpWebRequestElement.UseUnsafeHeaderParsing
