### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.WSDualHttpSecurity
  id: WSDualHttpSecurity
  children:
  - System.ServiceModel.WSDualHttpSecurity.#ctor
  - System.ServiceModel.WSDualHttpSecurity.Message
  - System.ServiceModel.WSDualHttpSecurity.Mode
  - System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMessage
  - System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMode
  langs:
  - csharp
  name: WSDualHttpSecurity
  nameWithType: WSDualHttpSecurity
  fullName: System.ServiceModel.WSDualHttpSecurity
  type: Class
  summary: "セキュリティの設定を示す、 <xref href=&quot;System.ServiceModel.WSDualHttpBinding&quot;></xref>です。"
  remarks: "このクラスのセキュリティ設定を指定する、`wsDualHttpBinding`バインドします。"
  syntax:
    content: public sealed class WSDualHttpSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.WSDualHttpSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.WSDualHttpSecurity
  langs:
  - csharp
  name: WSDualHttpSecurity()
  nameWithType: WSDualHttpSecurity.WSDualHttpSecurity()
  fullName: System.ServiceModel.WSDualHttpSecurity.WSDualHttpSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.ServiceModel.WSDualHttpSecurity&quot;> </xref>クラスです。"
  syntax:
    content: public WSDualHttpSecurity ();
    parameters: []
  overload: System.ServiceModel.WSDualHttpSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WSDualHttpSecurity.Message
  id: Message
  parent: System.ServiceModel.WSDualHttpSecurity
  langs:
  - csharp
  name: Message
  nameWithType: WSDualHttpSecurity.Message
  fullName: System.ServiceModel.WSDualHttpSecurity.Message
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "メッセージ レベルのセキュリティ プロパティを取得、 <xref href=&quot;System.ServiceModel.WSDualHttpBinding&quot;></xref>です。"
  remarks: "返されるオブジェクトの詳細なメッセージ レベルのセキュリティ プロパティを指定する、`wsDualHttpBinding`バインドします。"
  example:
  - "The following code shows how to set the <xref:System.ServiceModel.MessageSecurityOverHttp.AlgorithmSuite%2A> property by accessing this property.  \n  \n [!code-cs[S_UEWSDualHttpSecurity#30](~/add/codesnippet/csharp/p-system.servicemodel.ws_4_1.cs)]\n [!code-vb[S_UEWSDualHttpSecurity#30](~/add/codesnippet/visualbasic/p-system.servicemodel.ws_4_1.vb)]"
  syntax:
    content: public System.ServiceModel.MessageSecurityOverHttp Message { get; set; }
    return:
      type: System.ServiceModel.MessageSecurityOverHttp
      description: 'A <xref href=&quot;System.ServiceModel.MessageSecurityOverHttp&quot;></xref> value. The default values include: <>*> is <xref:System.ServiceModel.MessageCredentialType>, <>*> is <>*>, and <>*> is <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>.</xref:System.ServiceModel.MessageCredentialType>'
  overload: System.ServiceModel.WSDualHttpSecurity.Message*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WSDualHttpSecurity.Mode
  id: Mode
  parent: System.ServiceModel.WSDualHttpSecurity
  langs:
  - csharp
  name: Mode
  nameWithType: WSDualHttpSecurity.Mode
  fullName: System.ServiceModel.WSDualHttpSecurity.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "親のセキュリティ モードを設定を取得または<xref href=&quot;System.ServiceModel.WSDualHttpBinding&quot;></xref>です。"
  remarks: "このプロパティの値は、メッセージ レベルのセキュリティがバインディングに適用されるかどうかを判断します。"
  example:
  - "The following code shows how to set this property.  \n  \n [!code-cs[S_UEWSDualHttpSecurity#30](~/add/codesnippet/csharp/p-system.servicemodel.ws_16_1.cs)]\n [!code-vb[S_UEWSDualHttpSecurity#30](~/add/codesnippet/visualbasic/p-system.servicemodel.ws_16_1.vb)]"
  syntax:
    content: public System.ServiceModel.WSDualHttpSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.WSDualHttpSecurityMode
      description: "値、 <xref href=&quot;System.ServiceModel.WSDualHttpSecurityMode&quot;> </xref>列挙します。 既定値は<xref href=&quot;System.ServiceModel.WSDualHttpSecurityMode&quot;></xref>です。"
  overload: System.ServiceModel.WSDualHttpSecurity.Mode*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "値が有効な<xref href=&quot;System.ServiceModel.WSDualHttpSecurityMode&quot;></xref>です。"
  platform:
  - net462
- uid: System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMessage
  id: ShouldSerializeMessage
  parent: System.ServiceModel.WSDualHttpSecurity
  langs:
  - csharp
  name: ShouldSerializeMessage()
  nameWithType: WSDualHttpSecurity.ShouldSerializeMessage()
  fullName: System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMessage()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "示す値を返すかどうか、<xref:System.ServiceModel.WSDualHttpSecurity.Message*>プロパティがその既定値から変更し、シリアル化する必要があります</xref:System.ServiceModel.WSDualHttpSecurity.Message*>。 WCF によって XAML 統合に使用されます。"
  syntax:
    content: public bool ShouldSerializeMessage ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>場合、<xref:System.ServiceModel.WSDualHttpSecurity.Message*>プロパティの値が、それ以外のシリアル化する必要があります<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref></xref:System.ServiceModel.WSDualHttpSecurity.Message*> 。"
  overload: System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMessage*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMode
  id: ShouldSerializeMode
  parent: System.ServiceModel.WSDualHttpSecurity
  langs:
  - csharp
  name: ShouldSerializeMode()
  nameWithType: WSDualHttpSecurity.ShouldSerializeMode()
  fullName: System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMode()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "示す値を返すかどうか、<xref:System.ServiceModel.WSDualHttpSecurity.Mode*>プロパティがその既定値から変更し、シリアル化する必要があります</xref:System.ServiceModel.WSDualHttpSecurity.Mode*>。 WCF によって XAML 統合に使用されます。"
  syntax:
    content: public bool ShouldSerializeMode ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>場合、<xref:System.ServiceModel.WSDualHttpSecurity.Mode*>プロパティの値が、それ以外のシリアル化する必要があります<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref></xref:System.ServiceModel.WSDualHttpSecurity.Mode*> 。"
  overload: System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMode*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.WSDualHttpSecurity.#ctor
  parent: System.ServiceModel.WSDualHttpSecurity
  isExternal: false
  name: WSDualHttpSecurity()
  nameWithType: WSDualHttpSecurity.WSDualHttpSecurity()
  fullName: System.ServiceModel.WSDualHttpSecurity.WSDualHttpSecurity()
- uid: System.ServiceModel.WSDualHttpSecurity.Message
  parent: System.ServiceModel.WSDualHttpSecurity
  isExternal: false
  name: Message
  nameWithType: WSDualHttpSecurity.Message
  fullName: System.ServiceModel.WSDualHttpSecurity.Message
- uid: System.ServiceModel.MessageSecurityOverHttp
  parent: System.ServiceModel
  isExternal: false
  name: MessageSecurityOverHttp
  nameWithType: MessageSecurityOverHttp
  fullName: System.ServiceModel.MessageSecurityOverHttp
- uid: System.ServiceModel.WSDualHttpSecurity.Mode
  parent: System.ServiceModel.WSDualHttpSecurity
  isExternal: false
  name: Mode
  nameWithType: WSDualHttpSecurity.Mode
  fullName: System.ServiceModel.WSDualHttpSecurity.Mode
- uid: System.ServiceModel.WSDualHttpSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: WSDualHttpSecurityMode
  nameWithType: WSDualHttpSecurityMode
  fullName: System.ServiceModel.WSDualHttpSecurityMode
- uid: System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMessage
  parent: System.ServiceModel.WSDualHttpSecurity
  isExternal: false
  name: ShouldSerializeMessage()
  nameWithType: WSDualHttpSecurity.ShouldSerializeMessage()
  fullName: System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMessage()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMode
  parent: System.ServiceModel.WSDualHttpSecurity
  isExternal: false
  name: ShouldSerializeMode()
  nameWithType: WSDualHttpSecurity.ShouldSerializeMode()
  fullName: System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMode()
- uid: System.ServiceModel.WSDualHttpSecurity.#ctor*
  parent: System.ServiceModel.WSDualHttpSecurity
  isExternal: false
  name: WSDualHttpSecurity
  nameWithType: WSDualHttpSecurity.WSDualHttpSecurity
- uid: System.ServiceModel.WSDualHttpSecurity.Message*
  parent: System.ServiceModel.WSDualHttpSecurity
  isExternal: false
  name: Message
  nameWithType: WSDualHttpSecurity.Message
- uid: System.ServiceModel.WSDualHttpSecurity.Mode*
  parent: System.ServiceModel.WSDualHttpSecurity
  isExternal: false
  name: Mode
  nameWithType: WSDualHttpSecurity.Mode
- uid: System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMessage*
  parent: System.ServiceModel.WSDualHttpSecurity
  isExternal: false
  name: ShouldSerializeMessage
  nameWithType: WSDualHttpSecurity.ShouldSerializeMessage
- uid: System.ServiceModel.WSDualHttpSecurity.ShouldSerializeMode*
  parent: System.ServiceModel.WSDualHttpSecurity
  isExternal: false
  name: ShouldSerializeMode
  nameWithType: WSDualHttpSecurity.ShouldSerializeMode
