### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  id: X509DefaultServiceCertificateElement
  children:
  - System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.#ctor
  - System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Copy(System.ServiceModel.Configuration.X509DefaultServiceCertificateElement)
  - System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.FindValue
  - System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Properties
  - System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreLocation
  - System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreName
  - System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.X509FindType
  langs:
  - csharp
  name: X509DefaultServiceCertificateElement
  nameWithType: X509DefaultServiceCertificateElement
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  type: Class
  summary: "サービスによって使用される既定の証明書を指定する構成要素を表します。 このクラスは継承できません。"
  syntax:
    content: 'public sealed class X509DefaultServiceCertificateElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  langs:
  - csharp
  name: X509DefaultServiceCertificateElement()
  nameWithType: X509DefaultServiceCertificateElement.X509DefaultServiceCertificateElement()
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.X509DefaultServiceCertificateElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.ServiceModel.Configuration.X509DefaultServiceCertificateElement&quot;> </xref>クラスです。"
  syntax:
    content: public X509DefaultServiceCertificateElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Copy(System.ServiceModel.Configuration.X509DefaultServiceCertificateElement)
  id: Copy(System.ServiceModel.Configuration.X509DefaultServiceCertificateElement)
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  langs:
  - csharp
  name: Copy(X509DefaultServiceCertificateElement)
  nameWithType: X509DefaultServiceCertificateElement.Copy(X509DefaultServiceCertificateElement)
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Copy(X509DefaultServiceCertificateElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "この構成要素に指定された構成要素の内容をコピーします。"
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.X509DefaultServiceCertificateElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
      description: "コピーされる構成要素。"
  overload: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Copy*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>from</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "構成ファイルは、読み取り専用です。"
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.FindValue
  id: FindValue
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  langs:
  - csharp
  name: FindValue
  nameWithType: X509DefaultServiceCertificateElement.FindValue
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.FindValue
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得または X.509 証明書ストアで検索する値を指定する文字列を設定します。"
  remarks: "このプロパティに含まれる型は、指定した要件を満たしている必要があります<xref:System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.X509FindType%2A>値</xref:System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.X509FindType%2A>。 既定では、空の文字列です。"
  syntax:
    content: public string FindValue { get; set; }
    return:
      type: System.String
      description: "X.509 証明書ストアで検索する値。"
  overload: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.FindValue*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  langs:
  - csharp
  name: Properties
  nameWithType: X509DefaultServiceCertificateElement.Properties
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "追加します。"
  overload: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreLocation
  id: StoreLocation
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  langs:
  - csharp
  name: StoreLocation
  nameWithType: X509DefaultServiceCertificateElement.StoreLocation
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreLocation
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得またはサーバーの証明書の検証に使用できる、クライアント証明書ストアの位置を指定する値を設定します。"
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreLocation StoreLocation { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreLocation
      description: "A <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreLocation&quot;> </xref>クライアント、サーバーの証明書の検証に使用できる証明書ストアの場所を指定します。 既定値は<xref href=&quot;System.Security.Cryptography.X509Certificates.StoreLocation&quot;></xref>です。"
  overload: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreLocation*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreName
  id: StoreName
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  langs:
  - csharp
  name: StoreName
  nameWithType: X509DefaultServiceCertificateElement.StoreName
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得または設定を開くには、X.509 証明書ストアの名前。"
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreName StoreName { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreName
      description: "A <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreName&quot;> </xref>を開くには、X.509 証明書ストアの名前を格納しています。"
  overload: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.X509FindType
  id: X509FindType
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  langs:
  - csharp
  name: X509FindType
  nameWithType: X509DefaultServiceCertificateElement.X509FindType
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.X509FindType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得またはを実行する X.509 検索の種類を設定します。"
  remarks: "含まれる型<xref:System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.FindValue%2A>このプロパティの要件を満たす必要があります</xref:System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.FindValue%2A>。"
  syntax:
    content: public System.Security.Cryptography.X509Certificates.X509FindType X509FindType { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.X509FindType
      description: "A <xref href=&quot;System.Security.Cryptography.X509Certificates.X509FindType&quot;> </xref>を実行する X.509 検索の種類を指定します。"
  overload: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.X509FindType*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.#ctor
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: X509DefaultServiceCertificateElement()
  nameWithType: X509DefaultServiceCertificateElement.X509DefaultServiceCertificateElement()
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.X509DefaultServiceCertificateElement()
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Copy(System.ServiceModel.Configuration.X509DefaultServiceCertificateElement)
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: Copy(X509DefaultServiceCertificateElement)
  nameWithType: X509DefaultServiceCertificateElement.Copy(X509DefaultServiceCertificateElement)
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Copy(X509DefaultServiceCertificateElement)
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: X509DefaultServiceCertificateElement
  nameWithType: X509DefaultServiceCertificateElement
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.FindValue
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: FindValue
  nameWithType: X509DefaultServiceCertificateElement.FindValue
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.FindValue
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Properties
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: Properties
  nameWithType: X509DefaultServiceCertificateElement.Properties
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreLocation
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: StoreLocation
  nameWithType: X509DefaultServiceCertificateElement.StoreLocation
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreLocation
- uid: System.Security.Cryptography.X509Certificates.StoreLocation
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreLocation
  nameWithType: StoreLocation
  fullName: System.Security.Cryptography.X509Certificates.StoreLocation
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreName
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: StoreName
  nameWithType: X509DefaultServiceCertificateElement.StoreName
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreName
- uid: System.Security.Cryptography.X509Certificates.StoreName
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreName
  nameWithType: StoreName
  fullName: System.Security.Cryptography.X509Certificates.StoreName
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.X509FindType
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: X509FindType
  nameWithType: X509DefaultServiceCertificateElement.X509FindType
  fullName: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.X509FindType
- uid: System.Security.Cryptography.X509Certificates.X509FindType
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: X509FindType
  nameWithType: X509FindType
  fullName: System.Security.Cryptography.X509Certificates.X509FindType
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.#ctor*
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: X509DefaultServiceCertificateElement
  nameWithType: X509DefaultServiceCertificateElement.X509DefaultServiceCertificateElement
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Copy*
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: Copy
  nameWithType: X509DefaultServiceCertificateElement.Copy
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.FindValue*
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: FindValue
  nameWithType: X509DefaultServiceCertificateElement.FindValue
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.Properties*
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: Properties
  nameWithType: X509DefaultServiceCertificateElement.Properties
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreLocation*
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: StoreLocation
  nameWithType: X509DefaultServiceCertificateElement.StoreLocation
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.StoreName*
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: StoreName
  nameWithType: X509DefaultServiceCertificateElement.StoreName
- uid: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement.X509FindType*
  parent: System.ServiceModel.Configuration.X509DefaultServiceCertificateElement
  isExternal: false
  name: X509FindType
  nameWithType: X509DefaultServiceCertificateElement.X509FindType
