### YamlMime:ManagedReference
items:
- uid: System.Configuration.NameValueConfigurationElement
  id: NameValueConfigurationElement
  children:
  - System.Configuration.NameValueConfigurationElement.#ctor(System.String,System.String)
  - System.Configuration.NameValueConfigurationElement.Name
  - System.Configuration.NameValueConfigurationElement.Properties
  - System.Configuration.NameValueConfigurationElement.Value
  langs:
  - csharp
  name: NameValueConfigurationElement
  nameWithType: NameValueConfigurationElement
  fullName: System.Configuration.NameValueConfigurationElement
  type: Class
  summary: "格納する構成要素、<xref:System.String>名および<xref:System.String>値</xref:System.String></xref:System.String>。 このクラスは継承できません。"
  remarks: "<xref:System.Configuration.ConfigurationElement>基底クラス</xref:System.Configuration.ConfigurationElement>から継承して、NameValueConfigurationElement <xref:System.Configuration.ConfigurationElement>構成ファイル内の要素を表します</xref:System.Configuration.ConfigurationElement>。       NameValueConfigurationElement クラスおよび<xref:System.Configuration.KeyValueConfigurationElement>クラス</xref:System.Configuration.KeyValueConfigurationElement>間で違いがあります。 NameValueConfigurationElement クラスでは、一意である最初の文字列は必要ありませんが<xref:System.Configuration.KeyValueConfigurationElement>クラスには、キー、およびそのため、コレクション内で一意である最初の文字列が必要です</xref:System.Configuration.KeyValueConfigurationElement>。"
  syntax:
    content: 'public sealed class NameValueConfigurationElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Configuration.NameValueConfigurationElement.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Configuration.NameValueConfigurationElement
  langs:
  - csharp
  name: NameValueConfigurationElement(String,String)
  nameWithType: NameValueConfigurationElement.NameValueConfigurationElement(String,String)
  fullName: System.Configuration.NameValueConfigurationElement.NameValueConfigurationElement(String,String)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Configuration.NameValueConfigurationElement&quot;> </xref>クラスに基づくパラメーターを指定します。"
  syntax:
    content: public NameValueConfigurationElement (string name, string value);
    parameters:
    - id: name
      type: System.String
      description: "名前、 <xref href=&quot;System.Configuration.NameValueConfigurationElement&quot;> </xref>オブジェクト。"
    - id: value
      type: System.String
      description: "値、 <xref href=&quot;System.Configuration.NameValueConfigurationElement&quot;> </xref>オブジェクト。"
  overload: System.Configuration.NameValueConfigurationElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.NameValueConfigurationElement.Name
  id: Name
  parent: System.Configuration.NameValueConfigurationElement
  langs:
  - csharp
  name: Name
  nameWithType: NameValueConfigurationElement.Name
  fullName: System.Configuration.NameValueConfigurationElement.Name
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "名前を取得、 <xref href=&quot;System.Configuration.NameValueConfigurationElement&quot;> </xref>オブジェクト。"
  syntax:
    content: public string Name { get; }
    return:
      type: System.String
      description: "名前、 <xref href=&quot;System.Configuration.NameValueConfigurationElement&quot;> </xref>オブジェクト。"
  overload: System.Configuration.NameValueConfigurationElement.Name*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.NameValueConfigurationElement.Properties
  id: Properties
  parent: System.Configuration.NameValueConfigurationElement
  langs:
  - csharp
  name: Properties
  nameWithType: NameValueConfigurationElement.Properties
  fullName: System.Configuration.NameValueConfigurationElement.Properties
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "追加します。"
  overload: System.Configuration.NameValueConfigurationElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.NameValueConfigurationElement.Value
  id: Value
  parent: System.Configuration.NameValueConfigurationElement
  langs:
  - csharp
  name: Value
  nameWithType: NameValueConfigurationElement.Value
  fullName: System.Configuration.NameValueConfigurationElement.Value
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "取得または設定の値、 <xref href=&quot;System.Configuration.NameValueConfigurationElement&quot;> </xref>オブジェクト。"
  syntax:
    content: public string Value { get; set; }
    return:
      type: System.String
      description: "値、 <xref href=&quot;System.Configuration.NameValueConfigurationElement&quot;> </xref>オブジェクト。"
  overload: System.Configuration.NameValueConfigurationElement.Value*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Configuration.NameValueConfigurationElement.#ctor(System.String,System.String)
  parent: System.Configuration.NameValueConfigurationElement
  isExternal: false
  name: NameValueConfigurationElement(String,String)
  nameWithType: NameValueConfigurationElement.NameValueConfigurationElement(String,String)
  fullName: System.Configuration.NameValueConfigurationElement.NameValueConfigurationElement(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.NameValueConfigurationElement.Name
  parent: System.Configuration.NameValueConfigurationElement
  isExternal: false
  name: Name
  nameWithType: NameValueConfigurationElement.Name
  fullName: System.Configuration.NameValueConfigurationElement.Name
- uid: System.Configuration.NameValueConfigurationElement.Properties
  parent: System.Configuration.NameValueConfigurationElement
  isExternal: false
  name: Properties
  nameWithType: NameValueConfigurationElement.Properties
  fullName: System.Configuration.NameValueConfigurationElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Configuration.NameValueConfigurationElement.Value
  parent: System.Configuration.NameValueConfigurationElement
  isExternal: false
  name: Value
  nameWithType: NameValueConfigurationElement.Value
  fullName: System.Configuration.NameValueConfigurationElement.Value
- uid: System.Configuration.NameValueConfigurationElement.#ctor*
  parent: System.Configuration.NameValueConfigurationElement
  isExternal: false
  name: NameValueConfigurationElement
  nameWithType: NameValueConfigurationElement.NameValueConfigurationElement
- uid: System.Configuration.NameValueConfigurationElement.Name*
  parent: System.Configuration.NameValueConfigurationElement
  isExternal: false
  name: Name
  nameWithType: NameValueConfigurationElement.Name
- uid: System.Configuration.NameValueConfigurationElement.Properties*
  parent: System.Configuration.NameValueConfigurationElement
  isExternal: false
  name: Properties
  nameWithType: NameValueConfigurationElement.Properties
- uid: System.Configuration.NameValueConfigurationElement.Value*
  parent: System.Configuration.NameValueConfigurationElement
  isExternal: false
  name: Value
  nameWithType: NameValueConfigurationElement.Value
