### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlReaderSettings
  id: XamlReaderSettings
  children:
  - System.Xaml.XamlReaderSettings.#ctor
  - System.Xaml.XamlReaderSettings.#ctor(System.Xaml.XamlReaderSettings)
  - System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  - System.Xaml.XamlReaderSettings.BaseUri
  - System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  - System.Xaml.XamlReaderSettings.LocalAssembly
  - System.Xaml.XamlReaderSettings.ProvideLineInfo
  - System.Xaml.XamlReaderSettings.ValuesMustBeString
  langs:
  - csharp
  name: XamlReaderSettings
  nameWithType: XamlReaderSettings
  fullName: System.Xaml.XamlReaderSettings
  type: Class
  summary: "規則の処理またはのオプション設定を指定します、 <xref href=&quot;System.Xaml.XamlReader&quot;> </xref>実装します。"
  remarks: "既定では、初期化された XamlReaderSettings オブジェクトを使用して値のプロパティに対応する必要があるの既定値などの`false`のブール型プロパティまたは参照型のプロパティの null 値です。 既定の初期化が、次の値になります: -<xref:System.Xaml.XamlReaderSettings.BaseUri%2A>と<xref:System.Xaml.XamlReaderSettings.LocalAssembly%2A>プロパティは、 `null`</xref:System.Xaml.XamlReaderSettings.LocalAssembly%2A> </xref:System.Xaml.XamlReaderSettings.BaseUri%2A> 。      -<xref:System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements%2A>プロパティは`false`</xref:System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements%2A>。      -<xref:System.Xaml.XamlReaderSettings.ProvideLineInfo%2A>プロパティが`false`オブジェクト モデルですただし、そのことができますをに設定する`true`読み込まれた実行可能ファイルとそのデバッグ設定、または XAML スキーマ コンテキストに基づいて実行時にします。</xref:System.Xaml.XamlReaderSettings.ProvideLineInfo%2A> 。"
  syntax:
    content: public class XamlReaderSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: XamlReaderSettings()
  nameWithType: XamlReaderSettings.XamlReaderSettings()
  fullName: System.Xaml.XamlReaderSettings.XamlReaderSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Xaml.XamlReaderSettings&quot;> </xref>クラスです。"
  remarks: "詳細については<xref:System.Xaml.XamlReaderSettings>既定のインスタンス、 <xref:System.Xaml.XamlReaderSettings>。</xref:System.Xaml.XamlReaderSettings>を参照してください</xref:System.Xaml.XamlReaderSettings>の初期化"
  syntax:
    content: public XamlReaderSettings ();
    parameters: []
  overload: System.Xaml.XamlReaderSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.#ctor(System.Xaml.XamlReaderSettings)
  id: '#ctor(System.Xaml.XamlReaderSettings)'
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: XamlReaderSettings(XamlReaderSettings)
  nameWithType: XamlReaderSettings.XamlReaderSettings(XamlReaderSettings)
  fullName: System.Xaml.XamlReaderSettings.XamlReaderSettings(XamlReaderSettings)
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Xaml.XamlReaderSettings&quot;> </xref>クラスが別の値に基づいた<xref href=&quot;System.Xaml.XamlReaderSettings&quot;></xref>オブジェクト。"
  remarks: "このコンス トラクターは、ここで追加の設定もリーダー処理で他の参加者からの XAML リーダーの設定の結合をサポートします。"
  syntax:
    content: public XamlReaderSettings (System.Xaml.XamlReaderSettings settings);
    parameters:
    - id: settings
      type: System.Xaml.XamlReaderSettings
      description: "既存の<xref href=&quot;System.Xaml.XamlReaderSettings&quot;></xref>オブジェクト。"
  overload: System.Xaml.XamlReaderSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  id: AllowProtectedMembersOnRoot
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: AllowProtectedMembersOnRoot
  nameWithType: XamlReaderSettings.AllowProtectedMembersOnRoot
  fullName: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "取得またはルート オブジェクトを XAML 型の表現を報告したときに、保護されているコード アクセス モデルを持つメンバーを含めることがあるかどうかを示す値を設定します。"
  remarks: "この設定は、ルート オブジェクトが常に実用的なオブジェクト インスタンスがパターンの種類ではないときに、パターンの種類からインスタンスを生成するための「ファクトリ」では多くの場合、WPF などの一部の XAML 実装。 ルートなど`UserControl`WPF と Silverlight アプリケーション モデルでは、特定の意味を持つと`UserControl`プロパティが保護されている可能性があります (`UserControl.Content`) パーサーがへのアクセスを必要があること。 ツールおよびデザイン サーフェイスは、このようなプロパティへのアクセスも必要です。 このような場合必要があります通常として報告される XAML 型システムに書き込み可能なプロパティ、バッキング型システムでアクセスが保護されている場合でも。"
  syntax:
    content: public bool AllowProtectedMembersOnRoot { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>場合は、ルート オブジェクトには、保護されているコード アクセス モデル; を持つメンバーが含まれますそれ以外の場合、 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>です。"
  overload: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.BaseUri
  id: BaseUri
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: BaseUri
  nameWithType: XamlReaderSettings.BaseUri
  fullName: System.Xaml.XamlReaderSettings.BaseUri
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "取得または相対パスを解決するために使用されるベース URI を設定します。"
  remarks: ".NET Framework XAML サービス API の一部の URI に関連するプロパティは、XAML 名前空間の Uri を文字列として扱うただし、このプロパティは、true を使用<xref:System.Uri>型です</xref:System.Uri>。"
  syntax:
    content: public Uri BaseUri { get; set; }
    return:
      type: System.Uri
      description: "使用するベース URI。 既定値は<xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>です。"
  overload: System.Xaml.XamlReaderSettings.BaseUri*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  id: IgnoreUidsOnPropertyElements
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: IgnoreUidsOnPropertyElements
  nameWithType: XamlReaderSettings.IgnoreUidsOnPropertyElements
  fullName: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "XAML リーダーがの値を無視する必要があるかどうかを指定する値の設定を取得または<xref uid=&quot;langword_csharp_x:Uid&quot; name=&quot;x:Uid&quot; href=&quot;&quot;></xref>プロパティ要素に存在する属性。"
  remarks: "ローカリゼーション、中に、`x:Uid`ローカリゼーション ツールは、ローカリゼーション用の個別のエンティティとして XAML 要素を処理できるように、マークアップ内の要素を識別する属性を使用します。 属性は、通常は xaml プロパティ要素の表示されません。 ただし、`x:Uid`が例外いくつかの使用法配置プロパティ要素のローカライズされたテキスト コンテンツとしての代わりに受け取ることのできる個別のオブジェクトとして独自`x:Uid`です。 IgnoreUidsOnPropertyElements 値を設定する`true`より厳密なモードを有効にします。 既定値の`false`プロパティ要素の処理を継続する`x:Uid`属性。"
  syntax:
    content: public bool IgnoreUidsOnPropertyElements { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>リーダーの値を無視する場合<xref uid=&quot;langword_csharp_x:Uid&quot; name=&quot;x:Uid&quot; href=&quot;&quot;></xref>プロパティ要素の属性です。 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>リーダーが処理する場合は<xref uid=&quot;langword_csharp_x:Uid&quot; name=&quot;x:Uid&quot; href=&quot;&quot;></xref>プロパティ要素の属性です。 既定値は<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>です。"
  overload: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.LocalAssembly
  id: LocalAssembly
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: LocalAssembly
  nameWithType: XamlReaderSettings.LocalAssembly
  fullName: System.Xaml.XamlReaderSettings.LocalAssembly
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "取得または設定を処理するため、現在のローカル アセンブリを表すオブジェクト。 このアセンブリ情報がなどのヘルパー Api への呼び出しに使用が&lt;xref:System.Xaml.XamlType.GetAllMembers%2A?displayProperty=fullName&gt;です。"
  syntax:
    content: public System.Reflection.Assembly LocalAssembly { get; set; }
    return:
      type: System.Reflection.Assembly
      description: "CLR リフレクション<xref:System.Reflection.Assembly>オブジェクト</xref:System.Reflection.Assembly>。"
  overload: System.Xaml.XamlReaderSettings.LocalAssembly*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.ProvideLineInfo
  id: ProvideLineInfo
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: ProvideLineInfo
  nameWithType: XamlReaderSettings.ProvideLineInfo
  fullName: System.Xaml.XamlReaderSettings.ProvideLineInfo
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "取得または行番号と位置にリーダーを提供できるかどうかを指定する値を設定します。"
  remarks: "ProvideLineInfo は`false`オブジェクト モデルです。 ただし、そのことができますをに設定する`true`読み込まれた実行可能ファイルとそのデバッグ設定に基づいて実行時にします。"
  syntax:
    content: public bool ProvideLineInfo { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>リーダーは、行番号および位置情報を提供できる場合それ以外の場合、 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>です。"
  overload: System.Xaml.XamlReaderSettings.ProvideLineInfo*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.ValuesMustBeString
  id: ValuesMustBeString
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: ValuesMustBeString
  nameWithType: XamlReaderSettings.ValuesMustBeString
  fullName: System.Xaml.XamlReaderSettings.ValuesMustBeString
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "リーダーを強制するかどうかを指定する値の設定を取得またはすべて<xref uid=&quot;langword_csharp_Value&quot; name=&quot;Value&quot; href=&quot;&quot;></xref>としてのノードが処理される、 <xref uid=&quot;langword_csharp_String&quot; name=&quot;String&quot; href=&quot;&quot;> </xref>型です。"
  remarks: "加え<xref:System.String>、ことがある`Value`一部の XAML 実装の下にあるコンテンツが<xref:System.Windows.Markup.XData>.</xref:System.Windows.Markup.XData> </xref:System.String>"
  syntax:
    content: public bool ValuesMustBeString { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>場合は、リーダーを強制のみ<xref uid=&quot;langword_csharp_String&quot; name=&quot;String&quot; href=&quot;&quot;></xref>に含まれる<xref uid=&quot;langword_csharp_Value&quot; name=&quot;Value&quot; href=&quot;&quot;></xref>ノード以外の場合、 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>です。 既定値は<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>です。"
  overload: System.Xaml.XamlReaderSettings.ValuesMustBeString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Xaml.XamlReaderSettings.#ctor
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: XamlReaderSettings()
  nameWithType: XamlReaderSettings.XamlReaderSettings()
  fullName: System.Xaml.XamlReaderSettings.XamlReaderSettings()
- uid: System.Xaml.XamlReaderSettings.#ctor(System.Xaml.XamlReaderSettings)
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: XamlReaderSettings(XamlReaderSettings)
  nameWithType: XamlReaderSettings.XamlReaderSettings(XamlReaderSettings)
  fullName: System.Xaml.XamlReaderSettings.XamlReaderSettings(XamlReaderSettings)
- uid: System.Xaml.XamlReaderSettings
  parent: System.Xaml
  isExternal: false
  name: XamlReaderSettings
  nameWithType: XamlReaderSettings
  fullName: System.Xaml.XamlReaderSettings
- uid: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: AllowProtectedMembersOnRoot
  nameWithType: XamlReaderSettings.AllowProtectedMembersOnRoot
  fullName: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlReaderSettings.BaseUri
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: BaseUri
  nameWithType: XamlReaderSettings.BaseUri
  fullName: System.Xaml.XamlReaderSettings.BaseUri
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: IgnoreUidsOnPropertyElements
  nameWithType: XamlReaderSettings.IgnoreUidsOnPropertyElements
  fullName: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
- uid: System.Xaml.XamlReaderSettings.LocalAssembly
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: LocalAssembly
  nameWithType: XamlReaderSettings.LocalAssembly
  fullName: System.Xaml.XamlReaderSettings.LocalAssembly
- uid: System.Reflection.Assembly
  parent: System.Reflection
  isExternal: true
  name: Assembly
  nameWithType: Assembly
  fullName: System.Reflection.Assembly
- uid: System.Xaml.XamlReaderSettings.ProvideLineInfo
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: ProvideLineInfo
  nameWithType: XamlReaderSettings.ProvideLineInfo
  fullName: System.Xaml.XamlReaderSettings.ProvideLineInfo
- uid: System.Xaml.XamlReaderSettings.ValuesMustBeString
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: ValuesMustBeString
  nameWithType: XamlReaderSettings.ValuesMustBeString
  fullName: System.Xaml.XamlReaderSettings.ValuesMustBeString
- uid: System.Xaml.XamlReaderSettings.#ctor*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: XamlReaderSettings
  nameWithType: XamlReaderSettings.XamlReaderSettings
- uid: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: AllowProtectedMembersOnRoot
  nameWithType: XamlReaderSettings.AllowProtectedMembersOnRoot
- uid: System.Xaml.XamlReaderSettings.BaseUri*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: BaseUri
  nameWithType: XamlReaderSettings.BaseUri
- uid: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: IgnoreUidsOnPropertyElements
  nameWithType: XamlReaderSettings.IgnoreUidsOnPropertyElements
- uid: System.Xaml.XamlReaderSettings.LocalAssembly*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: LocalAssembly
  nameWithType: XamlReaderSettings.LocalAssembly
- uid: System.Xaml.XamlReaderSettings.ProvideLineInfo*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: ProvideLineInfo
  nameWithType: XamlReaderSettings.ProvideLineInfo
- uid: System.Xaml.XamlReaderSettings.ValuesMustBeString*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: ValuesMustBeString
  nameWithType: XamlReaderSettings.ValuesMustBeString
