### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.WebHttpSecurity
  id: WebHttpSecurity
  children:
  - System.ServiceModel.WebHttpSecurity.#ctor
  - System.ServiceModel.WebHttpSecurity.Mode
  - System.ServiceModel.WebHttpSecurity.ShouldSerializeMode
  - System.ServiceModel.WebHttpSecurity.ShouldSerializeTransport
  - System.ServiceModel.WebHttpSecurity.Transport
  langs:
  - csharp
  name: WebHttpSecurity
  nameWithType: WebHttpSecurity
  fullName: System.ServiceModel.WebHttpSecurity
  type: Class
  summary: "HTTP 要求を受信するように構成するサービス エンドポイントで使用できるセキュリティの種類を指定します。"
  remarks: "WebHttpSecurity <xref:System.ServiceModel.WebHttpBinding>。</xref:System.ServiceModel.WebHttpBinding>で構成されるエンドポイントのセキュリティ要件を提供します。       場合、<xref:System.ServiceModel.WebHttpSecurityMode>値を指定して、<xref:System.ServiceModel.WebHttpBinding.%23ctor%28System.ServiceModel.WebHttpSecurityMode%29>メソッド後で指定される設定、<xref:System.ServiceModel.WebHttpSecurity.Transport%2A>プロパティは、サービス エンドポイントを有効になります</xref:System.ServiceModel.WebHttpSecurity.Transport%2A></xref:System.ServiceModel.WebHttpBinding.%23ctor%28System.ServiceModel.WebHttpSecurityMode%29></xref:System.ServiceModel.WebHttpSecurityMode>。 値<xref:System.ServiceModel.WebHttpSecurityMode>でのみ設定することができます、<xref:System.ServiceModel.WebHttpBinding>を明示的なパラメーターとその値は再び設定できませんバインディング インスタンスが作成された後、それを受け取るコンス トラクター</xref:System.ServiceModel.WebHttpBinding> </xref:System.ServiceModel.WebHttpSecurityMode> 。"
  syntax:
    content: public sealed class WebHttpSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.WebHttpSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.WebHttpSecurity
  langs:
  - csharp
  name: WebHttpSecurity()
  nameWithType: WebHttpSecurity.WebHttpSecurity()
  fullName: System.ServiceModel.WebHttpSecurity.WebHttpSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel
  summary: "新しいインスタンスを作成、 <xref href=&quot;System.ServiceModel.WebHttpSecurity&quot;> </xref>クラスです。"
  syntax:
    content: public WebHttpSecurity ();
    parameters: []
  overload: System.ServiceModel.WebHttpSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WebHttpSecurity.Mode
  id: Mode
  parent: System.ServiceModel.WebHttpSecurity
  langs:
  - csharp
  name: Mode
  nameWithType: WebHttpSecurity.Mode
  fullName: System.ServiceModel.WebHttpSecurity.Mode
  type: Property
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel
  summary: "取得または設定に HTTP 要求を受信するように構成エンドポイントによって使用されるセキュリティのモード、 <xref href=&quot;System.ServiceModel.WebHttpBinding&quot;></xref>です。"
  remarks: "このプロパティを決定するかどうかの設定、<xref:System.ServiceModel.WebHttpSecurity.Transport%2A>プロパティを有効になります</xref:System.ServiceModel.WebHttpSecurity.Transport%2A>。"
  syntax:
    content: public System.ServiceModel.WebHttpSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.WebHttpSecurityMode
      description: "値、 <xref href=&quot;System.ServiceModel.WebHttpSecurityMode&quot;> </xref>エンドポイントによってトランスポート レベルのセキュリティまたはセキュリティが使用されるかどうかを示すです。 既定値は<xref href=&quot;System.ServiceModel.WebHttpSecurityMode&quot;></xref>です。"
  overload: System.ServiceModel.WebHttpSecurity.Mode*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "値が有効な<xref href=&quot;System.ServiceModel.WebHttpSecurityMode&quot;></xref>です。"
  platform:
  - net462
- uid: System.ServiceModel.WebHttpSecurity.ShouldSerializeMode
  id: ShouldSerializeMode
  parent: System.ServiceModel.WebHttpSecurity
  langs:
  - csharp
  name: ShouldSerializeMode()
  nameWithType: WebHttpSecurity.ShouldSerializeMode()
  fullName: System.ServiceModel.WebHttpSecurity.ShouldSerializeMode()
  type: Method
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel
  summary: "指定するかどうか、<xref:System.ServiceModel.WebHttpSecurity.Mode*>プロパティが既定値から変更し、シリアル化する必要があります</xref:System.ServiceModel.WebHttpSecurity.Mode*>。 これは、XAML 統合に使用されます。"
  syntax:
    content: public bool ShouldSerializeMode ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>場合、<xref:System.ServiceModel.WebHttpSecurity.Mode*>プロパティの値が、それ以外のシリアル化する必要があります<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref></xref:System.ServiceModel.WebHttpSecurity.Mode*> 。"
  overload: System.ServiceModel.WebHttpSecurity.ShouldSerializeMode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WebHttpSecurity.ShouldSerializeTransport
  id: ShouldSerializeTransport
  parent: System.ServiceModel.WebHttpSecurity
  langs:
  - csharp
  name: ShouldSerializeTransport()
  nameWithType: WebHttpSecurity.ShouldSerializeTransport()
  fullName: System.ServiceModel.WebHttpSecurity.ShouldSerializeTransport()
  type: Method
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel
  summary: "トランスポートのプロパティが既定値から変更され、シリアル化するかどうかを示す値を返します。 WCF によって XAML 統合に使用されます。"
  syntax:
    content: public bool ShouldSerializeTransport ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>場合、<xref:System.ServiceModel.WebHttpSecurity.Transport*>プロパティの値が、それ以外のシリアル化する必要があります<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref></xref:System.ServiceModel.WebHttpSecurity.Transport*> 。"
  overload: System.ServiceModel.WebHttpSecurity.ShouldSerializeTransport*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WebHttpSecurity.Transport
  id: Transport
  parent: System.ServiceModel.WebHttpSecurity
  langs:
  - csharp
  name: Transport
  nameWithType: WebHttpSecurity.Transport
  fullName: System.ServiceModel.WebHttpSecurity.Transport
  type: Property
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel
  summary: "このバインディングのトランスポート レベルのセキュリティ設定を格納しているオブジェクトを取得します。"
  remarks: "<xref:System.ServiceModel.HttpTransportSecurity> <xref:System.ServiceModel.WebHttpBinding>。</xref:System.ServiceModel.WebHttpBinding>のトランスポート セキュリティのパラメーターを設定するには、このプロパティによって返されるオブジェクト</xref:System.ServiceModel.HttpTransportSecurity>の使用します。       場合、<xref:System.ServiceModel.WebHttpSecurityMode>または<xref:System.ServiceModel.WebHttpSecurityMode>値を指定して、<xref:System.ServiceModel.WebHttpBinding.%23ctor%28System.ServiceModel.WebHttpSecurityMode%29>メソッド、サービス エンドポイントを有効になるトランスポートのプロパティによって指定される設定</xref:System.ServiceModel.WebHttpBinding.%23ctor%28System.ServiceModel.WebHttpSecurityMode%29></xref:System.ServiceModel.WebHttpSecurityMode></xref:System.ServiceModel.WebHttpSecurityMode>。       場合、<xref:System.ServiceModel.WebHttpSecurityMode>値を指定して、<xref:System.ServiceModel.WebHttpBinding.%23ctor%28System.ServiceModel.WebHttpSecurityMode%29>メソッド、サービス エンドポイントを有効になるトランスポートのプロパティによって指定される設定</xref:System.ServiceModel.WebHttpBinding.%23ctor%28System.ServiceModel.WebHttpSecurityMode%29></xref:System.ServiceModel.WebHttpSecurityMode>。 値<xref:System.ServiceModel.WebHttpSecurityMode>でのみ設定することができます、<xref:System.ServiceModel.WebHttpBinding>を明示的なパラメーターとその値は再び設定できませんバインディング インスタンスが作成された後、それを受け取るコンス トラクター</xref:System.ServiceModel.WebHttpBinding> </xref:System.ServiceModel.WebHttpSecurityMode> 。"
  syntax:
    content: public System.ServiceModel.HttpTransportSecurity Transport { get; set; }
    return:
      type: System.ServiceModel.HttpTransportSecurity
      description: "<xref:System.ServiceModel.HttpTransportSecurity>このバインディングの</xref:System.ServiceModel.HttpTransportSecurity>。       既定値の設定は、 <> </> *> の<xref:System.ServiceModel.HttpClientCredentialType>、 <> </> *> の<xref href=&quot;System.ServiceModel.HttpProxyCredentialType&quot;> </xref>、および<xref:System.ServiceModel.HttpTransportSecurity.Realm*>=&quot;&quot;です</xref:System.ServiceModel.HttpTransportSecurity.Realm*></xref:System.ServiceModel.HttpClientCredentialType>。"
  overload: System.ServiceModel.WebHttpSecurity.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.WebHttpSecurity.#ctor
  parent: System.ServiceModel.WebHttpSecurity
  isExternal: false
  name: WebHttpSecurity()
  nameWithType: WebHttpSecurity.WebHttpSecurity()
  fullName: System.ServiceModel.WebHttpSecurity.WebHttpSecurity()
- uid: System.ServiceModel.WebHttpSecurity.Mode
  parent: System.ServiceModel.WebHttpSecurity
  isExternal: false
  name: Mode
  nameWithType: WebHttpSecurity.Mode
  fullName: System.ServiceModel.WebHttpSecurity.Mode
- uid: System.ServiceModel.WebHttpSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: WebHttpSecurityMode
  nameWithType: WebHttpSecurityMode
  fullName: System.ServiceModel.WebHttpSecurityMode
- uid: System.ServiceModel.WebHttpSecurity.ShouldSerializeMode
  parent: System.ServiceModel.WebHttpSecurity
  isExternal: false
  name: ShouldSerializeMode()
  nameWithType: WebHttpSecurity.ShouldSerializeMode()
  fullName: System.ServiceModel.WebHttpSecurity.ShouldSerializeMode()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.WebHttpSecurity.ShouldSerializeTransport
  parent: System.ServiceModel.WebHttpSecurity
  isExternal: false
  name: ShouldSerializeTransport()
  nameWithType: WebHttpSecurity.ShouldSerializeTransport()
  fullName: System.ServiceModel.WebHttpSecurity.ShouldSerializeTransport()
- uid: System.ServiceModel.WebHttpSecurity.Transport
  parent: System.ServiceModel.WebHttpSecurity
  isExternal: false
  name: Transport
  nameWithType: WebHttpSecurity.Transport
  fullName: System.ServiceModel.WebHttpSecurity.Transport
- uid: System.ServiceModel.HttpTransportSecurity
  parent: System.ServiceModel
  isExternal: true
  name: HttpTransportSecurity
  nameWithType: HttpTransportSecurity
  fullName: System.ServiceModel.HttpTransportSecurity
- uid: System.ServiceModel.WebHttpSecurity.#ctor*
  parent: System.ServiceModel.WebHttpSecurity
  isExternal: false
  name: WebHttpSecurity
  nameWithType: WebHttpSecurity.WebHttpSecurity
- uid: System.ServiceModel.WebHttpSecurity.Mode*
  parent: System.ServiceModel.WebHttpSecurity
  isExternal: false
  name: Mode
  nameWithType: WebHttpSecurity.Mode
- uid: System.ServiceModel.WebHttpSecurity.ShouldSerializeMode*
  parent: System.ServiceModel.WebHttpSecurity
  isExternal: false
  name: ShouldSerializeMode
  nameWithType: WebHttpSecurity.ShouldSerializeMode
- uid: System.ServiceModel.WebHttpSecurity.ShouldSerializeTransport*
  parent: System.ServiceModel.WebHttpSecurity
  isExternal: false
  name: ShouldSerializeTransport
  nameWithType: WebHttpSecurity.ShouldSerializeTransport
- uid: System.ServiceModel.WebHttpSecurity.Transport*
  parent: System.ServiceModel.WebHttpSecurity
  isExternal: false
  name: Transport
  nameWithType: WebHttpSecurity.Transport
