### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ExtensionElement
  id: ExtensionElement
  children:
  - System.ServiceModel.Configuration.ExtensionElement.#ctor
  - System.ServiceModel.Configuration.ExtensionElement.#ctor(System.String)
  - System.ServiceModel.Configuration.ExtensionElement.#ctor(System.String,System.String)
  - System.ServiceModel.Configuration.ExtensionElement.Name
  - System.ServiceModel.Configuration.ExtensionElement.Properties
  - System.ServiceModel.Configuration.ExtensionElement.Type
  langs:
  - csharp
  name: ExtensionElement
  nameWithType: ExtensionElement
  fullName: System.ServiceModel.Configuration.ExtensionElement
  type: Class
  summary: "ユーザーがユーザー定義のバインディングや動作などを作成できるように拡張機能を定義する構成要素を表します。"
  syntax:
    content: 'public class ExtensionElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ExtensionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ExtensionElement
  langs:
  - csharp
  name: ExtensionElement()
  nameWithType: ExtensionElement.ExtensionElement()
  fullName: System.ServiceModel.Configuration.ExtensionElement.ExtensionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.ServiceModel.Configuration.ExtensionElement&quot;> </xref>クラスです。"
  syntax:
    content: public ExtensionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ExtensionElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ExtensionElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.ExtensionElement
  langs:
  - csharp
  name: ExtensionElement(String)
  nameWithType: ExtensionElement.ExtensionElement(String)
  fullName: System.ServiceModel.Configuration.ExtensionElement.ExtensionElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.ServiceModel.Configuration.ExtensionElement&quot;> </xref>指定した名前のクラスです。"
  syntax:
    content: public ExtensionElement (string name);
    parameters:
    - id: name
      type: System.String
      description: "この構成要素の一意の名前。"
  overload: System.ServiceModel.Configuration.ExtensionElement.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>name</code><xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>または空です。"
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ExtensionElement.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.ServiceModel.Configuration.ExtensionElement
  langs:
  - csharp
  name: ExtensionElement(String,String)
  nameWithType: ExtensionElement.ExtensionElement(String,String)
  fullName: System.ServiceModel.Configuration.ExtensionElement.ExtensionElement(String,String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.ServiceModel.Configuration.ExtensionElement&quot;> </xref>クラスを指定した名前と型を使用します。"
  syntax:
    content: public ExtensionElement (string name, string type);
    parameters:
    - id: name
      type: System.String
      description: "この構成要素の一意の名前。"
    - id: type
      type: System.String
      description: "この構成要素の型。"
  overload: System.ServiceModel.Configuration.ExtensionElement.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>type</code><xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>または空です。       -or-       <code>name</code> is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref> or empty."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ExtensionElement.Name
  id: Name
  parent: System.ServiceModel.Configuration.ExtensionElement
  langs:
  - csharp
  name: Name
  nameWithType: ExtensionElement.Name
  fullName: System.ServiceModel.Configuration.ExtensionElement.Name
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得または、この構成要素の一意の名前を設定します。"
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "この構成要素の一意の名前。"
  overload: System.ServiceModel.Configuration.ExtensionElement.Name*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ExtensionElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ExtensionElement
  langs:
  - csharp
  name: Properties
  nameWithType: ExtensionElement.Properties
  fullName: System.ServiceModel.Configuration.ExtensionElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得、 <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref>インスタンスのコレクションを含む<xref href=&quot;System.Configuration.ConfigurationProperty&quot;></xref>属性を保持できるオブジェクトまたは<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>この構成要素のオブジェクト。"
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref>インスタンスのコレクションを含む<xref href=&quot;System.Configuration.ConfigurationProperty&quot;></xref>属性を保持できるオブジェクトまたは<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>この構成要素のオブジェクト。"
  overload: System.ServiceModel.Configuration.ExtensionElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ExtensionElement.Type
  id: Type
  parent: System.ServiceModel.Configuration.ExtensionElement
  langs:
  - csharp
  name: Type
  nameWithType: ExtensionElement.Type
  fullName: System.ServiceModel.Configuration.ExtensionElement.Type
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得または、この構成要素の型を設定します。"
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "この構成要素の型。"
  overload: System.ServiceModel.Configuration.ExtensionElement.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ServiceModel.Configuration.ExtensionElement.#ctor
  parent: System.ServiceModel.Configuration.ExtensionElement
  isExternal: false
  name: ExtensionElement()
  nameWithType: ExtensionElement.ExtensionElement()
  fullName: System.ServiceModel.Configuration.ExtensionElement.ExtensionElement()
- uid: System.ServiceModel.Configuration.ExtensionElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.ExtensionElement
  isExternal: false
  name: ExtensionElement(String)
  nameWithType: ExtensionElement.ExtensionElement(String)
  fullName: System.ServiceModel.Configuration.ExtensionElement.ExtensionElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.ExtensionElement.#ctor(System.String,System.String)
  parent: System.ServiceModel.Configuration.ExtensionElement
  isExternal: false
  name: ExtensionElement(String,String)
  nameWithType: ExtensionElement.ExtensionElement(String,String)
  fullName: System.ServiceModel.Configuration.ExtensionElement.ExtensionElement(String,String)
- uid: System.ServiceModel.Configuration.ExtensionElement.Name
  parent: System.ServiceModel.Configuration.ExtensionElement
  isExternal: false
  name: Name
  nameWithType: ExtensionElement.Name
  fullName: System.ServiceModel.Configuration.ExtensionElement.Name
- uid: System.ServiceModel.Configuration.ExtensionElement.Properties
  parent: System.ServiceModel.Configuration.ExtensionElement
  isExternal: false
  name: Properties
  nameWithType: ExtensionElement.Properties
  fullName: System.ServiceModel.Configuration.ExtensionElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ExtensionElement.Type
  parent: System.ServiceModel.Configuration.ExtensionElement
  isExternal: false
  name: Type
  nameWithType: ExtensionElement.Type
  fullName: System.ServiceModel.Configuration.ExtensionElement.Type
- uid: System.ServiceModel.Configuration.ExtensionElement.#ctor*
  parent: System.ServiceModel.Configuration.ExtensionElement
  isExternal: false
  name: ExtensionElement
  nameWithType: ExtensionElement.ExtensionElement
- uid: System.ServiceModel.Configuration.ExtensionElement.Name*
  parent: System.ServiceModel.Configuration.ExtensionElement
  isExternal: false
  name: Name
  nameWithType: ExtensionElement.Name
- uid: System.ServiceModel.Configuration.ExtensionElement.Properties*
  parent: System.ServiceModel.Configuration.ExtensionElement
  isExternal: false
  name: Properties
  nameWithType: ExtensionElement.Properties
- uid: System.ServiceModel.Configuration.ExtensionElement.Type*
  parent: System.ServiceModel.Configuration.ExtensionElement
  isExternal: false
  name: Type
  nameWithType: ExtensionElement.Type
