### YamlMime:ManagedReference
items:
- uid: System.Activities.Validation.ValidationSettings
  id: ValidationSettings
  children:
  - System.Activities.Validation.ValidationSettings.#ctor
  - System.Activities.Validation.ValidationSettings.AdditionalConstraints
  - System.Activities.Validation.ValidationSettings.CancellationToken
  - System.Activities.Validation.ValidationSettings.Environment
  - System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints
  - System.Activities.Validation.ValidationSettings.PrepareForRuntime
  - System.Activities.Validation.ValidationSettings.SingleLevel
  - System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration
  langs:
  - csharp
  name: ValidationSettings
  nameWithType: ValidationSettings
  fullName: System.Activities.Validation.ValidationSettings
  type: Class
  summary: "動作をカスタマイズする設定のコレクションを表すを<xref:System.Activities.Validation.ActivityValidationServices.Validate*>は発生します</xref:System.Activities.Validation.ActivityValidationServices.Validate*>。 アクティビティのユーザー ワークフローにポリシー制約を適用することもできます。"
  syntax:
    content: public class ValidationSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Activities.Validation.ValidationSettings.#ctor
  id: '#ctor'
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: ValidationSettings()
  nameWithType: ValidationSettings.ValidationSettings()
  fullName: System.Activities.Validation.ValidationSettings.ValidationSettings()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: "新しいインスタンスを作成、 <xref href=&quot;System.Activities.Validation.ValidationSettings&quot;> </xref>クラスです。"
  syntax:
    content: public ValidationSettings ();
    parameters: []
  overload: System.Activities.Validation.ValidationSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.Validation.ValidationSettings.AdditionalConstraints
  id: AdditionalConstraints
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: AdditionalConstraints
  nameWithType: ValidationSettings.AdditionalConstraints
  fullName: System.Activities.Validation.ValidationSettings.AdditionalConstraints
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: "型制約のペアのディクショナリを取得します。 ディクショナリに追加された各制約を検証するワークフローの指定された型の各アクティビティに使用されます。"
  syntax:
    content: public System.Collections.Generic.IDictionary<Type,System.Collections.Generic.IList<System.Activities.Validation.Constraint>> AdditionalConstraints { get; }
    return:
      type: System.Collections.Generic.IDictionary{System.Type,System.Collections.Generic.IList{System.Activities.Validation.Constraint}}
      description: "制約と型のディクショナリ型一覧。"
  overload: System.Activities.Validation.ValidationSettings.AdditionalConstraints*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.Validation.ValidationSettings.CancellationToken
  id: CancellationToken
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: CancellationToken
  nameWithType: ValidationSettings.CancellationToken
  fullName: System.Activities.Validation.ValidationSettings.CancellationToken
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: "取得またはキャンセル トークンを使用して、アクティビティを取り消す通知を設定します。"
  syntax:
    content: public System.Threading.CancellationToken CancellationToken { get; set; }
    return:
      type: System.Threading.CancellationToken
      description: "アクティビティをキャンセルできる必要がありますに通知するために使用するキャンセル トークン。"
  overload: System.Activities.Validation.ValidationSettings.CancellationToken*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.Validation.ValidationSettings.Environment
  id: Environment
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: Environment
  nameWithType: ValidationSettings.Environment
  fullName: System.Activities.Validation.ValidationSettings.Environment
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: "取得または、この検証の設定に関連付けられている引数および変数の環境を設定します。"
  syntax:
    content: public System.Activities.LocationReferenceEnvironment Environment { get; set; }
    return:
      type: System.Activities.LocationReferenceEnvironment
      description: "この検証の設定に関連付けられている引数および変数の環境。"
  overload: System.Activities.Validation.ValidationSettings.Environment*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints
  id: OnlyUseAdditionalConstraints
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: OnlyUseAdditionalConstraints
  nameWithType: ValidationSettings.OnlyUseAdditionalConstraints
  fullName: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: "取得または追加の検証制約が、ワークフローの検証に排他的に使用するかどうかを示す値を設定します。 場合設定<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>、アクティビティ自体の内部に含まれるすべての検証は無視されます。"
  remarks: "<xref:System.Activities.Validation.ActivityValidationServices.Validate%2A>ワークフローが実行されるたびに呼び出されると、生成されるエラーが発生し、<xref:System.Activities.InvalidWorkflowException>がスローされます</xref:System.Activities.InvalidWorkflowException>。</xref:System.Activities.Validation.ActivityValidationServices.Validate%2A>"
  syntax:
    content: public bool OnlyUseAdditionalConstraints { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>排他的です。 使用する場合は、追加の制約それ以外の場合、 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>です。"
  overload: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.Validation.ValidationSettings.PrepareForRuntime
  id: PrepareForRuntime
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: PrepareForRuntime
  nameWithType: ValidationSettings.PrepareForRuntime
  fullName: System.Activities.Validation.ValidationSettings.PrepareForRuntime
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: "取得またはランタイム用にこのインスタンスを準備するかどうかを示す値を設定します。"
  syntax:
    content: public bool PrepareForRuntime { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_True&quot; name=&quot;True&quot; href=&quot;&quot;></xref>ランタイムのこのインスタンスが準備された場合それ以外の場合、 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>です。"
  overload: System.Activities.Validation.ValidationSettings.PrepareForRuntime*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.Validation.ValidationSettings.SingleLevel
  id: SingleLevel
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: SingleLevel
  nameWithType: ValidationSettings.SingleLevel
  fullName: System.Activities.Validation.ValidationSettings.SingleLevel
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: "取得または設定するかどうか、指定したアクティビティとすべての子と、指定したアクティビティの下位の子が検証されたら、または、指定したアクティビティにのみ検証するバリデーターを示す値。"
  syntax:
    content: public bool SingleLevel { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>その子要素を検証せず、要素は検証されている場合それ以外の場合、 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>要素とその子と孫検証中である場合。"
  overload: System.Activities.Validation.ValidationSettings.SingleLevel*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration
  id: SkipValidatingRootConfiguration
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: SkipValidatingRootConfiguration
  nameWithType: ValidationSettings.SkipValidatingRootConfiguration
  fullName: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: "取得またはルート構成が検証の主題ではないかどうかを示す値を設定します。"
  syntax:
    content: public bool SkipValidatingRootConfiguration { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>ルートの構成が検証の対象でない場合それ以外の場合、 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>です。"
  overload: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Activities.Validation.ValidationSettings.#ctor
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: ValidationSettings()
  nameWithType: ValidationSettings.ValidationSettings()
  fullName: System.Activities.Validation.ValidationSettings.ValidationSettings()
- uid: System.Activities.Validation.ValidationSettings.AdditionalConstraints
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: AdditionalConstraints
  nameWithType: ValidationSettings.AdditionalConstraints
  fullName: System.Activities.Validation.ValidationSettings.AdditionalConstraints
- uid: System.Collections.Generic.IDictionary{System.Type,System.Collections.Generic.IList{System.Activities.Validation.Constraint}}
  parent: System.Collections.Generic
  isExternal: true
  name: IDictionary<Type,IList<Constraint>>
  nameWithType: IDictionary<Type,IList<Constraint>>
  fullName: System.Collections.Generic.IDictionary<System.Type,System.Collections.Generic.IList<System.Activities.Validation.Constraint>>
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    nameWithType: IDictionary
    fullName: IDictionary<System.Type,System.Collections.Generic.IList<System.Activities.Validation.Constraint>>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Type
    name: Type
    nameWithType: Type
    fullName: Type
  - name: ','
    nameWithType: ','
    fullName: ','
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: IList<System.Activities.Validation.Constraint>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Activities.Validation.Constraint
    name: Constraint
    nameWithType: Constraint
    fullName: Constraint
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Activities.Validation.ValidationSettings.CancellationToken
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: CancellationToken
  nameWithType: ValidationSettings.CancellationToken
  fullName: System.Activities.Validation.ValidationSettings.CancellationToken
- uid: System.Threading.CancellationToken
  parent: System.Threading
  isExternal: true
  name: CancellationToken
  nameWithType: CancellationToken
  fullName: System.Threading.CancellationToken
- uid: System.Activities.Validation.ValidationSettings.Environment
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: Environment
  nameWithType: ValidationSettings.Environment
  fullName: System.Activities.Validation.ValidationSettings.Environment
- uid: System.Activities.LocationReferenceEnvironment
  parent: System.Activities
  isExternal: false
  name: LocationReferenceEnvironment
  nameWithType: LocationReferenceEnvironment
  fullName: System.Activities.LocationReferenceEnvironment
- uid: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: OnlyUseAdditionalConstraints
  nameWithType: ValidationSettings.OnlyUseAdditionalConstraints
  fullName: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Activities.Validation.ValidationSettings.PrepareForRuntime
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: PrepareForRuntime
  nameWithType: ValidationSettings.PrepareForRuntime
  fullName: System.Activities.Validation.ValidationSettings.PrepareForRuntime
- uid: System.Activities.Validation.ValidationSettings.SingleLevel
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: SingleLevel
  nameWithType: ValidationSettings.SingleLevel
  fullName: System.Activities.Validation.ValidationSettings.SingleLevel
- uid: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: SkipValidatingRootConfiguration
  nameWithType: ValidationSettings.SkipValidatingRootConfiguration
  fullName: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration
- uid: System.Activities.Validation.ValidationSettings.#ctor*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: ValidationSettings
  nameWithType: ValidationSettings.ValidationSettings
- uid: System.Activities.Validation.ValidationSettings.AdditionalConstraints*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: AdditionalConstraints
  nameWithType: ValidationSettings.AdditionalConstraints
- uid: System.Activities.Validation.ValidationSettings.CancellationToken*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: CancellationToken
  nameWithType: ValidationSettings.CancellationToken
- uid: System.Activities.Validation.ValidationSettings.Environment*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: Environment
  nameWithType: ValidationSettings.Environment
- uid: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: OnlyUseAdditionalConstraints
  nameWithType: ValidationSettings.OnlyUseAdditionalConstraints
- uid: System.Activities.Validation.ValidationSettings.PrepareForRuntime*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: PrepareForRuntime
  nameWithType: ValidationSettings.PrepareForRuntime
- uid: System.Activities.Validation.ValidationSettings.SingleLevel*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: SingleLevel
  nameWithType: ValidationSettings.SingleLevel
- uid: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration*
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: SkipValidatingRootConfiguration
  nameWithType: ValidationSettings.SkipValidatingRootConfiguration
