### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationCollectionAttribute
  id: ConfigurationCollectionAttribute
  children:
  - System.Configuration.ConfigurationCollectionAttribute.#ctor(System.Type)
  - System.Configuration.ConfigurationCollectionAttribute.AddItemName
  - System.Configuration.ConfigurationCollectionAttribute.ClearItemsName
  - System.Configuration.ConfigurationCollectionAttribute.CollectionType
  - System.Configuration.ConfigurationCollectionAttribute.ItemType
  - System.Configuration.ConfigurationCollectionAttribute.RemoveItemName
  langs:
  - csharp
  name: ConfigurationCollectionAttribute
  nameWithType: ConfigurationCollectionAttribute
  fullName: System.Configuration.ConfigurationCollectionAttribute
  type: Class
  summary: "宣言的な構成要素のコレクションのインスタンスを作成する .NET Framework に指示します。 このクラスは継承できません。"
  remarks: "装飾に ConfigurationCollectionAttribute 属性を使用する、<xref:System.Configuration.ConfigurationElementCollection>要素</xref:System.Configuration.ConfigurationElementCollection>。 これにより、.NET Framework コレクションのインスタンスを作成して、ユーザー設定を使用して初期化するために、指示<xref:System.Configuration.ConfigurationElement>値</xref:System.Configuration.ConfigurationElement>。      > [!NOTE] > カスタム構成要素を作成する最も簡単な方法は、属性付きの (宣言) モデルを使用します。 要素を宣言し、ConfigurationCollectionAttribute 属性で装飾にするとします。 この属性でマークされた各要素に対して、.NET Framework リフレクションを使用して装飾のパラメーターを読み取り、および関連する作成<xref:System.Configuration.ConfigurationElementCollection>インスタンス</xref:System.Configuration.ConfigurationElementCollection>。 また、プログラムでモデルを使用することができます。 ここではユーザーの責任は、カスタムのパブリック コレクションを宣言する上書きにも、<xref:System.Configuration.ConfigurationElementCollection>メンバーと戻り値、プロパティのコレクション</xref:System.Configuration.ConfigurationElementCollection>。       .NET Framework 構成システムは、カスタム構成要素を作成するときに使用できる属性の型を提供します。 属性の&2; 種類があります:-.NET Framework の要素のプロパティのカスタム構成のインスタンスを作成する方法を指示する属性。 これらの型を含める: - ConfigurationCollectionAttribute - <xref:System.Configuration.ConfigurationPropertyAttribute>-.NET Framework をカスタム構成要素のプロパティを検証する方法を指示する属性</xref:System.Configuration.ConfigurationPropertyAttribute>。 These types include:          -   <xref:System.Configuration.IntegerValidatorAttribute>          -   <xref:System.Configuration.LongValidatorAttribute>          -   <xref:System.Configuration.RegexStringValidatorAttribute>          -   <xref:System.Configuration.StringValidatorAttribute>          -   <xref:System.Configuration.TimeSpanValidatorAttribute></xref:System.Configuration.TimeSpanValidatorAttribute></xref:System.Configuration.StringValidatorAttribute></xref:System.Configuration.RegexStringValidatorAttribute></xref:System.Configuration.LongValidatorAttribute></xref:System.Configuration.IntegerValidatorAttribute>"
  example:
  - "The following example shows how to use the ConfigurationCollectionAttribute.  \n  \n This example consists of three classes: `UrlsSection`, `UrlsCollection` and `UrlConfigElement`.The `UrlsSection` class uses the ConfigurationCollectionAttribute to define a custom configuration section. This section contains a URL collection (defined by the `UrlsCollection` class) of URL elements (defined by the `UrlConfigElement` class). When you run the example, an instance of the `UrlsSection` class is created and the following configuration elements are generated in the application configuration file:  \n  \n```  \n<configuration>  \n    <configSections>  \n        <section name=\"MyUrls\" type=\"UrlsSection,   \n          ConfigurationCollectionAttribute, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\" />  \n    </configSections>  \n    <MyUrls>  \n        <urls>  \n            <remove name=\"Contoso\" />  \n            <add name=\"Contoso\" url=\"http://www.contoso.com\" port=\"0\" />  \n        </urls>  \n    </MyUrls>  \n</configuration  \n```  \n  \n [!code-cs[System.Configuration.ConfigurationCollectionAttribute#1](~/add/codesnippet/csharp/t-system.configuration.c_7_1.cs)]\n [!code-vb[System.Configuration.ConfigurationCollectionAttribute#1](~/add/codesnippet/visualbasic/t-system.configuration.c_7_1.vb)]  \n  \n [!code-cs[System.Configuration.ConfigurationCollectionAttribute#31](~/add/codesnippet/csharp/t-system.configuration.c_7_2.cs)]\n [!code-vb[System.Configuration.ConfigurationCollectionAttribute#31](~/add/codesnippet/visualbasic/t-system.configuration.c_7_2.vb)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Property)]

      public sealed class ConfigurationCollectionAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationCollectionAttribute.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.Configuration.ConfigurationCollectionAttribute
  langs:
  - csharp
  name: ConfigurationCollectionAttribute(Type)
  nameWithType: ConfigurationCollectionAttribute.ConfigurationCollectionAttribute(Type)
  fullName: System.Configuration.ConfigurationCollectionAttribute.ConfigurationCollectionAttribute(Type)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Configuration.ConfigurationCollectionAttribute&quot;> </xref>クラスです。"
  remarks: "このコンス トラクターを使用して、カスタムの型を作成するプロパティのコレクションの .NET Framework に通知します。"
  example:
  - "The following example shows how to use the ConfigurationCollectionAttribute.  \n  \n [!code-cs[System.Configuration.ConfigurationCollectionAttribute#20](~/add/codesnippet/csharp/m-system.configuration.c_25_1.cs)]\n [!code-vb[System.Configuration.ConfigurationCollectionAttribute#20](~/add/codesnippet/visualbasic/m-system.configuration.c_25_1.vb)]"
  syntax:
    content: public ConfigurationCollectionAttribute (Type itemType);
    parameters:
    - id: itemType
      type: System.Type
      description: "作成するプロパティのコレクションの型。"
  overload: System.Configuration.ConfigurationCollectionAttribute.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>itemType</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.Configuration.ConfigurationCollectionAttribute.AddItemName
  id: AddItemName
  parent: System.Configuration.ConfigurationCollectionAttribute
  langs:
  - csharp
  name: AddItemName
  nameWithType: ConfigurationCollectionAttribute.AddItemName
  fullName: System.Configuration.ConfigurationCollectionAttribute.AddItemName
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "取得または設定の名前、 <xref uid=&quot;langword_csharp_&lt;add&gt;&quot; name=&quot;&lt;add&gt;&quot; href=&quot;&quot;> </xref>構成要素。"
  remarks: "AddItemName プロパティでは、別の名前を構成要素に代入することができます。 たとえば、使用する`addUrl`「追加」の代わりにします。"
  example:
  - "The following example shows how to use the AddItemName property.  \n  \n [!code-cs[System.Configuration.ConfigurationCollectionAttribute#20](~/add/codesnippet/csharp/p-system.configuration.c_47_1.cs)]\n [!code-vb[System.Configuration.ConfigurationCollectionAttribute#20](~/add/codesnippet/visualbasic/p-system.configuration.c_47_1.vb)]"
  syntax:
    content: public string AddItemName { get; set; }
    return:
      type: System.String
      description: "標準の名前に置き換えて名前「追加」for the configuration item します。"
  overload: System.Configuration.ConfigurationCollectionAttribute.AddItemName*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationCollectionAttribute.ClearItemsName
  id: ClearItemsName
  parent: System.Configuration.ConfigurationCollectionAttribute
  langs:
  - csharp
  name: ClearItemsName
  nameWithType: ConfigurationCollectionAttribute.ClearItemsName
  fullName: System.Configuration.ConfigurationCollectionAttribute.ClearItemsName
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "取得または設定の名前、 <xref uid=&quot;langword_csharp_&lt;clear&gt;&quot; name=&quot;&lt;clear&gt;&quot; href=&quot;&quot;> </xref>構成要素。"
  remarks: "ClearItemsName プロパティに別の名前を割り当てることができます、`<clear>`構成要素。 たとえば、使用する`clearUrls`「クリア」の代わりにします。"
  example:
  - "The following example shows how to use the ClearItemsName.  \n  \n [!code-cs[System.Configuration.ConfigurationCollectionAttribute#20](~/add/codesnippet/csharp/p-system.configuration.c_18_1.cs)]\n [!code-vb[System.Configuration.ConfigurationCollectionAttribute#20](~/add/codesnippet/visualbasic/p-system.configuration.c_18_1.vb)]"
  syntax:
    content: public string ClearItemsName { get; set; }
    return:
      type: System.String
      description: "標準の名前を置換する名前「オフ」、構成項目の。"
  overload: System.Configuration.ConfigurationCollectionAttribute.ClearItemsName*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationCollectionAttribute.CollectionType
  id: CollectionType
  parent: System.Configuration.ConfigurationCollectionAttribute
  langs:
  - csharp
  name: CollectionType
  nameWithType: ConfigurationCollectionAttribute.CollectionType
  fullName: System.Configuration.ConfigurationCollectionAttribute.CollectionType
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "取得または設定の種類、 <xref href=&quot;System.Configuration.ConfigurationCollectionAttribute&quot;> </xref>属性。"
  syntax:
    content: public System.Configuration.ConfigurationElementCollectionType CollectionType { get; set; }
    return:
      type: System.Configuration.ConfigurationElementCollectionType
      description: "型、 <xref href=&quot;System.Configuration.ConfigurationCollectionAttribute&quot;></xref>です。"
  overload: System.Configuration.ConfigurationCollectionAttribute.CollectionType*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationCollectionAttribute.ItemType
  id: ItemType
  parent: System.Configuration.ConfigurationCollectionAttribute
  langs:
  - csharp
  name: ItemType
  nameWithType: ConfigurationCollectionAttribute.ItemType
  fullName: System.Configuration.ConfigurationCollectionAttribute.ItemType
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "コレクション要素の型を取得します。"
  remarks: "リフレクションによっては、ItemType プロパティを使用して構成要素の型を取得します。"
  syntax:
    content: public Type ItemType { get; }
    return:
      type: System.Type
      description: "コレクション要素の型。"
  overload: System.Configuration.ConfigurationCollectionAttribute.ItemType*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationCollectionAttribute.RemoveItemName
  id: RemoveItemName
  parent: System.Configuration.ConfigurationCollectionAttribute
  langs:
  - csharp
  name: RemoveItemName
  nameWithType: ConfigurationCollectionAttribute.RemoveItemName
  fullName: System.Configuration.ConfigurationCollectionAttribute.RemoveItemName
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "取得または設定の名前、 <xref uid=&quot;langword_csharp_&lt;remove&gt;&quot; name=&quot;&lt;remove&gt;&quot; href=&quot;&quot;> </xref>構成要素。"
  remarks: "RemoveItemName プロパティに別の名前を割り当てることができます、`<remove>`構成要素。 たとえば、使用する`removeUrl`「削除」の代わりにします。"
  example:
  - "The following example shows how to use the RemoveItemName property.  \n  \n [!code-cs[System.Configuration.ConfigurationCollectionAttribute#20](~/add/codesnippet/csharp/p-system.configuration.c_41_1.cs)]\n [!code-vb[System.Configuration.ConfigurationCollectionAttribute#20](~/add/codesnippet/visualbasic/p-system.configuration.c_41_1.vb)]"
  syntax:
    content: public string RemoveItemName { get; set; }
    return:
      type: System.String
      description: "標準の名前を置換する名前&quot;remove&quot;構成要素のです。"
  overload: System.Configuration.ConfigurationCollectionAttribute.RemoveItemName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.ConfigurationCollectionAttribute.#ctor(System.Type)
  parent: System.Configuration.ConfigurationCollectionAttribute
  isExternal: false
  name: ConfigurationCollectionAttribute(Type)
  nameWithType: ConfigurationCollectionAttribute.ConfigurationCollectionAttribute(Type)
  fullName: System.Configuration.ConfigurationCollectionAttribute.ConfigurationCollectionAttribute(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.ConfigurationCollectionAttribute.AddItemName
  parent: System.Configuration.ConfigurationCollectionAttribute
  isExternal: false
  name: AddItemName
  nameWithType: ConfigurationCollectionAttribute.AddItemName
  fullName: System.Configuration.ConfigurationCollectionAttribute.AddItemName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationCollectionAttribute.ClearItemsName
  parent: System.Configuration.ConfigurationCollectionAttribute
  isExternal: false
  name: ClearItemsName
  nameWithType: ConfigurationCollectionAttribute.ClearItemsName
  fullName: System.Configuration.ConfigurationCollectionAttribute.ClearItemsName
- uid: System.Configuration.ConfigurationCollectionAttribute.CollectionType
  parent: System.Configuration.ConfigurationCollectionAttribute
  isExternal: false
  name: CollectionType
  nameWithType: ConfigurationCollectionAttribute.CollectionType
  fullName: System.Configuration.ConfigurationCollectionAttribute.CollectionType
- uid: System.Configuration.ConfigurationElementCollectionType
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElementCollectionType
  nameWithType: ConfigurationElementCollectionType
  fullName: System.Configuration.ConfigurationElementCollectionType
- uid: System.Configuration.ConfigurationCollectionAttribute.ItemType
  parent: System.Configuration.ConfigurationCollectionAttribute
  isExternal: false
  name: ItemType
  nameWithType: ConfigurationCollectionAttribute.ItemType
  fullName: System.Configuration.ConfigurationCollectionAttribute.ItemType
- uid: System.Configuration.ConfigurationCollectionAttribute.RemoveItemName
  parent: System.Configuration.ConfigurationCollectionAttribute
  isExternal: false
  name: RemoveItemName
  nameWithType: ConfigurationCollectionAttribute.RemoveItemName
  fullName: System.Configuration.ConfigurationCollectionAttribute.RemoveItemName
- uid: System.Configuration.ConfigurationCollectionAttribute.#ctor*
  parent: System.Configuration.ConfigurationCollectionAttribute
  isExternal: false
  name: ConfigurationCollectionAttribute
  nameWithType: ConfigurationCollectionAttribute.ConfigurationCollectionAttribute
- uid: System.Configuration.ConfigurationCollectionAttribute.AddItemName*
  parent: System.Configuration.ConfigurationCollectionAttribute
  isExternal: false
  name: AddItemName
  nameWithType: ConfigurationCollectionAttribute.AddItemName
- uid: System.Configuration.ConfigurationCollectionAttribute.ClearItemsName*
  parent: System.Configuration.ConfigurationCollectionAttribute
  isExternal: false
  name: ClearItemsName
  nameWithType: ConfigurationCollectionAttribute.ClearItemsName
- uid: System.Configuration.ConfigurationCollectionAttribute.CollectionType*
  parent: System.Configuration.ConfigurationCollectionAttribute
  isExternal: false
  name: CollectionType
  nameWithType: ConfigurationCollectionAttribute.CollectionType
- uid: System.Configuration.ConfigurationCollectionAttribute.ItemType*
  parent: System.Configuration.ConfigurationCollectionAttribute
  isExternal: false
  name: ItemType
  nameWithType: ConfigurationCollectionAttribute.ItemType
- uid: System.Configuration.ConfigurationCollectionAttribute.RemoveItemName*
  parent: System.Configuration.ConfigurationCollectionAttribute
  isExternal: false
  name: RemoveItemName
  nameWithType: ConfigurationCollectionAttribute.RemoveItemName
