### YamlMime:ManagedReference
items:
- uid: System.Windows.Media.Converters.CacheModeValueSerializer
  id: CacheModeValueSerializer
  children:
  - System.Windows.Media.Converters.CacheModeValueSerializer.#ctor
  - System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Converters.CacheModeValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Converters.CacheModeValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: CacheModeValueSerializer
  nameWithType: CacheModeValueSerializer
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer
  type: Class
  summary: "インスタンスに変換します<xref:System.String>のインスタンスと<xref href=&quot;System.Windows.Media.CacheMode&quot;> </xref></xref:System.String> 。"
  remarks: "このクラスは、通常のみ使用して、<xref:System.Windows.Markup.Primitives.MarkupWriter>シリアル化のためです</xref:System.Windows.Markup.Primitives.MarkupWriter>。"
  syntax:
    content: 'public class CacheModeValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.#ctor
  id: '#ctor'
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  langs:
  - csharp
  name: CacheModeValueSerializer()
  nameWithType: CacheModeValueSerializer.CacheModeValueSerializer()
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.CacheModeValueSerializer()
  type: Constructor
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Windows.Media.Converters.CacheModeValueSerializer&quot;> </xref>クラスです。"
  syntax:
    content: public CacheModeValueSerializer ();
    parameters: []
  overload: System.Windows.Media.Converters.CacheModeValueSerializer.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  langs:
  - csharp
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: CacheModeValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "決定するかどうか、指定した<xref:System.String>のインスタンスに変換できる<xref href=&quot;System.Windows.Media.CacheMode&quot;> </xref></xref:System.String> 。"
  remarks: "このメソッドは常に返します`true`です。"
  syntax:
    content: public override bool CanConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "A<xref:System.String>変換の評価対象にします</xref:System.String>。"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "変換に使用されるコンテキスト情報。"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>場合<code> value </code>変換後、それ以外は、 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>です。"
  overload: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: CacheModeValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "指定するかどうかの指定されたインスタンス<xref href=&quot;System.Windows.Media.CacheMode&quot;> </xref> <xref:System.String>.</xref:System.String>を変換することができます"
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "インスタンス<xref href=&quot;System.Windows.Media.CacheMode&quot;></xref>変換の評価対象にします。"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "変換に使用されるコンテキスト情報。"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>場合<code> value </code>に変換できる、 <xref:System.String>、それ以外の<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref></xref:System.String> 。"
  overload: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertToString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  langs:
  - csharp
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: CacheModeValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "変換、<xref:System.String>に、 <xref href=&quot;System.Windows.Media.CacheMode&quot;> </xref></xref:System.String> 。"
  syntax:
    content: public override object ConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "A<xref:System.String>に変換する値、 <xref href=&quot;System.Windows.Media.CacheMode&quot;> </xref></xref:System.String> 。"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "変換に使用されるコンテキスト情報。"
    return:
      type: System.Object
      description: "新しいインスタンスを<xref href=&quot;System.Windows.Media.CacheMode&quot;></xref>に基づいて、指定された<code> value</code>です。"
  overload: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: CacheModeValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "インスタンスに変換します<xref href=&quot;System.Windows.Media.CacheMode&quot;> </xref> <xref:System.String></xref:System.String> 。"
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "インスタンス<xref href=&quot;System.Windows.Media.CacheMode&quot;></xref>変換の評価対象にします。"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "変換に使用されるコンテキスト情報。"
    return:
      type: System.String
      description: "A<xref:System.String>の指定した表現<xref href=&quot;System.Windows.Media.CacheMode&quot;></xref>オブジェクト</xref:System.String>。"
  overload: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.#ctor
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: CacheModeValueSerializer()
  nameWithType: CacheModeValueSerializer.CacheModeValueSerializer()
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.CacheModeValueSerializer()
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: CacheModeValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertFromString(String,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: CacheModeValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: CacheModeValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertFromString(String,IValueSerializerContext)
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: CacheModeValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.#ctor*
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: CacheModeValueSerializer
  nameWithType: CacheModeValueSerializer.CacheModeValueSerializer
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertFromString*
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: CanConvertFromString
  nameWithType: CacheModeValueSerializer.CanConvertFromString
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.CanConvertToString*
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: CacheModeValueSerializer.CanConvertToString
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertFromString*
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: ConvertFromString
  nameWithType: CacheModeValueSerializer.ConvertFromString
- uid: System.Windows.Media.Converters.CacheModeValueSerializer.ConvertToString*
  parent: System.Windows.Media.Converters.CacheModeValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: CacheModeValueSerializer.ConvertToString
