### YamlMime:ManagedReference
items:
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  id: TimeSpanMinutesOrInfiniteConverter
  children:
  - System.Configuration.TimeSpanMinutesOrInfiniteConverter.#ctor
  - System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: TimeSpanMinutesOrInfiniteConverter
  nameWithType: TimeSpanMinutesOrInfiniteConverter
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  type: Class
  summary: "<xref:System.TimeSpan>分数で表されるまたは無限の標準として span. を時刻</xref:System.TimeSpan>に変換します"
  remarks: "など、他の構成を実行するコンバーターの種類すべて、この型では、関連する厳密に型指定されたプロパティとの間の構成ファイル内で見つかった文字列に変換します。       具体的には、TimeSpanMinutesOrInfiniteConverter クラスに変換します<xref:System.String>(分単位) に、[構成] プロパティに割り当てられている<xref:System.TimeSpan>分またはその逆</xref:System.TimeSpan></xref:System.String>。 構成プロパティがある場合、 <xref:System.String>「無制限」の値は、この値を変換<xref:System.TimeSpan>およびその逆</xref:System.TimeSpan></xref:System.String>。       無限<xref:System.TimeSpan>によって表される値、<xref:System.TimeSpan.MaxValue>列挙値</xref:System.TimeSpan.MaxValue></xref:System.TimeSpan>。"
  example:
  - Refer to the code examples in the <xref:System.Configuration.InfiniteTimeSpanConverter> and <xref:System.Configuration.TimeSpanMinutesConverter> classes.
  syntax:
    content: 'public sealed class TimeSpanMinutesOrInfiniteConverter : System.Configuration.TimeSpanMinutesConverter'
  inheritance:
  - System.Object
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  - System.Configuration.TimeSpanMinutesConverter
  implements: []
  inheritedMembers:
  - System.ComponentModel.TypeConverter.CanConvertFrom(System.Type)
  - System.ComponentModel.TypeConverter.CanConvertTo(System.Type)
  - System.ComponentModel.TypeConverter.ConvertFrom(System.Object)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.String)
  - System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.Object)
  - System.ComponentModel.TypeConverter.CreateInstance(System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.CreateInstance(System.ComponentModel.ITypeDescriptorContext,System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.GetConvertFromException(System.Object)
  - System.ComponentModel.TypeConverter.GetConvertToException(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object,System.Attribute[])
  - System.ComponentModel.TypeConverter.GetProperties(System.Object)
  - System.ComponentModel.TypeConverter.GetPropertiesSupported
  - System.ComponentModel.TypeConverter.GetPropertiesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValues
  - System.ComponentModel.TypeConverter.GetStandardValues(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.IsValid(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.IsValid(System.Object)
  - System.ComponentModel.TypeConverter.SortProperties(System.ComponentModel.PropertyDescriptorCollection,System.String[])
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  platform:
  - net462
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.#ctor
  id: '#ctor'
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  langs:
  - csharp
  name: TimeSpanMinutesOrInfiniteConverter()
  nameWithType: TimeSpanMinutesOrInfiniteConverter.TimeSpanMinutesOrInfiniteConverter()
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.TimeSpanMinutesOrInfiniteConverter()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Configuration.TimeSpanMinutesOrInfiniteConverter&quot;> </xref>クラスです。"
  remarks: "通常、システムによって提供されるコンバーターの種類を使用します。 TimeSpanMinutesOrInfiniteConverter コンス トラクターを使用する必要があるは、独自の変換の種類を作成するときだけです。"
  syntax:
    content: public TimeSpanMinutesOrInfiniteConverter ();
    parameters: []
  overload: System.Configuration.TimeSpanMinutesOrInfiniteConverter.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TimeSpanMinutesOrInfiniteConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "<xref:System.String> <xref:System.TimeSpan>。</xref:System.TimeSpan></xref:System.String>に変換します"
  remarks: "システム メソッドを使用して ConvertFrom 構成ファイルから読み取るときに変換する、<xref:System.String>値<xref:System.TimeSpan>、または、 <xref:System.String>「無制限」 <xref:System.TimeSpan.MaxValue></xref:System.TimeSpan.MaxValue> </xref:System.String> </xref:System.TimeSpan> </xref:System.String> 。"
  example:
  - Refer to the code examples in the <xref:System.Configuration.InfiniteTimeSpanConverter> and <xref:System.Configuration.TimeSpanMinutesConverter> classes.
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "<xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref>オブジェクトの型変換のために使用します。"
    - id: ci
      type: System.Globalization.CultureInfo
      description: "<xref:System.Globalization.CultureInfo>変換中に使用されるオブジェクト</xref:System.Globalization.CultureInfo>。"
    - id: data
      type: System.Object
      description: "<xref:System.String>変換対象のオブジェクト</xref:System.String>。"
    return:
      type: System.Object
      description: "<xref:System.TimeSpan.MaxValue>場合は、 <code> data </code>パラメーターは、 <xref:System.String>「無制限」、それ以外の<xref:System.TimeSpan>を表す、 <code> data </code>分単位でのパラメーターです</xref:System.TimeSpan></xref:System.String></xref:System.TimeSpan.MaxValue>。"
  overload: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TimeSpanMinutesOrInfiniteConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "<xref:System.TimeSpan> <xref:System.String>。</xref:System.String></xref:System.TimeSpan>に変換します"
  remarks: "システム、ConvertTo メソッドを使用して構成ファイルに書き込む際に変換する<xref:System.TimeSpan>値または<xref:System.TimeSpan.MaxValue><xref:System.String>。</xref:System.String> </xref:System.TimeSpan.MaxValue> </xref:System.TimeSpan>"
  example:
  - Refer to the code examples in the <xref:System.Configuration.InfiniteTimeSpanConverter> and <xref:System.Configuration.TimeSpanMinutesConverter> classes.
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "<xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref>オブジェクトの型変換のために使用します。"
    - id: ci
      type: System.Globalization.CultureInfo
      description: "<xref:System.Globalization.CultureInfo>変換中に使用されるオブジェクト</xref:System.Globalization.CultureInfo>。"
    - id: value
      type: System.Object
      description: "変換する値。"
    - id: type
      type: System.Type
      description: "変換の型。"
    return:
      type: System.Object
      description: "<xref:System.String>「無制限」の場合、 <code> value </code>パラメーターが<xref:System.TimeSpan.MaxValue>ですそれ以外の場合、<xref:System.String>を表す、 <code> value </code>分単位でのパラメーターです。</xref:System.String> </xref:System.TimeSpan.MaxValue> </xref:System.String> 。"
  overload: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.TimeSpanMinutesConverter
  isExternal: false
  name: System.Configuration.TimeSpanMinutesConverter
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.#ctor
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  isExternal: false
  name: TimeSpanMinutesOrInfiniteConverter()
  nameWithType: TimeSpanMinutesOrInfiniteConverter.TimeSpanMinutesOrInfiniteConverter()
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.TimeSpanMinutesOrInfiniteConverter()
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TimeSpanMinutesOrInfiniteConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: false
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TimeSpanMinutesOrInfiniteConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.#ctor*
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  isExternal: false
  name: TimeSpanMinutesOrInfiniteConverter
  nameWithType: TimeSpanMinutesOrInfiniteConverter.TimeSpanMinutesOrInfiniteConverter
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertFrom*
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: TimeSpanMinutesOrInfiniteConverter.ConvertFrom
- uid: System.Configuration.TimeSpanMinutesOrInfiniteConverter.ConvertTo*
  parent: System.Configuration.TimeSpanMinutesOrInfiniteConverter
  isExternal: false
  name: ConvertTo
  nameWithType: TimeSpanMinutesOrInfiniteConverter.ConvertTo
