### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.FormsProtectionEnum
  id: FormsProtectionEnum
  children:
  - System.Web.Configuration.FormsProtectionEnum.All
  - System.Web.Configuration.FormsProtectionEnum.Encryption
  - System.Web.Configuration.FormsProtectionEnum.None
  - System.Web.Configuration.FormsProtectionEnum.Validation
  langs:
  - csharp
  name: FormsProtectionEnum
  nameWithType: FormsProtectionEnum
  fullName: System.Web.Configuration.FormsProtectionEnum
  type: Enum
  summary: "いずれかの cookie を使用する場合は、暗号化の種類を定義します。"
  remarks: "システムがに基づいて、構成済みのデータ検証アルゴリズムを使用してすべての値を選択する場合、 [machineKey 要素 (ASP.NET 設定スキーマ)](http://msdn.microsoft.com/en-us/4b5699a9-bc21-4c4a-85f1-8b3b8ebd2d46)タグ。 これは、既定値であり、推奨値。       [なし] を選択した場合、プレーン テキスト攻撃の対象と cookie を引き起こすことがあります。       検証を選択すると、cookie のデータの検証キーの連結、メッセージ認証コード (MAC)、コンピューティングおよび送出 cookie への MAC の付加により、cookie 検証を使用して cookie が作成されます。"
  example:
  - "The following code example shows how to use the FormsProtectionEnum enumeration. Refer to the code example in the <xref:System.Web.Configuration.FormsAuthenticationConfiguration> class topic to learn how to get the section.  \n  \n [!code-vb[System.Web.Configuration.FormsAuthenticationConfiguration#11](~/add/codesnippet/visualbasic/t-system.web.configurati_72_1.vb)]\n [!code-cs[System.Web.Configuration.FormsAuthenticationConfiguration#11](~/add/codesnippet/csharp/t-system.web.configurati_72_1.cs)]"
  syntax:
    content: public enum FormsProtectionEnum
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.FormsProtectionEnum.All
  id: All
  parent: System.Web.Configuration.FormsProtectionEnum
  langs:
  - csharp
  name: All
  nameWithType: FormsProtectionEnum.All
  fullName: System.Web.Configuration.FormsProtectionEnum.All
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "アプリケーションが cookie を保護するために、データの検証と暗号化の両方を使用することを指定します。 このオプションが設定されているデータ検証アルゴリズムを使用して (に基づいて、 <xref uid=&quot;langword_csharp_machineKey&quot; name=&quot;machineKey&quot; href=&quot;&quot;> </xref>要素)。 TRIPLE-DES (3 des) 暗号化に使用、および使用可能になる場合、キーが 48 バイト以上である場合。 <xref uid=&quot;langword_csharp_All&quot; name=&quot;All&quot; href=&quot;&quot;></xref>既定値 (および推奨) 値です。"
  syntax:
    content: All
    return:
      type: System.Web.Configuration.FormsProtectionEnum
      description: "追加します。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsProtectionEnum.Encryption
  id: Encryption
  parent: System.Web.Configuration.FormsProtectionEnum
  langs:
  - csharp
  name: Encryption
  nameWithType: FormsProtectionEnum.Encryption
  fullName: System.Web.Configuration.FormsProtectionEnum.Encryption
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "TRIPLE-DES または DES を使用して cookie が暗号化されますが、cookie のデータ検証は実行されませんを指定します。 このように使用する cookie は、平文セキュリティ攻撃にさらされる可能性があります。"
  syntax:
    content: Encryption
    return:
      type: System.Web.Configuration.FormsProtectionEnum
      description: "追加します。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsProtectionEnum.None
  id: None
  parent: System.Web.Configuration.FormsProtectionEnum
  langs:
  - csharp
  name: None
  nameWithType: FormsProtectionEnum.None
  fullName: System.Web.Configuration.FormsProtectionEnum.None
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "パーソナル化に対してのみ cookie を使用する、セキュリティ要件が高くしたがってがサイトの暗号化と検証の両方が無効になっているを指定します。 この方法で cookie を使用することはしないでください。ただし、.NET Framework を使用して個人用設定を有効にするリソースを最小限に抑える方法を勧めします。"
  syntax:
    content: None
    return:
      type: System.Web.Configuration.FormsProtectionEnum
      description: "追加します。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsProtectionEnum.Validation
  id: Validation
  parent: System.Web.Configuration.FormsProtectionEnum
  langs:
  - csharp
  name: Validation
  nameWithType: FormsProtectionEnum.Validation
  fullName: System.Web.Configuration.FormsProtectionEnum.Validation
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "アプリケーションで検証スキームを使用して、転送中に暗号化された cookie の内容が変更されていないことを確認することを指定します。 Cookie のデータの検証キーの連結、メッセージ認証コード (MAC)、コンピューティングおよび送出 cookie への MAC の付加により、cookie が作成されます。"
  syntax:
    content: Validation
    return:
      type: System.Web.Configuration.FormsProtectionEnum
      description: "追加します。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.FormsProtectionEnum.All
  parent: System.Web.Configuration.FormsProtectionEnum
  isExternal: false
  name: All
  nameWithType: FormsProtectionEnum.All
  fullName: System.Web.Configuration.FormsProtectionEnum.All
- uid: System.Web.Configuration.FormsProtectionEnum
  parent: System.Web.Configuration
  isExternal: false
  name: FormsProtectionEnum
  nameWithType: FormsProtectionEnum
  fullName: System.Web.Configuration.FormsProtectionEnum
- uid: System.Web.Configuration.FormsProtectionEnum.Encryption
  parent: System.Web.Configuration.FormsProtectionEnum
  isExternal: false
  name: Encryption
  nameWithType: FormsProtectionEnum.Encryption
  fullName: System.Web.Configuration.FormsProtectionEnum.Encryption
- uid: System.Web.Configuration.FormsProtectionEnum.None
  parent: System.Web.Configuration.FormsProtectionEnum
  isExternal: false
  name: None
  nameWithType: FormsProtectionEnum.None
  fullName: System.Web.Configuration.FormsProtectionEnum.None
- uid: System.Web.Configuration.FormsProtectionEnum.Validation
  parent: System.Web.Configuration.FormsProtectionEnum
  isExternal: false
  name: Validation
  nameWithType: FormsProtectionEnum.Validation
  fullName: System.Web.Configuration.FormsProtectionEnum.Validation
