### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement
  id: SoapExtensionTypeElement
  children:
  - System.Web.Services.Configuration.SoapExtensionTypeElement.#ctor
  - System.Web.Services.Configuration.SoapExtensionTypeElement.#ctor(System.String,System.Int32,System.Web.Services.Configuration.PriorityGroup)
  - System.Web.Services.Configuration.SoapExtensionTypeElement.#ctor(System.Type,System.Int32,System.Web.Services.Configuration.PriorityGroup)
  - System.Web.Services.Configuration.SoapExtensionTypeElement.Group
  - System.Web.Services.Configuration.SoapExtensionTypeElement.Priority
  - System.Web.Services.Configuration.SoapExtensionTypeElement.Properties
  - System.Web.Services.Configuration.SoapExtensionTypeElement.Type
  langs:
  - csharp
  name: SoapExtensionTypeElement
  nameWithType: SoapExtensionTypeElement
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement
  type: Class
  summary: "Web サービスの構成ファイルで SoapExtensionElement を表します。 この要素は、構成ファイルのスコープ内のすべての XML Web サービスで実行する SOAP 拡張機能を追加します。 クラスは継承できません。"
  syntax:
    content: 'public sealed class SoapExtensionTypeElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.#ctor
  id: '#ctor'
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  langs:
  - csharp
  name: SoapExtensionTypeElement()
  nameWithType: SoapExtensionTypeElement.SoapExtensionTypeElement()
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.SoapExtensionTypeElement()
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Web.Services.Configuration.SoapExtensionTypeElement&quot;> </xref>クラスです。"
  syntax:
    content: public SoapExtensionTypeElement ();
    parameters: []
  overload: System.Web.Services.Configuration.SoapExtensionTypeElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.#ctor(System.String,System.Int32,System.Web.Services.Configuration.PriorityGroup)
  id: '#ctor(System.String,System.Int32,System.Web.Services.Configuration.PriorityGroup)'
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  langs:
  - csharp
  name: SoapExtensionTypeElement(String,Int32,PriorityGroup)
  nameWithType: SoapExtensionTypeElement.SoapExtensionTypeElement(String,Int32,PriorityGroup)
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.SoapExtensionTypeElement(String,Int32,PriorityGroup)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Web.Services.Configuration.SoapExtensionTypeElement&quot;> </xref>クラスです。"
  syntax:
    content: public SoapExtensionTypeElement (string type, int priority, System.Web.Services.Configuration.PriorityGroup group);
    parameters:
    - id: type
      type: System.String
      description: "追加される SOAP 拡張機能クラスを指定します。"
    - id: priority
      type: System.Int32
      description: "SOAP 拡張機能が実行される複数の SOAP 拡張機能が指定されている相対順序を示します。 各グループ内では、優先度属性は、SOAP 拡張機能の全体的な相対的な優先順位を区別します。 低い優先順位番号では、SOAP 拡張機能の優先順位が高いことを示します。 Priority 属性の最小値は 1 です。"
    - id: group
      type: System.Web.Services.Configuration.PriorityGroup
      description: "優先度、と共に実行する複数の SOAP 拡張機能が構成されている場合に実行される SOAP 拡張機能の相対順序を指定します。"
  overload: System.Web.Services.Configuration.SoapExtensionTypeElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.#ctor(System.Type,System.Int32,System.Web.Services.Configuration.PriorityGroup)
  id: '#ctor(System.Type,System.Int32,System.Web.Services.Configuration.PriorityGroup)'
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  langs:
  - csharp
  name: SoapExtensionTypeElement(Type,Int32,PriorityGroup)
  nameWithType: SoapExtensionTypeElement.SoapExtensionTypeElement(Type,Int32,PriorityGroup)
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.SoapExtensionTypeElement(Type,Int32,PriorityGroup)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Web.Services.Configuration.SoapExtensionTypeElement&quot;> </xref>クラスです。"
  syntax:
    content: public SoapExtensionTypeElement (Type type, int priority, System.Web.Services.Configuration.PriorityGroup group);
    parameters:
    - id: type
      type: System.Type
      description: "追加される SOAP 拡張機能クラスを指定します。"
    - id: priority
      type: System.Int32
      description: "SOAP 拡張機能が実行される複数の SOAP 拡張機能が指定されている相対順序を示します。"
    - id: group
      type: System.Web.Services.Configuration.PriorityGroup
      description: "優先度、と共に実行する複数の SOAP 拡張機能が構成されている場合に実行される SOAP 拡張機能の相対順序を指定します。"
  overload: System.Web.Services.Configuration.SoapExtensionTypeElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.Group
  id: Group
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  langs:
  - csharp
  name: Group
  nameWithType: SoapExtensionTypeElement.Group
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.Group
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "取得またはを実行する複数の SOAP 拡張機能が構成されている場合に実行される SOAP 拡張機能の相対順序を設定します。"
  remarks: "各グループ内では、優先度属性は、SOAP 拡張機能の全体的な相対的な優先順位を区別します。 低い優先順位番号では、SOAP 拡張機能の優先順位が高いことを示します。 Priority 属性の最小値は 1 です。"
  syntax:
    content: public System.Web.Services.Configuration.PriorityGroup Group { get; set; }
    return:
      type: System.Web.Services.Configuration.PriorityGroup
      description: "A <xref href=&quot;System.Web.Services.Configuration.PriorityGroup&quot;> </xref> SOAP 拡張機能が実行される相対順序を決定する値を持つオブジェクト。"
  overload: System.Web.Services.Configuration.SoapExtensionTypeElement.Group*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.Priority
  id: Priority
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  langs:
  - csharp
  name: Priority
  nameWithType: SoapExtensionTypeElement.Priority
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.Priority
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "取得または複数の SOAP 拡張機能が指定されている場合に実行される SOAP 拡張機能の相対順序を示す値を設定します。"
  remarks: "各グループ内では、優先度属性は、SOAP 拡張機能の全体的な相対的な優先順位を区別します。 低い優先順位番号では、SOAP 拡張機能の優先順位が高いことを示します。 Priority 属性の最小値は 1 です。"
  syntax:
    content: public int Priority { get; set; }
    return:
      type: System.Int32
      description: "A <xref:System.Int32>SOAP 拡張機能が実行される相対順序を決定する値を持つ</xref:System.Int32>。"
  overload: System.Web.Services.Configuration.SoapExtensionTypeElement.Priority*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.Properties
  id: Properties
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  langs:
  - csharp
  name: Properties
  nameWithType: SoapExtensionTypeElement.Properties
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.Properties
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "追加します。"
  overload: System.Web.Services.Configuration.SoapExtensionTypeElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.Type
  id: Type
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  langs:
  - csharp
  name: Type
  nameWithType: SoapExtensionTypeElement.Type
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.Type
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "取得または Web サービスの構成ファイルの SoapExtensionType 要素に追加する SOAP 拡張機能クラスを設定します。"
  syntax:
    content: public Type Type { get; set; }
    return:
      type: System.Type
      description: "A <xref:System.String>SoapExtensionType 要素の型名を格納している</xref:System.String>。"
  overload: System.Web.Services.Configuration.SoapExtensionTypeElement.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.#ctor
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  isExternal: false
  name: SoapExtensionTypeElement()
  nameWithType: SoapExtensionTypeElement.SoapExtensionTypeElement()
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.SoapExtensionTypeElement()
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.#ctor(System.String,System.Int32,System.Web.Services.Configuration.PriorityGroup)
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  isExternal: false
  name: SoapExtensionTypeElement(String,Int32,PriorityGroup)
  nameWithType: SoapExtensionTypeElement.SoapExtensionTypeElement(String,Int32,PriorityGroup)
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.SoapExtensionTypeElement(String,Int32,PriorityGroup)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Services.Configuration.PriorityGroup
  parent: System.Web.Services.Configuration
  isExternal: false
  name: PriorityGroup
  nameWithType: PriorityGroup
  fullName: System.Web.Services.Configuration.PriorityGroup
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.#ctor(System.Type,System.Int32,System.Web.Services.Configuration.PriorityGroup)
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  isExternal: false
  name: SoapExtensionTypeElement(Type,Int32,PriorityGroup)
  nameWithType: SoapExtensionTypeElement.SoapExtensionTypeElement(Type,Int32,PriorityGroup)
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.SoapExtensionTypeElement(Type,Int32,PriorityGroup)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.Group
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  isExternal: false
  name: Group
  nameWithType: SoapExtensionTypeElement.Group
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.Group
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.Priority
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  isExternal: false
  name: Priority
  nameWithType: SoapExtensionTypeElement.Priority
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.Priority
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.Properties
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  isExternal: false
  name: Properties
  nameWithType: SoapExtensionTypeElement.Properties
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.Type
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  isExternal: false
  name: Type
  nameWithType: SoapExtensionTypeElement.Type
  fullName: System.Web.Services.Configuration.SoapExtensionTypeElement.Type
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.#ctor*
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  isExternal: false
  name: SoapExtensionTypeElement
  nameWithType: SoapExtensionTypeElement.SoapExtensionTypeElement
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.Group*
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  isExternal: false
  name: Group
  nameWithType: SoapExtensionTypeElement.Group
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.Priority*
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  isExternal: false
  name: Priority
  nameWithType: SoapExtensionTypeElement.Priority
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.Properties*
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  isExternal: false
  name: Properties
  nameWithType: SoapExtensionTypeElement.Properties
- uid: System.Web.Services.Configuration.SoapExtensionTypeElement.Type*
  parent: System.Web.Services.Configuration.SoapExtensionTypeElement
  isExternal: false
  name: Type
  nameWithType: SoapExtensionTypeElement.Type
