### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ConvertersCollection
  id: ConvertersCollection
  children:
  - System.Web.Configuration.ConvertersCollection.#ctor
  - System.Web.Configuration.ConvertersCollection.Add(System.Web.Configuration.Converter)
  - System.Web.Configuration.ConvertersCollection.Clear
  - System.Web.Configuration.ConvertersCollection.CreateNewElement
  - System.Web.Configuration.ConvertersCollection.GetElementKey(System.Configuration.ConfigurationElement)
  - System.Web.Configuration.ConvertersCollection.Item(System.Int32)
  - System.Web.Configuration.ConvertersCollection.Properties
  - System.Web.Configuration.ConvertersCollection.Remove(System.Web.Configuration.Converter)
  langs:
  - csharp
  name: ConvertersCollection
  nameWithType: ConvertersCollection
  fullName: System.Web.Configuration.ConvertersCollection
  type: Class
  summary: "参照を含む構成コレクションを表します<xref href=&quot;System.Web.Configuration.Converter&quot;></xref>オブジェクト。"
  remarks: "コレクションを使用する、ConvertersCollection を使用することができます<xref:System.Web.Configuration.Converter>オブジェクト</xref:System.Web.Configuration.Converter>。 カスタムのコレクションを追加するには、このクラスを実装する<xref:System.Web.Configuration.Converter>要素を<xref:System.Configuration.ConfigurationSection>オブジェクト</xref:System.Configuration.ConfigurationSection></xref:System.Web.Configuration.Converter>。"
  syntax:
    content: >-
      [System.Configuration.ConfigurationCollection(typeof(System.Web.Configuration.Converter))]

      public class ConvertersCollection : System.Configuration.ConfigurationElementCollection
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationElementCollection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.AddElementName
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Configuration.ConfigurationElement,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Int32,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseClear
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseGetAllKeys
  - System.Configuration.ConfigurationElementCollection.BaseGetKey(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseIndexOf(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseIsRemoved(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemove(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemoveAt(System.Int32)
  - System.Configuration.ConfigurationElementCollection.ClearElementName
  - System.Configuration.ConfigurationElementCollection.CollectionType
  - System.Configuration.ConfigurationElementCollection.CopyTo(System.Configuration.ConfigurationElement[],System.Int32)
  - System.Configuration.ConfigurationElementCollection.Count
  - System.Configuration.ConfigurationElementCollection.CreateNewElement(System.String)
  - System.Configuration.ConfigurationElementCollection.ElementName
  - System.Configuration.ConfigurationElementCollection.EmitClear
  - System.Configuration.ConfigurationElementCollection.Equals(System.Object)
  - System.Configuration.ConfigurationElementCollection.GetEnumerator
  - System.Configuration.ConfigurationElementCollection.GetHashCode
  - System.Configuration.ConfigurationElementCollection.IsElementName(System.String)
  - System.Configuration.ConfigurationElementCollection.IsElementRemovable(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.IsModified
  - System.Configuration.ConfigurationElementCollection.IsReadOnly
  - System.Configuration.ConfigurationElementCollection.IsSynchronized
  - System.Configuration.ConfigurationElementCollection.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElementCollection.RemoveElementName
  - System.Configuration.ConfigurationElementCollection.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.ResetModified
  - System.Configuration.ConfigurationElementCollection.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.SetReadOnly
  - System.Configuration.ConfigurationElementCollection.SyncRoot
  - System.Configuration.ConfigurationElementCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  - System.Configuration.ConfigurationElementCollection.ThrowOnDuplicate
  - System.Configuration.ConfigurationElementCollection.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.ConvertersCollection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.ConvertersCollection
  langs:
  - csharp
  name: ConvertersCollection()
  nameWithType: ConvertersCollection.ConvertersCollection()
  fullName: System.Web.Configuration.ConvertersCollection.ConvertersCollection()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Web.Configuration.ConvertersCollection&quot;> </xref>クラスです。"
  syntax:
    content: public ConvertersCollection ();
    parameters: []
  overload: System.Web.Configuration.ConvertersCollection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ConvertersCollection.Add(System.Web.Configuration.Converter)
  id: Add(System.Web.Configuration.Converter)
  parent: System.Web.Configuration.ConvertersCollection
  langs:
  - csharp
  name: Add(Converter)
  nameWithType: ConvertersCollection.Add(Converter)
  fullName: System.Web.Configuration.ConvertersCollection.Add(Converter)
  type: Method
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "追加、 <xref href=&quot;System.Web.Configuration.Converter&quot;> </xref>オブジェクトを<xref href=&quot;System.Web.Configuration.ConvertersCollection&quot;></xref>インスタンス。"
  remarks: "このメソッドは、追加、<xref:System.Web.Configuration.Converter>オブジェクトをコレクションです</xref:System.Web.Configuration.Converter>。 場合、<xref:System.Web.Configuration.Converter>オブジェクトは既にコレクションに、このメソッドは無視されます</xref:System.Web.Configuration.Converter>。"
  syntax:
    content: public void Add (System.Web.Configuration.Converter converter);
    parameters:
    - id: converter
      type: System.Web.Configuration.Converter
      description: "指定する文字列値、 <xref href=&quot;System.Web.Configuration.Converter&quot;> </xref>参照します。"
  overload: System.Web.Configuration.ConvertersCollection.Add*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ConvertersCollection.Clear
  id: Clear
  parent: System.Web.Configuration.ConvertersCollection
  langs:
  - csharp
  name: Clear()
  nameWithType: ConvertersCollection.Clear()
  fullName: System.Web.Configuration.ConvertersCollection.Clear()
  type: Method
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "すべて削除<xref href=&quot;System.Web.Configuration.Converter&quot;></xref>オブジェクトから、 <xref href=&quot;System.Web.Configuration.ConvertersCollection&quot;> </xref>オブジェクト。"
  remarks: "このメソッドは挿入、`clear`ディレクティブを適切なファイルのセクションに、構成、上位の構成ファイルで定義されている要素へのすべての参照を削除します。"
  syntax:
    content: public void Clear ();
    parameters: []
  overload: System.Web.Configuration.ConvertersCollection.Clear*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ConvertersCollection.CreateNewElement
  id: CreateNewElement
  parent: System.Web.Configuration.ConvertersCollection
  langs:
  - csharp
  name: CreateNewElement()
  nameWithType: ConvertersCollection.CreateNewElement()
  fullName: System.Web.Configuration.ConvertersCollection.CreateNewElement()
  type: Method
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "新たに作成<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>オブジェクト。"
  syntax:
    content: protected override System.Configuration.ConfigurationElement CreateNewElement ();
    parameters: []
    return:
      type: System.Configuration.ConfigurationElement
      description: "新しい<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>オブジェクト。"
  overload: System.Web.Configuration.ConvertersCollection.CreateNewElement*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ConvertersCollection.GetElementKey(System.Configuration.ConfigurationElement)
  id: GetElementKey(System.Configuration.ConfigurationElement)
  parent: System.Web.Configuration.ConvertersCollection
  langs:
  - csharp
  name: GetElementKey(ConfigurationElement)
  nameWithType: ConvertersCollection.GetElementKey(ConfigurationElement)
  fullName: System.Web.Configuration.ConvertersCollection.GetElementKey(ConfigurationElement)
  type: Method
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "指定された要素のキーを取得<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>オブジェクト。"
  syntax:
    content: protected override object GetElementKey (System.Configuration.ConfigurationElement element);
    parameters:
    - id: element
      type: System.Configuration.ConfigurationElement
      description: "<xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref>オブジェクトを取得するキーを持つ。"
    return:
      type: System.Object
      description: "オブジェクトは、指定されたキーとして機能<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>インスタンス。"
  overload: System.Web.Configuration.ConvertersCollection.GetElementKey*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ConvertersCollection.Item(System.Int32)
  id: Item(System.Int32)
  parent: System.Web.Configuration.ConvertersCollection
  langs:
  - csharp
  name: Item(Int32)
  nameWithType: ConvertersCollection.Item(Int32)
  fullName: System.Web.Configuration.ConvertersCollection.Item(Int32)
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "取得または設定項目、 <xref href=&quot;System.Web.Configuration.ConvertersCollection&quot;> </xref>コレクション。"
  syntax:
    content: public System.Web.Configuration.Converter this[int index] { get; set; }
    parameters:
    - id: index
      type: System.Int32
      description: "A <xref href=&quot;System.Web.Configuration.Converter&quot;> </xref>コレクションのインデックス。"
    return:
      type: System.Web.Configuration.Converter
      description: "<xref href=&quot;System.Web.Configuration.Converter&quot;> </xref>指定したインデックスにあるオブジェクト。"
  overload: System.Web.Configuration.ConvertersCollection.Item*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ConvertersCollection.Properties
  id: Properties
  parent: System.Web.Configuration.ConvertersCollection
  langs:
  - csharp
  name: Properties
  nameWithType: ConvertersCollection.Properties
  fullName: System.Web.Configuration.ConvertersCollection.Properties
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "構成要素のプロパティのコレクションを取得します。"
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref>構成要素のプロパティを含むオブジェクトです。"
  overload: System.Web.Configuration.ConvertersCollection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ConvertersCollection.Remove(System.Web.Configuration.Converter)
  id: Remove(System.Web.Configuration.Converter)
  parent: System.Web.Configuration.ConvertersCollection
  langs:
  - csharp
  name: Remove(Converter)
  nameWithType: ConvertersCollection.Remove(Converter)
  fullName: System.Web.Configuration.ConvertersCollection.Remove(Converter)
  type: Method
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "指定されたコンバーターからの削除、 <xref href=&quot;System.Web.Configuration.ConvertersCollection&quot;> </xref>オブジェクト。"
  syntax:
    content: public void Remove (System.Web.Configuration.Converter converter);
    parameters:
    - id: converter
      type: System.Web.Configuration.Converter
      description: "削除するコンバーターの名前。"
  overload: System.Web.Configuration.ConvertersCollection.Remove*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElementCollection
  isExternal: false
  name: System.Configuration.ConfigurationElementCollection
- uid: System.Web.Configuration.ConvertersCollection.#ctor
  parent: System.Web.Configuration.ConvertersCollection
  isExternal: false
  name: ConvertersCollection()
  nameWithType: ConvertersCollection.ConvertersCollection()
  fullName: System.Web.Configuration.ConvertersCollection.ConvertersCollection()
- uid: System.Web.Configuration.ConvertersCollection.Add(System.Web.Configuration.Converter)
  parent: System.Web.Configuration.ConvertersCollection
  isExternal: false
  name: Add(Converter)
  nameWithType: ConvertersCollection.Add(Converter)
  fullName: System.Web.Configuration.ConvertersCollection.Add(Converter)
- uid: System.Web.Configuration.Converter
  parent: System.Web.Configuration
  isExternal: false
  name: Converter
  nameWithType: Converter
  fullName: System.Web.Configuration.Converter
- uid: System.Web.Configuration.ConvertersCollection.Clear
  parent: System.Web.Configuration.ConvertersCollection
  isExternal: false
  name: Clear()
  nameWithType: ConvertersCollection.Clear()
  fullName: System.Web.Configuration.ConvertersCollection.Clear()
- uid: System.Web.Configuration.ConvertersCollection.CreateNewElement
  parent: System.Web.Configuration.ConvertersCollection
  isExternal: false
  name: CreateNewElement()
  nameWithType: ConvertersCollection.CreateNewElement()
  fullName: System.Web.Configuration.ConvertersCollection.CreateNewElement()
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.ConvertersCollection.GetElementKey(System.Configuration.ConfigurationElement)
  parent: System.Web.Configuration.ConvertersCollection
  isExternal: false
  name: GetElementKey(ConfigurationElement)
  nameWithType: ConvertersCollection.GetElementKey(ConfigurationElement)
  fullName: System.Web.Configuration.ConvertersCollection.GetElementKey(ConfigurationElement)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.ConvertersCollection.Item(System.Int32)
  parent: System.Web.Configuration.ConvertersCollection
  isExternal: false
  name: Item(Int32)
  nameWithType: ConvertersCollection.Item(Int32)
  fullName: System.Web.Configuration.ConvertersCollection.Item(Int32)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.ConvertersCollection.Properties
  parent: System.Web.Configuration.ConvertersCollection
  isExternal: false
  name: Properties
  nameWithType: ConvertersCollection.Properties
  fullName: System.Web.Configuration.ConvertersCollection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.ConvertersCollection.Remove(System.Web.Configuration.Converter)
  parent: System.Web.Configuration.ConvertersCollection
  isExternal: false
  name: Remove(Converter)
  nameWithType: ConvertersCollection.Remove(Converter)
  fullName: System.Web.Configuration.ConvertersCollection.Remove(Converter)
- uid: System.Web.Configuration.ConvertersCollection.#ctor*
  parent: System.Web.Configuration.ConvertersCollection
  isExternal: false
  name: ConvertersCollection
  nameWithType: ConvertersCollection.ConvertersCollection
- uid: System.Web.Configuration.ConvertersCollection.Add*
  parent: System.Web.Configuration.ConvertersCollection
  isExternal: false
  name: Add
  nameWithType: ConvertersCollection.Add
- uid: System.Web.Configuration.ConvertersCollection.Clear*
  parent: System.Web.Configuration.ConvertersCollection
  isExternal: false
  name: Clear
  nameWithType: ConvertersCollection.Clear
- uid: System.Web.Configuration.ConvertersCollection.CreateNewElement*
  parent: System.Web.Configuration.ConvertersCollection
  isExternal: false
  name: CreateNewElement
  nameWithType: ConvertersCollection.CreateNewElement
- uid: System.Web.Configuration.ConvertersCollection.GetElementKey*
  parent: System.Web.Configuration.ConvertersCollection
  isExternal: false
  name: GetElementKey
  nameWithType: ConvertersCollection.GetElementKey
- uid: System.Web.Configuration.ConvertersCollection.Item*
  parent: System.Web.Configuration.ConvertersCollection
  isExternal: false
  name: Item
  nameWithType: ConvertersCollection.Item
- uid: System.Web.Configuration.ConvertersCollection.Properties*
  parent: System.Web.Configuration.ConvertersCollection
  isExternal: false
  name: Properties
  nameWithType: ConvertersCollection.Properties
- uid: System.Web.Configuration.ConvertersCollection.Remove*
  parent: System.Web.Configuration.ConvertersCollection
  isExternal: false
  name: Remove
  nameWithType: ConvertersCollection.Remove
