### YamlMime:ManagedReference
items:
- uid: System.Workflow.Runtime.WorkflowEnvironment
  id: WorkflowEnvironment
  children:
  - System.Workflow.Runtime.WorkflowEnvironment.WorkBatch
  - System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId
  langs:
  - csharp
  name: WorkflowEnvironment
  nameWithType: WorkflowEnvironment
  fullName: System.Workflow.Runtime.WorkflowEnvironment
  type: Class
  summary: "現在のスレッドで実行されているワークフロー インスタンスのトランザクション環境を表します。"
  remarks: "> [!NOTE] >  [!INCLUDE[DeprecatedContent](~/add/includes/ajax-current-ext-md.md)]WorkflowEnvironment では、現在のスレッドで実行されているワークフロー インスタンスのトランザクション環境を表します。 WorkflowEnvironment が&2; つのプロパティ:<xref:System.Workflow.Runtime.WorkflowEnvironment.WorkBatch%2A>プロパティでは、現在の作業バッチを公開し、追加することで、現在のトランザクションに参加するには、ホストまたはホスト サービスは、<xref:System.Workflow.Runtime.IPendingWork>ですこのプロパティに項目と<xref:System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId%2A>を公開するプロパティ、<xref:System.Guid>このスレッドで現在実行されているワークフロー インスタンスの。</xref:System.Guid> </xref:System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId%2A> </xref:System.Workflow.Runtime.IPendingWork> </xref:System.Workflow.Runtime.WorkflowEnvironment.WorkBatch%2A> 。"
  syntax:
    content: >-
      [System.Obsolete("The System.Workflow.* types are deprecated.  Instead, please use the new types from System.Activities.*")]

      public static class WorkflowEnvironment
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Workflow.Runtime.WorkflowEnvironment.WorkBatch
  id: WorkBatch
  parent: System.Workflow.Runtime.WorkflowEnvironment
  langs:
  - csharp
  name: WorkBatch
  nameWithType: WorkflowEnvironment.WorkBatch
  fullName: System.Workflow.Runtime.WorkflowEnvironment.WorkBatch
  type: Property
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime
  summary: "現在の作業バッチを取得します。"
  remarks: "直接的プロパティは、現在の作業バッチに保留中の作業項目を追加して、現在のトランザクションに参加するには、ホストまたはホスト サービスを使用できます。 ホストまたは現在のトランザクションに参加するホスト サービスを実装する必要があります、<xref:System.Workflow.Runtime.IPendingWork>インターフェイスし、使用<xref:System.Workflow.Runtime.IWorkBatch.Add%2A?displayProperty=fullName>直接的に保留中の作業項目を追加する</xref:System.Workflow.Runtime.IWorkBatch.Add%2A?displayProperty=fullName></xref:System.Workflow.Runtime.IPendingWork>。 永続性サービスは、それらのデータ ストアの状態のワークフロー インスタンスの状態と一貫性を維持する直接的に項目を追加する必要があります。 既定の永続性サービスでは、<xref:System.Workflow.Runtime.Tracking.SqlTrackingService>と<xref:System.Workflow.Runtime.Hosting.SqlWorkflowPersistenceService>、どちらもこの機能を実装します</xref:System.Workflow.Runtime.Hosting.SqlWorkflowPersistenceService></xref:System.Workflow.Runtime.Tracking.SqlTrackingService>。"
  syntax:
    content: public static System.Workflow.Runtime.IWorkBatch WorkBatch { get; }
    return:
      type: System.Workflow.Runtime.IWorkBatch
      description: "<xref href=&quot;System.Workflow.Runtime.IWorkBatch&quot;> </xref>を現在の作業バッチを表すです。"
  overload: System.Workflow.Runtime.WorkflowEnvironment.WorkBatch*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId
  id: WorkflowInstanceId
  parent: System.Workflow.Runtime.WorkflowEnvironment
  langs:
  - csharp
  name: WorkflowInstanceId
  nameWithType: WorkflowEnvironment.WorkflowInstanceId
  fullName: System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId
  type: Property
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime
  summary: "取得、<xref:System.Guid>の現在のスレッドに関連付けられているワークフロー インスタンス</xref:System.Guid>。"
  remarks: "WorkflowInstanceId が含まれています、<xref:System.Guid>このスレッドで現在実行されているワークフロー インスタンスの</xref:System.Guid>。 コードをワークフロー スレッド内から実行されるたびにすることも、 <xref:System.Guid>WorkflowInstanceId プロパティを介してワークフロー インスタンスの</xref:System.Guid>。 たとえば、コードがアクティビティによって呼び出されるサービスの場合は、WorkflowInstanceId は、 <xref:System.Guid>、呼び出し元アクティビティのワークフロー インスタンスの</xref:System.Guid>。"
  syntax:
    content: public static Guid WorkflowInstanceId { get; }
    return:
      type: System.Guid
      description: "<xref:System.Guid>現在のワークフロー インスタンスを識別します</xref:System.Guid>。"
  overload: System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Workflow.Runtime.WorkflowEnvironment.WorkBatch
  parent: System.Workflow.Runtime.WorkflowEnvironment
  isExternal: false
  name: WorkBatch
  nameWithType: WorkflowEnvironment.WorkBatch
  fullName: System.Workflow.Runtime.WorkflowEnvironment.WorkBatch
- uid: System.Workflow.Runtime.IWorkBatch
  parent: System.Workflow.Runtime
  isExternal: false
  name: IWorkBatch
  nameWithType: IWorkBatch
  fullName: System.Workflow.Runtime.IWorkBatch
- uid: System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId
  parent: System.Workflow.Runtime.WorkflowEnvironment
  isExternal: false
  name: WorkflowInstanceId
  nameWithType: WorkflowEnvironment.WorkflowInstanceId
  fullName: System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Workflow.Runtime.WorkflowEnvironment.WorkBatch*
  parent: System.Workflow.Runtime.WorkflowEnvironment
  isExternal: false
  name: WorkBatch
  nameWithType: WorkflowEnvironment.WorkBatch
- uid: System.Workflow.Runtime.WorkflowEnvironment.WorkflowInstanceId*
  parent: System.Workflow.Runtime.WorkflowEnvironment
  isExternal: false
  name: WorkflowInstanceId
  nameWithType: WorkflowEnvironment.WorkflowInstanceId
