### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection
  id: SystemIdentityModelSection
  children:
  - System.IdentityModel.Configuration.SystemIdentityModelSection.#ctor
  - System.IdentityModel.Configuration.SystemIdentityModelSection.Current
  - System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement
  - System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements
  - System.IdentityModel.Configuration.SystemIdentityModelSection.SectionName
  langs:
  - csharp
  name: SystemIdentityModelSection
  nameWithType: SystemIdentityModelSection
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection
  type: Class
  summary: "表す、 <xref uid=&quot;langword_csharp_&lt;system.identityModel&gt;&quot; name=&quot;&lt;system.identityModel&gt;&quot; href=&quot;&quot;> </xref>構成ファイル内のセクションです。 このクラスは継承できません。"
  remarks: "内で、`<system.identityModel>`セクションで、それぞれが一意の名前と特定の構成を定義する複数の id の構成を定義することがあります、たとえば、`<identityConfiguration name=&quot;alternate&quot; >`です。 Id モデルのセクションで定義されている id の構成要素のコレクションを使用して取得できる、<xref:System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements%2A>プロパティ</xref:System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements%2A>。       Id の構成要素の名前が指定されていない場合、要素は、既定の id 構成を定義します。 既定の id 構成はパッシブなフェデレーション シナリオ常に使用されます。 Id モデルの構成セクションでは、1 つだけの既定の構成があります。 使用して取得できる、<xref:System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement%2A>プロパティ</xref:System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement%2A>。"
  syntax:
    content: 'public sealed class SystemIdentityModelSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  langs:
  - csharp
  name: SystemIdentityModelSection()
  nameWithType: SystemIdentityModelSection.SystemIdentityModelSection()
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.SystemIdentityModelSection()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.IdentityModel.Configuration.SystemIdentityModelSection&quot;> </xref>クラスです。"
  syntax:
    content: public SystemIdentityModelSection ();
    parameters: []
  overload: System.IdentityModel.Configuration.SystemIdentityModelSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.Current
  id: Current
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  langs:
  - csharp
  name: Current
  nameWithType: SystemIdentityModelSection.Current
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.Current
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "現在の取得<xref href=&quot;System.IdentityModel.Configuration.SystemIdentityModelSection&quot;></xref>参照します。"
  syntax:
    content: public static System.IdentityModel.Configuration.SystemIdentityModelSection Current { get; }
    return:
      type: System.IdentityModel.Configuration.SystemIdentityModelSection
      description: "現在<xref href=&quot;System.IdentityModel.Configuration.SystemIdentityModelSection&quot;></xref>参照します。"
  overload: System.IdentityModel.Configuration.SystemIdentityModelSection.Current*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement
  id: DefaultIdentityConfigurationElement
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  langs:
  - csharp
  name: DefaultIdentityConfigurationElement
  nameWithType: SystemIdentityModelSection.DefaultIdentityConfigurationElement
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "既定を取得します (無名) <xref href=&quot;System.IdentityModel.Configuration.IdentityConfigurationElement&quot;> </xref>構成ファイルからです。"
  remarks: "`<system.identityModel>`セクションでは、既定値の&1; つだけを含めることができます`<identityConfiguration>`要素。 既定の id 構成はパッシブなフェデレーション シナリオ常に使用されます。"
  syntax:
    content: public static System.IdentityModel.Configuration.IdentityConfigurationElement DefaultIdentityConfigurationElement { get; }
    return:
      type: System.IdentityModel.Configuration.IdentityConfigurationElement
      description: "既定値 (無名) <xref uid=&quot;langword_csharp_&lt;identityConfiguration&gt;&quot; name=&quot;&lt;identityConfiguration&gt;&quot; href=&quot;&quot;> </xref>要素。"
  overload: System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements
  id: IdentityConfigurationElements
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  langs:
  - csharp
  name: IdentityConfigurationElements
  nameWithType: SystemIdentityModelSection.IdentityConfigurationElements
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "取得、 <xref href=&quot;System.IdentityModel.Configuration.IdentityConfigurationElementCollection&quot;> </xref>構成ファイルからです。"
  syntax:
    content: public System.IdentityModel.Configuration.IdentityConfigurationElementCollection IdentityConfigurationElements { get; }
    return:
      type: System.IdentityModel.Configuration.IdentityConfigurationElementCollection
      description: "含むすべてのコレクション、 <xref uid=&quot;langword_csharp_&lt;identityConfiguration&gt;&quot; name=&quot;&lt;identityConfiguration&gt;&quot; href=&quot;&quot;> </xref>内の要素、 <xref uid=&quot;langword_csharp_&lt;system.identityModel&gt;&quot; name=&quot;&lt;system.identityModel&gt;&quot; href=&quot;&quot;> </xref>セクションです。"
  overload: System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.SectionName
  id: SectionName
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  langs:
  - csharp
  name: SectionName
  nameWithType: SystemIdentityModelSection.SectionName
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.SectionName
  type: Field
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Windows Identity Foundation (WIF) では定義されている構成セクションの名前system.identityModel です。"
  syntax:
    content: public const string SectionName;
    return:
      type: System.String
      description: "追加します。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.#ctor
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: SystemIdentityModelSection()
  nameWithType: SystemIdentityModelSection.SystemIdentityModelSection()
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.SystemIdentityModelSection()
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.Current
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: Current
  nameWithType: SystemIdentityModelSection.Current
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.Current
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection
  parent: System.IdentityModel.Configuration
  isExternal: false
  name: SystemIdentityModelSection
  nameWithType: SystemIdentityModelSection
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: DefaultIdentityConfigurationElement
  nameWithType: SystemIdentityModelSection.DefaultIdentityConfigurationElement
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement
- uid: System.IdentityModel.Configuration.IdentityConfigurationElement
  parent: System.IdentityModel.Configuration
  isExternal: false
  name: IdentityConfigurationElement
  nameWithType: IdentityConfigurationElement
  fullName: System.IdentityModel.Configuration.IdentityConfigurationElement
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: IdentityConfigurationElements
  nameWithType: SystemIdentityModelSection.IdentityConfigurationElements
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements
- uid: System.IdentityModel.Configuration.IdentityConfigurationElementCollection
  parent: System.IdentityModel.Configuration
  isExternal: false
  name: IdentityConfigurationElementCollection
  nameWithType: IdentityConfigurationElementCollection
  fullName: System.IdentityModel.Configuration.IdentityConfigurationElementCollection
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.SectionName
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: SectionName
  nameWithType: SystemIdentityModelSection.SectionName
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.SectionName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.#ctor*
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: SystemIdentityModelSection
  nameWithType: SystemIdentityModelSection.SystemIdentityModelSection
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.Current*
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: Current
  nameWithType: SystemIdentityModelSection.Current
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement*
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: DefaultIdentityConfigurationElement
  nameWithType: SystemIdentityModelSection.DefaultIdentityConfigurationElement
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements*
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: IdentityConfigurationElements
  nameWithType: SystemIdentityModelSection.IdentityConfigurationElements
