### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsLoadedEventHandler
  id: SettingsLoadedEventHandler
  langs:
  - csharp
  name: SettingsLoadedEventHandler
  nameWithType: SettingsLoadedEventHandler
  fullName: System.Configuration.SettingsLoadedEventHandler
  type: Delegate
  summary: "処理するメソッドを表す、 <xref href=&quot;System.Configuration.ApplicationSettingsBase.SettingsLoaded&quot;> </xref>イベント。"
  remarks: "<xref:System.Configuration.ApplicationSettingsBase.SettingsLoaded>イベント プロバイダーから設定を取得するときに発生します</xref:System.Configuration.ApplicationSettingsBase.SettingsLoaded>。 このイベントは、プロバイダーごとに&1; 回発生します。"
  syntax:
    content: public delegate void SettingsLoadedEventHandler(object sender, SettingsLoadedEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
