### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.SecurityPolicySection
  id: SecurityPolicySection
  children:
  - System.Web.Configuration.SecurityPolicySection.#ctor
  - System.Web.Configuration.SecurityPolicySection.Properties
  - System.Web.Configuration.SecurityPolicySection.TrustLevels
  langs:
  - csharp
  name: SecurityPolicySection
  nameWithType: SecurityPolicySection
  fullName: System.Web.Configuration.SecurityPolicySection
  type: Class
  summary: "Web アプリケーションのセキュリティ インフラストラクチャをサポートするために使用される構成設定を定義します。 このクラスは継承できません。"
  remarks: "SecurityPolicySection クラスは、プログラムからアクセスしの内容を変更する方法を提供、`securityPolicy`構成ファイルのセクションです。"
  example:
  - "This example demonstrates how to specify values declaratively within the `securityPolicy` section, which can also be accessed as members of the SecurityPolicySection class.  \n  \n The following configuration file example shows how to specify values declaratively for the `securityPolicy` section.  \n  \n```  \n<system.web>  \n  <securityPolicy>  \n    <trustLevel name=\"Full\" policyFile=\"internal\" />  \n    <trustLevel name=\"High\" policyFile=\"web_hightrust.config\" />  \n    <trustLevel name=\"Medium\" policyFile=\"web_mediumtrust.config\" />  \n    <trustLevel name=\"Low\" policyFile=\"web_lowtrust.config\" />  \n    <trustLevel name=\"Minimal\" policyFile=\"web_minimaltrust.config\" />  \n  </securityPolicy>  \n</system.web>  \n```  \n  \n The following code example demonstrates how to use the SecurityPolicySection class.  \n  \n [!code-cs[System.Web.Configuration.SecurityPolicySection#1](~/add/codesnippet/csharp/t-system.web.configurati_26_1.cs)]\n [!code-vb[System.Web.Configuration.SecurityPolicySection#1](~/add/codesnippet/visualbasic/t-system.web.configurati_26_1.vb)]"
  syntax:
    content: 'public sealed class SecurityPolicySection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.SecurityPolicySection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.SecurityPolicySection
  langs:
  - csharp
  name: SecurityPolicySection()
  nameWithType: SecurityPolicySection.SecurityPolicySection()
  fullName: System.Web.Configuration.SecurityPolicySection.SecurityPolicySection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Web.Configuration.SecurityPolicySection&quot;> </xref>既定の設定を使用して、クラスです。"
  remarks: "SecurityPolicySection コンス トラクターは、コードから直接使用するものではありません。 ASP.NET 構成システムによって呼び出されます。 インスタンスを取得する、<xref:System.Web.Configuration.SecurityPolicySection>クラスを使用して、<xref:System.Configuration.Configuration.GetSection%2A>メソッド</xref:System.Configuration.Configuration.GetSection%2A></xref:System.Web.Configuration.SecurityPolicySection>。"
  syntax:
    content: public SecurityPolicySection ();
    parameters: []
  overload: System.Web.Configuration.SecurityPolicySection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SecurityPolicySection.Properties
  id: Properties
  parent: System.Web.Configuration.SecurityPolicySection
  langs:
  - csharp
  name: Properties
  nameWithType: SecurityPolicySection.Properties
  fullName: System.Web.Configuration.SecurityPolicySection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "追加します。"
  overload: System.Web.Configuration.SecurityPolicySection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SecurityPolicySection.TrustLevels
  id: TrustLevels
  parent: System.Web.Configuration.SecurityPolicySection
  langs:
  - csharp
  name: TrustLevels
  nameWithType: SecurityPolicySection.TrustLevels
  fullName: System.Web.Configuration.SecurityPolicySection.TrustLevels
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "TrustLevels コレクションを取得します。"
  remarks: "TrustLevels プロパティの既定値は`Full`、 `High`、 `Medium`、 `Low`、および`Minimal`です。 TrustLevels コレクションの項目は、セキュリティのレベルの名前と関連付けられているポリシー ファイルを指定します。 によって指定されたファイルにマップされている、独自の名前を持つ信頼レベル要素を提供することにより、セキュリティ システムを拡張することができます、`policyFile`属性。 信頼レベルの要素を作成する方法の詳細については、次を参照してください。 [trustLevel 要素 (ASP.NET 設定スキーマ) securityPolicy の](http://msdn.microsoft.com/en-us/729ab04c-03da-4ee5-86b1-be9d08a09369)します。"
  example:
  - "The following code example demonstrates how to use the TrustLevels property, add a trust-level element to the configuration file, and update the configuration file. This code example is part of a larger example provided for the <xref:System.Web.Configuration.SecurityPolicySection> class.  \n  \n [!code-cs[System.Web.Configuration.SecurityPolicySection#2](~/add/codesnippet/csharp/p-system.web.configurati_203_1.cs)]\n [!code-vb[System.Web.Configuration.SecurityPolicySection#2](~/add/codesnippet/visualbasic/p-system.web.configurati_203_1.vb)]"
  syntax:
    content: public System.Web.Configuration.TrustLevelCollection TrustLevels { get; }
    return:
      type: System.Web.Configuration.TrustLevelCollection
      description: "TrustLevels オブジェクトのコレクション。"
  overload: System.Web.Configuration.SecurityPolicySection.TrustLevels*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.SecurityPolicySection.#ctor
  parent: System.Web.Configuration.SecurityPolicySection
  isExternal: false
  name: SecurityPolicySection()
  nameWithType: SecurityPolicySection.SecurityPolicySection()
  fullName: System.Web.Configuration.SecurityPolicySection.SecurityPolicySection()
- uid: System.Web.Configuration.SecurityPolicySection.Properties
  parent: System.Web.Configuration.SecurityPolicySection
  isExternal: false
  name: Properties
  nameWithType: SecurityPolicySection.Properties
  fullName: System.Web.Configuration.SecurityPolicySection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.SecurityPolicySection.TrustLevels
  parent: System.Web.Configuration.SecurityPolicySection
  isExternal: false
  name: TrustLevels
  nameWithType: SecurityPolicySection.TrustLevels
  fullName: System.Web.Configuration.SecurityPolicySection.TrustLevels
- uid: System.Web.Configuration.TrustLevelCollection
  parent: System.Web.Configuration
  isExternal: false
  name: TrustLevelCollection
  nameWithType: TrustLevelCollection
  fullName: System.Web.Configuration.TrustLevelCollection
- uid: System.Web.Configuration.SecurityPolicySection.#ctor*
  parent: System.Web.Configuration.SecurityPolicySection
  isExternal: false
  name: SecurityPolicySection
  nameWithType: SecurityPolicySection.SecurityPolicySection
- uid: System.Web.Configuration.SecurityPolicySection.Properties*
  parent: System.Web.Configuration.SecurityPolicySection
  isExternal: false
  name: Properties
  nameWithType: SecurityPolicySection.Properties
- uid: System.Web.Configuration.SecurityPolicySection.TrustLevels*
  parent: System.Web.Configuration.SecurityPolicySection
  isExternal: false
  name: TrustLevels
  nameWithType: SecurityPolicySection.TrustLevels
