### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel
  id: ProcessModelComImpersonationLevel
  children:
  - System.Web.Configuration.ProcessModelComImpersonationLevel.Anonymous
  - System.Web.Configuration.ProcessModelComImpersonationLevel.Default
  - System.Web.Configuration.ProcessModelComImpersonationLevel.Delegate
  - System.Web.Configuration.ProcessModelComImpersonationLevel.Identify
  - System.Web.Configuration.ProcessModelComImpersonationLevel.Impersonate
  langs:
  - csharp
  name: ProcessModelComImpersonationLevel
  nameWithType: ProcessModelComImpersonationLevel
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel
  type: Enum
  summary: "COM のセキュリティの認証レベルを指定します。"
  remarks: "ProcessModelComImpersonationLevel クラスを設定するときに使用する値を列挙、<xref:System.Web.Configuration.ProcessModelSection.ComImpersonationLevel%2A>プロパティ</xref:System.Web.Configuration.ProcessModelSection.ComImpersonationLevel%2A>。       既定値は、権限を借用します。"
  example:
  - "The following code example shows how to access the <xref:System.Web.Configuration.ProcessModelSection.ComImpersonationLevel%2A> property.  \n  \n [!code-cs[System.Web.Configuration.ProcessModelSection#22](~/add/codesnippet/csharp/t-system.web.configurati_52_1.cs)]\n [!code-vb[System.Web.Configuration.ProcessModelSection#22](~/add/codesnippet/visualbasic/t-system.web.configurati_52_1.vb)]"
  syntax:
    content: public enum ProcessModelComImpersonationLevel
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Anonymous
  id: Anonymous
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  langs:
  - csharp
  name: Anonymous
  nameWithType: ProcessModelComImpersonationLevel.Anonymous
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Anonymous
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "クライアントがサーバーに対して匿名ことを指定します。 このフィールドは定数です。"
  remarks: "サーバーは、クライアントを偽装できますが、権限借用トークンにはすべての情報が含まれていません。"
  syntax:
    content: Anonymous
    return:
      type: System.Web.Configuration.ProcessModelComImpersonationLevel
      description: "追加します。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Default
  id: Default
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  langs:
  - csharp
  name: Default
  nameWithType: ProcessModelComImpersonationLevel.Default
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Default
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "DCOM が偽装レベルを決定することを指定します。 このフィールドは定数です。"
  remarks: "DCOM は、通常のセキュリティ ネゴシエーション アルゴリズムを使用して、偽装レベルを決定します。"
  syntax:
    content: Default
    return:
      type: System.Web.Configuration.ProcessModelComImpersonationLevel
      description: "追加します。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Delegate
  id: Delegate
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  langs:
  - csharp
  name: Delegate
  nameWithType: ProcessModelComImpersonationLevel.Delegate
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Delegate
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "サーバー プロセスが、クライアントの代理として機能している間、クライアントのセキュリティ コンテキストを偽装できることを指定します。 このフィールドは定数です。"
  remarks: "サーバー プロセスには、クローク設定を使用して、クライアントの代理として機能している間には、他のサーバーに送信呼び出しを行うことができます。 サーバーは、クライアントとローカルおよびリモート リソースにアクセスするのに他のコンピューターでクライアントのセキュリティ コンテキストを使用できます。 プロセスがこのレベルでクライアントを偽装する場合、任意の数のコンピューターの境界間で権限借用トークンを渡すことができます。"
  syntax:
    content: Delegate
    return:
      type: System.Web.Configuration.ProcessModelComImpersonationLevel
      description: "追加します。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Identify
  id: Identify
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  langs:
  - csharp
  name: Identify
  nameWithType: ProcessModelComImpersonationLevel.Identify
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Identify
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "サーバーがクライアントの id を取得できることを指定します。 このフィールドは定数です。"
  remarks: "サーバーがアクセス制御リスト (ACL) をチェックする、用のクライアントを偽装できますが、クライアントとしてシステム オブジェクトにアクセスできません。"
  syntax:
    content: Identify
    return:
      type: System.Web.Configuration.ProcessModelComImpersonationLevel
      description: "追加します。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Impersonate
  id: Impersonate
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  langs:
  - csharp
  name: Impersonate
  nameWithType: ProcessModelComImpersonationLevel.Impersonate
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Impersonate
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "サーバー プロセスが、クライアントの代理として機能している間、クライアントのセキュリティ コンテキストを偽装できることを指定します。 このフィールドは定数です。"
  remarks: "このレベルの偽装は、ファイルなどのローカル リソースへのアクセスに使用できます。 プロセスがこのレベルでクライアントを偽装する場合、権限借用トークンは&1; 台のコンピューターの境界を越えて渡すことができます。"
  syntax:
    content: Impersonate
    return:
      type: System.Web.Configuration.ProcessModelComImpersonationLevel
      description: "追加します。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Anonymous
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  isExternal: false
  name: Anonymous
  nameWithType: ProcessModelComImpersonationLevel.Anonymous
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Anonymous
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel
  parent: System.Web.Configuration
  isExternal: false
  name: ProcessModelComImpersonationLevel
  nameWithType: ProcessModelComImpersonationLevel
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Default
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  isExternal: false
  name: Default
  nameWithType: ProcessModelComImpersonationLevel.Default
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Default
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Delegate
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  isExternal: false
  name: Delegate
  nameWithType: ProcessModelComImpersonationLevel.Delegate
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Delegate
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Identify
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  isExternal: false
  name: Identify
  nameWithType: ProcessModelComImpersonationLevel.Identify
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Identify
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Impersonate
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  isExternal: false
  name: Impersonate
  nameWithType: ProcessModelComImpersonationLevel.Impersonate
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Impersonate
