### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ClientTarget
  id: ClientTarget
  children:
  - System.Web.Configuration.ClientTarget.#ctor(System.String,System.String)
  - System.Web.Configuration.ClientTarget.Alias
  - System.Web.Configuration.ClientTarget.Properties
  - System.Web.Configuration.ClientTarget.UserAgent
  langs:
  - csharp
  name: ClientTarget
  nameWithType: ClientTarget
  fullName: System.Web.Configuration.ClientTarget
  type: Class
  summary: "ASP.NET サーバー コントロールがコンテンツを表示するターゲット ユーザー エージェントに関連付けられているエイリアスを定義します。 このクラスは継承できません。"
  remarks: "ClientTarget クラスに追加される要素を指す、`clientTarget`構成ファイルのセクションです。       ClientTarget クラス<xref:System.Web.Configuration.ClientTargetCollection>クラスと<xref:System.Web.Configuration.ClientTargetSection>クラス</xref:System.Web.Configuration.ClientTargetSection></xref:System.Web.Configuration.ClientTargetCollection>が含まれるグループに属しています。       ClientTarget クラスには、ユーザー エージェントとも呼ばれます、クライアントのブラウザーを識別する&2; つのプロパティが含まれています。 1 つのプロパティは、2 番目のプロパティで識別される、クライアント ブラウザーに関連付けられているエイリアスです。 ASP.NET では、この情報を使用して、ページ内のサーバー コントロールを表示します。       使用方法については、ユーザー エージェント、またはそのエイリアスは、プログラムで、次を参照してください、<xref:System.Web.UI.Page.ClientTarget%2A?displayProperty=fullName>プロパティ。</xref:System.Web.UI.Page.ClientTarget%2A?displayProperty=fullName> 。 使用方法については、ユーザー エージェント、またはそのエイリアスは、宣言によって、次を参照してください。 [@ Page](http://msdn.microsoft.com/en-us/f06cf9e5-22bb-461d-8b8f-549e53ff40a4)です。       場合、<xref:System.Web.UI.Page.ClientTarget%2A?displayProperty=fullName>プロパティが設定されていない、<xref:System.Web.HttpBrowserCapabilities>オブジェクトに関連付けられている、<xref:System.Web.UI.Page.Request%2A?displayProperty=fullName>プロパティには、クライアント ブラウザーの機能が反映されます</xref:System.Web.UI.Page.Request%2A?displayProperty=fullName></xref:System.Web.HttpBrowserCapabilities></xref:System.Web.UI.Page.ClientTarget%2A?displayProperty=fullName>。 (ブラウザーの種類は必ずしもそのブラウザーの特定のインスタンスの設定の機能を反映)。プロパティを設定すると、クライアント ブラウザーの検出が無効になり、ページが定義したユーザー エージェント文字列に関連付けられているブラウザーの機能を使用します。 任意の有効なユーザー エージェント文字列には、このプロパティを設定することができます。"
  example:
  - "This section provides two code examples. The first demonstrates how to declaratively specify values for several properties of the ClientTarget class. The second shows how to obtain the <xref:System.Web.Configuration.ClientTargetCollection> object from the configuration file. You use this object to access the ClientTarget objects it contains.  \n  \n The following code example shows how to declaratively specify values for several properties of the ClientTarget class.  \n  \n```  \n<clientTarget>  \n  <add alias=  \n    \"uplevel\"   \n    userAgent=\"Mozilla/5.0 (compatible;MSIE 6.0;Windows NT 5.1)\"/>  \n  <add alias=\"downlevel\" userAgent=\"Generic Downlevel\"/>  \n</clientTarget>  \n```  \n  \n The following code example shows how to obtain the <xref:System.Web.Configuration.ClientTargetCollection> object from the configuration file.  \n  \n [!code-vb[System.Web.Configuration.ClientTarget#1](~/add/codesnippet/visualbasic/t-system.web.configurati_29_1.vb)]\n [!code-cs[System.Web.Configuration.ClientTarget#1](~/add/codesnippet/csharp/t-system.web.configurati_29_1.cs)]"
  syntax:
    content: 'public sealed class ClientTarget : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.ClientTarget.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.ClientTarget
  langs:
  - csharp
  name: ClientTarget(String,String)
  nameWithType: ClientTarget.ClientTarget(String,String)
  fullName: System.Web.Configuration.ClientTarget.ClientTarget(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Web.Configuration.ClientTarget&quot;> </xref>クラスです。"
  syntax:
    content: public ClientTarget (string alias, string userAgent);
    parameters:
    - id: alias
      type: System.String
      description: "特定のユーザー エージェントを参照するために使用する名前です。"
    - id: userAgent
      type: System.String
      description: "ユーザー エージェントの識別名。"
  overload: System.Web.Configuration.ClientTarget.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ClientTarget.Alias
  id: Alias
  parent: System.Web.Configuration.ClientTarget
  langs:
  - csharp
  name: Alias
  nameWithType: ClientTarget.Alias
  fullName: System.Web.Configuration.ClientTarget.Alias
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "ユーザー エージェントのエイリアスを取得します。"
  remarks: "エイリアスのプロパティを指す、`alias`の属性、`add`内の要素、`clientTarget`構成ファイルのセクションです。       ASP.NET 構成の既定値には、次のエイリアスが含まれます:- `uplevel`、HTML および Internet Explorer 6.0 とそれ以降のバージョンでサポートする ECMAScript に送信する ASP.NET に指示します。      - `downlevel`HTML と Internet Explorer 6.0 より前のブラウザーでサポートされているバージョンにスクリプトを制限する ASP.NET に指示します。"
  example:
  - "The following code example shows how to get the Alias from the configuration file of an existing Web application.  \n  \n [!code-vb[System.Web.Configuration.ClientTarget#3](~/add/codesnippet/visualbasic/p-system.web.configurati_91_1.vb)]\n [!code-cs[System.Web.Configuration.ClientTarget#3](~/add/codesnippet/csharp/p-system.web.configurati_91_1.cs)]"
  syntax:
    content: public string Alias { get; }
    return:
      type: System.String
      description: "特定のユーザー エージェントを参照するために使用する名前です。"
  overload: System.Web.Configuration.ClientTarget.Alias*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ClientTarget.Properties
  id: Properties
  parent: System.Web.Configuration.ClientTarget
  langs:
  - csharp
  name: Properties
  nameWithType: ClientTarget.Properties
  fullName: System.Web.Configuration.ClientTarget.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "追加します。"
  overload: System.Web.Configuration.ClientTarget.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ClientTarget.UserAgent
  id: UserAgent
  parent: System.Web.Configuration.ClientTarget
  langs:
  - csharp
  name: UserAgent
  nameWithType: ClientTarget.UserAgent
  fullName: System.Web.Configuration.ClientTarget.UserAgent
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "ユーザー エージェントの識別名を取得します。"
  remarks: "UserAgent プロパティを指す、`userAgent`の属性、`add`内の要素、`clientTarget`構成ファイルのセクションです。       ASP.NET 構成の既定値は、さまざまな Microsoft Internet Explorer のバージョンのページをカスタマイズできるようにします。 それらの間、別名を検索`uplevel`、HTML および ECMAScript でサポートされている Internet Explorer 4.0 以降、クライアントに送信する ASP.NET に指示するおよび`downlevel`HTML と Internet Explorer 4.0 より前のブラウザーがサポートするスクリプトを制限する ASP.NET に指示します。"
  example:
  - "The following code example shows how to get the UserAgent from the configuration file of an existing Web application.  \n  \n [!code-vb[System.Web.Configuration.ClientTarget#4](~/add/codesnippet/visualbasic/p-system.web.configurati_190_1.vb)]\n [!code-cs[System.Web.Configuration.ClientTarget#4](~/add/codesnippet/csharp/p-system.web.configurati_190_1.cs)]"
  syntax:
    content: public string UserAgent { get; }
    return:
      type: System.String
      description: "ユーザー エージェントの識別名。"
  overload: System.Web.Configuration.ClientTarget.UserAgent*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.ClientTarget.#ctor(System.String,System.String)
  parent: System.Web.Configuration.ClientTarget
  isExternal: false
  name: ClientTarget(String,String)
  nameWithType: ClientTarget.ClientTarget(String,String)
  fullName: System.Web.Configuration.ClientTarget.ClientTarget(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.ClientTarget.Alias
  parent: System.Web.Configuration.ClientTarget
  isExternal: false
  name: Alias
  nameWithType: ClientTarget.Alias
  fullName: System.Web.Configuration.ClientTarget.Alias
- uid: System.Web.Configuration.ClientTarget.Properties
  parent: System.Web.Configuration.ClientTarget
  isExternal: false
  name: Properties
  nameWithType: ClientTarget.Properties
  fullName: System.Web.Configuration.ClientTarget.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.ClientTarget.UserAgent
  parent: System.Web.Configuration.ClientTarget
  isExternal: false
  name: UserAgent
  nameWithType: ClientTarget.UserAgent
  fullName: System.Web.Configuration.ClientTarget.UserAgent
- uid: System.Web.Configuration.ClientTarget.#ctor*
  parent: System.Web.Configuration.ClientTarget
  isExternal: false
  name: ClientTarget
  nameWithType: ClientTarget.ClientTarget
- uid: System.Web.Configuration.ClientTarget.Alias*
  parent: System.Web.Configuration.ClientTarget
  isExternal: false
  name: Alias
  nameWithType: ClientTarget.Alias
- uid: System.Web.Configuration.ClientTarget.Properties*
  parent: System.Web.Configuration.ClientTarget
  isExternal: false
  name: Properties
  nameWithType: ClientTarget.Properties
- uid: System.Web.Configuration.ClientTarget.UserAgent*
  parent: System.Web.Configuration.ClientTarget
  isExternal: false
  name: UserAgent
  nameWithType: ClientTarget.UserAgent
