### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  id: FileAssociation
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.#ctor
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDefaultIcon
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDescription
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlExtension
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlProgId
  langs:
  - csharp
  name: FileAssociation
  nameWithType: FileAssociation
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  type: Class
  summary: "アプリケーションに関連するファイル名拡張子を表します。"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class FileAssociation
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.#ctor
  id: '#ctor'
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: FileAssociation()
  nameWithType: FileAssociation.FileAssociation()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.FileAssociation()
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "新しいインスタンスを初期化、 <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation&quot;> </xref>クラスです。"
  syntax:
    content: public FileAssociation ();
    parameters: []
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon
  id: DefaultIcon
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: DefaultIcon
  nameWithType: FileAssociation.DefaultIcon
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "特定の<xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension*>。</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension*>を使用しているファイルに使用するアイコンを取得または"
  syntax:
    content: public string DefaultIcon { get; set; }
    return:
      type: System.String
      description: "アイコンを含むファイルの名前。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description
  id: Description
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: Description
  nameWithType: FileAssociation.Description
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "取得またはシェルで使用するためのファイルの種類の説明を設定します。"
  syntax:
    content: public string Description { get; set; }
    return:
      type: System.String
      description: "ファイルの種類の説明です。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension
  id: Extension
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: Extension
  nameWithType: FileAssociation.Extension
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "取得またはアプリケーションに関連するファイル名拡張子を設定します。"
  syntax:
    content: public string Extension { get; set; }
    return:
      type: System.String
      description: "アプリケーションに関連するファイル名拡張子。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId
  id: ProgId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: ProgId
  nameWithType: FileAssociation.ProgId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "取得またはファイルの関連付けのファイルの種類を一意に識別する名前を設定します。"
  syntax:
    content: public string ProgId { get; set; }
    return:
      type: System.String
      description: "ファイルの種類を一意に識別する名前。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDefaultIcon
  id: XmlDefaultIcon
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: XmlDefaultIcon
  nameWithType: FileAssociation.XmlDefaultIcon
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDefaultIcon
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "ファイルの関連付けをシリアル化に使用されているプロパティの設定を取得または<xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon*>プロパティを XML ファイル</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon*>。"
  syntax:
    content: public string XmlDefaultIcon { get; set; }
    return:
      type: System.String
      description: "このファイルの関連付けの DefaultIcon の XML 表現。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDefaultIcon*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDescription
  id: XmlDescription
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: XmlDescription
  nameWithType: FileAssociation.XmlDescription
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDescription
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "ファイルの関連付けをシリアル化に使用されているプロパティの設定を取得または<xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description*>プロパティを XML ファイル</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description*>。"
  syntax:
    content: public string XmlDescription { get; set; }
    return:
      type: System.String
      description: "このファイルの関連付けの XML 表現<xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description*>値</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description*>。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDescription*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlExtension
  id: XmlExtension
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: XmlExtension
  nameWithType: FileAssociation.XmlExtension
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlExtension
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "ファイルの関連付けをシリアル化に使用されているプロパティの設定を取得または<xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension*>プロパティを XML ファイル</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension*>。"
  syntax:
    content: public string XmlExtension { get; set; }
    return:
      type: System.String
      description: "このファイルの関連付けの XML 表現<xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension*>値</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension*>。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlExtension*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlProgId
  id: XmlProgId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: XmlProgId
  nameWithType: FileAssociation.XmlProgId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlProgId
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "取得または設定のシリアル化に使用されているプロパティ、<xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId*>プロパティを XML ファイル</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId*>。"
  syntax:
    content: public string XmlProgId { get; set; }
    return:
      type: System.String
      description: "このファイルの関連付けの XML 表現<xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId*>値</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId*>。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlProgId*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.#ctor
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: FileAssociation()
  nameWithType: FileAssociation.FileAssociation()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.FileAssociation()
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: DefaultIcon
  nameWithType: FileAssociation.DefaultIcon
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: Description
  nameWithType: FileAssociation.Description
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: Extension
  nameWithType: FileAssociation.Extension
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: ProgId
  nameWithType: FileAssociation.ProgId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDefaultIcon
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: XmlDefaultIcon
  nameWithType: FileAssociation.XmlDefaultIcon
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDefaultIcon
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDescription
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: XmlDescription
  nameWithType: FileAssociation.XmlDescription
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDescription
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlExtension
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: XmlExtension
  nameWithType: FileAssociation.XmlExtension
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlExtension
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlProgId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: XmlProgId
  nameWithType: FileAssociation.XmlProgId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlProgId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.#ctor*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: FileAssociation
  nameWithType: FileAssociation.FileAssociation
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: DefaultIcon
  nameWithType: FileAssociation.DefaultIcon
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: Description
  nameWithType: FileAssociation.Description
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: Extension
  nameWithType: FileAssociation.Extension
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: ProgId
  nameWithType: FileAssociation.ProgId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDefaultIcon*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: XmlDefaultIcon
  nameWithType: FileAssociation.XmlDefaultIcon
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDescription*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: XmlDescription
  nameWithType: FileAssociation.XmlDescription
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlExtension*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: XmlExtension
  nameWithType: FileAssociation.XmlExtension
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlProgId*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: XmlProgId
  nameWithType: FileAssociation.XmlProgId
